### ISSUE TITLE
editable suffix for extra_data, but a drop down for the bids modalities

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#10]
The suffix should be freely editable for extra_data, as these are series not part of BIDS, but the user may want to make them BIDS-like. The opposite is true for the BIDS-modalities, where the suffix should comply to the standard. The possible suffices are first of all defined in the bidsmap_template.yaml, but also in the samples-tree (used by the bidstrainer): ./heuristics/samples/. E.g. for 'anat', the suffix (modality_label) can be 'angio', 'defacemask', etc, but for 'func' it can be 'bold', 'events', etc.
```
/home/mrphys/marzwi/python/bidscoin/heuristics/samples/
|-- README.txt
|-- anat
|   |-- FLAIR
|   |-- FLASH
|   |-- PD
|   |-- PDT2
|   |-- PDmap
|   |-- SWImagandphase
|   |-- T1map
|   |-- T1rho
|   |-- T1w
|   |-- T2map
|   |-- T2star
|   |-- T2w
|   |-- angio
|   |-- defacemask
|   |-- inplaneT1
|   `-- inplaneT2
|-- beh
|   |-- beh
|   |-- events
|   |-- physio
|   `-- stim
|-- dwi
|   |-- dwi
|   `-- sbref
|-- fmap
|   |-- epi
|   |-- fieldmap
|   |-- magnitude
|   |-- magnitude1
|   |-- magnitude2
|   |-- phase1
|   |-- phase2
|   `-- phasediff
|-- func
|   |-- bold
|   |-- events
|   |-- physio
|   |-- sbref
|   `-- stim
`-- pet
    `-- pet
```

**Comment by marcelzwiers** [comment]
Now MODALITY_LABELS has a special status in the code, I suppose this needs to be completely removed

**Comment by rutgervandeelen** [comment]
The following has been changed in the `refactor_bidseditor` branch:
* The `/heuristics` yaml files have been made consistent, such as the template file
* The fixed list of allowed suffixes is obtained solely from the template file (the `/heuristics/samples/` directories are ignored)
* `modality_label` for `anat` is renamed to `suffix` (just like for all the other modalities)
* The dropdown selection has been repaired
* The (empty) BIDS attributes are derived from the template and subsequently enriched using the data in the input BIDS map yaml file
* The tests have been updated
