### ISSUE TITLE
bval and bvec dummy files are generated for sbref dwi images

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#101]
I have a `sbref` sequence of `dwi` type. If I categorize it like that, [dummy `bval` and `bvec` files containing `0`s are generated](https://github.com/Donders-Institute/bidscoin/blob/f8a6cd6b24d48d31b9867a92c18b4cd6106ff641/bidscoin/plugins/dcm2niix2bids.py#L298). BIDS validator complains on it with, for example:
```
./sub-0629/dwi/sub-0629_dir-AP_sbref.bval
                        Files with such naming scheme are not part of BIDS specification.
``` 
[BIDS documentation](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data) says that the `sbref`suffix for single band reference image is allowed only if the image has no corresponding gradient information.

For this particular image dcm2niix doesn't extract any gradient information. Then, is creating these dummy files necessary?

**Comment by marcelzwiers** [comment]
Interestingly, because I added the following lines in the past because the validator complained about missing bval/vec files:
```python
            # Add a dummy b0 bval- and bvec-file for any file without a bval/bvec file (e.g. sbref, b0 scans)
            if datatype == 'dwi':
                bvecfile = jsonfile.with_suffix('.bvec')
                bvalfile = jsonfile.with_suffix('.bval')
                if not bvecfile.is_file():
                    LOGGER.info(f"Adding dummy bvec file: {bvecfile}")
                    bvecfile.write_text('0\n0\n0\n')
                if not bvalfile.is_file():
                    LOGGER.info(f"Adding dummy bval file: {bvalfile}")
                    bvalfile.write_text('0\n')
```
Thanks for reporting this updated behaviour, I will remove the lines now
