### ISSUE TITLE
Compatibility for physio-data in the format .puls, .ecg, etc. 

### ISSUE THREAD

**Issue by TomW92** [Donders-Institute/bidscoin#103]
Hi there,

Our manually collected Siemens physio-data has an output format as mentioned in the title and also [here](https://gitlab.ethz.ch/physio/physio-doc/-/wikis/MANUAL_PART_READIN) (Siemens -> Manual Recording). 
**physio.py** only seems to accept  _*.log_ files. 
I thought about just changing the suffix of the _.puls_ files by adding _*.log_.

That seems to basically work, but **physio2tsv** still crashes because additionally, _physio_info.log_ does not exist.
What would be the easiest or the best way to make this work, or is it implemented somewhere else?

Many thanks in advance!

Best
Tom

**Comment by marcelzwiers** [comment]
I don't have a lot of experience myself with physiological data, I simply ported [this](https://github.com/CMRR-C2P/MB) matlab code to python (and pushed it back upstream). I will have a short look, but the plan is to move physio.py to phys2bids, so perhaps @smoia or someone else from the physiopy team can help you out if I can't fix it easily? So you have data from the CMRR sequence or from the Siemens product sequence?

**Comment by marcelzwiers** [comment]
Oh I see, you used the product sequence. Mhhh, that will probably require some new code...

**Comment by smoia** [comment]
@TomW92, would you be able to give us a file or two to implement an interface to deal with that type?
Is so, please open an issue in [physiopy/phys2bids](https://github.com/physiopy/phys2bids).

Thank you!

**Comment by TomW92** [comment]
Thank you both for the swift reply.
Yes, I am going to open an issue over at physiopy.
