### ISSUE TITLE
improve dynamic documentation using NIDM-terms

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/bidscoin#105]
In a BIDS meeting today @dbkeator and @nqueder demonstrated https://nidm-terms.github.io/ and the corresponding (github/json)  backend in https://github.com/NIDM-Terms/terms/tree/master/terms

It would be great if the description field of all defined terms in NIDM-terms were used as tooltip help in the BIDScoin gui. That would require copying/converting the information from https://github.com/NIDM-Terms/terms/blob/master/terms/BIDS_Terms.jsonld into a format that can be used for help

**Comment by marcelzwiers** [comment]
Nice, I'll have a look. Currently, I use the [BIDS schema files](https://github.com/bids-standard/bids-specification/tree/master/src/schema) to populate tooltips

**Comment by marcelzwiers** [comment]
In particular, the BIDS [entities](https://github.com/bids-standard/bids-specification/blob/master/src/schema/entities.yaml ) file

**Comment by robertoostenveld** [comment]
Oh that is great! In that case you don't have to change anything. 

It is not yet clear whether the flow of information/updates will be `BIDS-schema` -> `NIDM-terms` or `NIDM-terms` -> `BIDS-schema`, but if you pick the info up from either one (and occasionally update), it should be in sync with both of them.
