### ISSUE TITLE
Disucssion on data anonymization

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#109]
I've found that BIDScoin [shifts the acquisition dates](https://github.com/Donders-Institute/bidscoin/blob/6c33ac3ce00bcfb781b8384aecc1110f14246485/bidscoin/plugins/dcm2niix2bids.py#L396). Are there any other anonymization tasks performed by BIDScoin?

BIDScoin also ships with a [defacing tool](https://bidscoin.readthedocs.io/en/stable/finalizing.html#defacing) based on [pydeface](https://github.com/poldracklab/pydeface).

I think that it would be good not to "hide" data anonymization within BIDScoin but rather delegate it to another step in data preparation. I've recently found [BIDSonym](https://peerherholz.github.io/BIDSonym/index.html#) which is a comprehensive tool to do exactly that task.

Another idea would be to have a switch for anonymizing data by BIDScoin, like `--anonymize` flag, that makes the anonymization task more transparent.

**Comment by marcelzwiers** [comment]
Well, I do not anonymize anything, I just followed the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file) and avoid adding sensitive information"

> For anonymization purposes all dates within one subject should be shifted by a randomly chosen (but consistent across all recordings) number of days. This way relative timing would be preserved, but chances of identifying a person based on the date and time of their scan would be decreased. Dates that are shifted for anonymization purposes SHOULD be set to the year 1925 or earlier to clearly distinguish them from unmodified data. Shifting dates is RECOMMENDED, but not required.

But it is indeed not required, I will make it optional. I don't think there is anything else that I do, and the defacing tools are separate and not part of the standard BIDScoin workflow.

**Comment by marcelzwiers** [comment]
I added an anonymization flag to the dcm2niix2bids plugin settings (bidsmap -> Options -> dcm2niix -> anon) with this 920aad866c51f00f2e33977da8d8e6ea6daa9e45 commit
