### ISSUE TITLE
Add help buttons

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#11]
It could help users if they would be pointed to online(?) documentation at a few places. Here are some options:
* Main window
  * A help button that points to the README.md documents (e.g. on github), as show in the 'reset button' issue (https://github.com/Donders-Institute/bidscoin/issues/9), or perhaps render the document in a separate tab if it that is not to heavy (see e.g. https://github.com/AndrewRadev/quickmd)
* Edit window
  * A help button that points to the BIDS documentation, e.g. to https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data for 'anat' and to https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data for dwi, etc

![image](https://user-images.githubusercontent.com/15156015/58463993-2ffefa80-8135-11e9-9abd-a4cbfc428a6d.png)

**Comment by rutgervandeelen** [comment]
Could you be so kind to provide the help URL for each modality in the Edit window? I currently have the following in `bidseditor.py`:

```
HELP_URLS = {
    "anat": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data",
    "dwi": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data",
    "beh": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/07-behavioral-experiments.html",
    bids.unknownmodality: "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html"
}
```

What are the help URLs for `func`, `fmap`, `pet` and `bids.unknownmodality`?

**Comment by marcelzwiers** [comment]
`func` https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#task-including-resting-state-imaging-data
`fmap` https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data
`pet` https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0/edit
`bids.unknownmodality` https://bids-specification.readthedocs.io/en/latest/

The latter should be the default / general help if there is no specific help page

**Comment by rutgervandeelen** [comment]
Thank you. The help buttons ar implemented using the following URLs:

```
MAIN_HELP_URL = "https://github.com/Donders-Institute/bidscoin/blob/master/README.md"

EDIT_HELP_URL_DEFAULT = "https://bids-specification.readthedocs.io/en/latest/"

EDIT_HELP_URLS = {
    "anat": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data",
    "beh": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/07-behavioral-experiments.html",
    "dwi": "https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data",
    "fmap": "https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data",
    "func": "https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#task-including-resting-state-imaging-data",
    "pet": "https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0/edit",
    bids.unknownmodality: EDIT_HELP_URL_DEFAULT
}
```
