### ISSUE TITLE
no prefix syntax?

### ISSUE THREAD

**Issue by Moo-Marc** [Donders-Institute/bidscoin#121]
I'm just trying this tool since I was unhappy with Heudiconv.  One issue I ran into is how to deal with no prefix for subject or session.  When running bidsmapper with no optional arguments, it prints subprefix=None erroneously (since it's using sub- by default).  And it doesn't accept an empty string; it complains not finding subjects: sub-*.  How do you specify no prefix?

> 2022-01-19 16:33:29 - INFO | 
> 2022-01-19 16:33:29 - INFO | -------------- START BIDSmapper ------------
> 2022-01-19 16:33:29 - INFO | >>> bidsmapper sourcefolder=/export02/data/marcl/OMEGA/MRITest bidsfolder=/export02/data/marcl/OMEGA/BidsCoin bidsmap=bidsmap.yaml template=/export02/data/marcl/Software/Python/lib/python3.10/site-packages/bidscoin/heuristics/bidsmap_dccn.yaml plugins=[] subprefix= sesprefix= store=False
> 2022-01-19 16:33:29 - INFO | No existing bidsmap file found: /export02/data/marcl/Software/Python/lib/python3.10/site-packages/bidscoin/heuristics/bidsmap.yaml
> 2022-01-19 16:33:29 - INFO | Reading: /export02/data/marcl/Software/Python/lib/python3.10/site-packages/bidscoin/heuristics/bidsmap_dccn.yaml
> 2022-01-19 16:33:30 - WARNING | No subjects found in: /export02/data/marcl/OMEGA/MRITest/**sub-***

Also, when pressing the "test" button after the editor opened (with no subjects), it crashes.

>  Traceback (most recent call last):
>  File "/export02/data/marcl/Software/Python/lib/python3.10/site-packages/bidscoin/bidseditor.py", line 726, in test_bidscoin
>     if bidscoin.test_bidscoin(options=self.output_bidsmap['Options'], testplugins=False):
> TypeError: test_bidscoin() missing 1 required positional argument: 'bidsmapfile'
> Aborted (core dumped)

Thanks!

**Comment by Moo-Marc** [comment]
If I may add another question: is dicomsort able to run on files without extension?  I haven't been able to run it so far, it just does nothing and outputs no message.  I tried the pattern ".*" and gave it the folder containing a single dicom series (from a DICOMDIR folder structure).  Cheers

**Comment by marcelzwiers** [comment]
Mhhh, subject/session without prefix are a little bit tricky at the moment (I started bidscoin for internal usage, and we always have a prefix here), but I will refactor my code a bit and see what I can do. Missing DICOMDIR files are a bit troublesome in my view, but I can of course add an option to ignore that and continue

**Comment by Moo-Marc** [comment]
Thanks.  I ended up going with Heudiconv because I have a lot of images from different studies so having rules made more sense than a mapping in my case.  Maybe as a quick "fix" you can just make it clearer that it requires prefixes (and remove the places where the default is "=None").  I'm a bit unsure why some files are missing, but since I only wanted the T1, it didn't matter to me in the other sequences.  Cheers and thanks for sharing!

**Comment by marcelzwiers** [comment]
Fair enough, if you can define a small set of heudiconv rules that, then it could be easier that way. Thanks for your feedback, I'll take it into account for the next (point) release)

**Comment by marcelzwiers** [comment]
I know you reverted to heudiconv, but I think I solved the (very valid) BIDScoin issues/use-case you raised here (see the updated doc [here](https://bidscoin.readthedocs.io/en/latest/workflow.html)). Thanks for the feedback anyway
