### ISSUE TITLE
Handle duplicated fieldmaps in interrupted session

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#123]
**General summary**

I'm trying to [develop an end-to-end solution](https://frosch.cosy.sbg.ac.at/anc/data-ccns-documentation/-/issues/14) for handling duplicated fieldmaps in the case of interrupted sessions. I'm wandering what would be the best BIDScoin-based solution for that.

**Additional detail**

I briefly described the [problem of interrupted sessions](https://frosch.cosy.sbg.ac.at/anc/data-ccns-documentation/-/blob/main/format/datatypes/mri-conversion.md#interrupted-acquisitions). The scenario is the following. The experiment consists of more than one functional scans, lets say `task-1` and `task-2`. The fieldmaps are acquired. Some time after the first functional scan, the subject has to leave the scanner. Hence, the fieldmaps have to be acquired again after the return to the scanner. This leads to a situation when two sets of fieldmaps have to be kept, one for `task-1` and another for `task-2`. The names of fieldmaps scans are not modified on the scanner.

The interruption is not consistent among subjects and, in case of multiple functional scans, can happen anytime. Using automatic `run-` indexes lets us differentiate the fieldmaps. However, this is applied to fieldmaps of all subjects, even if some subjects do not have duplicates. Moreover, if duplicated fieldmaps are not intended for specific scans consistently, this needs to be done manually. 

**Next steps**

- No steps at the moment.

**Comment by marcelzwiers** [comment]
Mhhh, this requires a bit of logic on top of the glob() search approach. But it's a fair point, I'll see what I can do

**Comment by mateuszpawlik** [comment]
A viable consistent solution, but I'm not sure if within the scope of BIDScoin, could be the following. The fieldmaps are intended for any task that is acquired after them but before another filedmaps, if they're present, and so on.

**Comment by marcelzwiers** [comment]
I am thinking of extending the bidsmap language a bit, e.g. with a colon-separated slicing term:
```
IntendedFor: <<taskname:[-1]>>
```
This would select the last task run only
```
IntendedFor: <<taskname:[-2:]>>
```
would select the last two runs
```
IntendedFor: <<taskname:[0:3]>>
```
would select the first two runs

**Comment by marcelzwiers** [comment]
But this doesn't solve your problem

**Comment by marcelzwiers** [comment]
A workaround would be to use hardcoded run-indexes (i.e. `1` instead of `<<1>>`) in the template bidsmap, but that's a bit hacky

**Comment by mateuszpawlik** [comment]
Thanks for a quick feedback. I think, that is exactly the problem. I'll sleep over it :-)

**Comment by marcelzwiers** [comment]
It's a bit convoluted to implement, but the problem at hand is a bit convoluted, so there is no way around it I think. I am currently thinking of:

```
IntendedFor: <<taskname:[-4:0]>>
```
Select maximally four preceding 'taskname' runs until a fieldmap with the same name but with a smaller run index
```
IntendedFor: <<taskname:[0:3]>>
```
Select maximally three subsequent 'taskname' runs until a fieldmap with the same name but with a larger run index
```
IntendedFor: <<taskname:[-2:2]>>
```
Select maximally two preceeding/subsequent 'taskname' runs until a fieldmap with the same name but with a smaller or larger run index

**Comment by marcelzwiers** [comment]
I implemented the above, but haven't tested it, could you perhaps give it a try?

**Comment by mateuszpawlik** [comment]
Wow! Thank you :-) I knew it wasn't trivial to do and haven't expected any implementation. I'm more than happy to test it. But I may not be done today.

**Comment by mateuszpawlik** [comment]
It seems to work on one example but let me do more testing.

**Comment by marcelzwiers** [comment]
I actually thought about making it even more general, such as allowing for using json data to select files, e.g. <<IntendedFor:{EchoTime: 40}>>. I can still do that if needed, but the IntendedFor system is going to change in future BIDS versions, so I thought to keep it a bit more simple till then

**Comment by mateuszpawlik** [comment]
> but the IntendedFor system is going to change in future BIDS versions

Could you point me to any information about it?

**Comment by marcelzwiers** [comment]
I saw discussions on various places, e.g.:
https://github.com/bids-standard/bids-specification/pull/622
https://github.com/bids-standard/bids-specification/issues/718

**Comment by mateuszpawlik** [comment]
I've started working on a [script to generate DICOM files](https://frosch.cosy.sbg.ac.at/anc/bids-misc-scripts/-/blob/generate-dicom/dicom-util/generate_dicom.py). I finally need some dummy data to test BIDS conversion. The important part is that dcm2niix can process the generated files without complaining too much. Once I'm done, I'll generate a few cases, test the interrupted sessions and come back here.

**Comment by mateuszpawlik** [comment]
I've generated DICOMs for three subjects with [DICOM generator](https://frosch.cosy.sbg.ac.at/anc/bids-misc-scripts#generate-dicom-files) and the following three configurations. I paste them at the end of the comment because GitHub doesn't support uploading JSON files here.

Dealing with the interrupted sessions works as expected with `run: <<1>>` and `IntendedFor: <<task:[0:3]>>` for the `fmap` section in the bidsmap file.

I tested it for the commit `0b7f3ef`. The HEAD commit `7ae1f58` fails.

`sub-1`:
```json
[
  {
    "ImageType" : "anat",
    "SeriesDescription" : "T1w"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri1"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri2"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri3"
  }
]
```

`sub-2`:
```json
[
  {
    "ImageType" : "anat",
    "SeriesDescription" : "T1w"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri1"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri2"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri3"
  }
]
```

`sub-3`:
```json
[
  {
    "ImageType" : "anat",
    "SeriesDescription" : "T1w"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri1"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri2"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri3"
  }
]
```

**Comment by mateuszpawlik** [comment]
I've tested it again with the commit 546d14a and it works as expected. Shall we close this issue?
