### ISSUE TITLE
Edit participant and session label

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#13]
Particpant and session label are taken from the foldername unless it is specified in the bidsmap.yaml to take it from a DICOM-fields (some institutes may do so). It is a setting at the session level rather than at the series-level (which are now editable by separate (series-level) edit buttons), so a different interface should be used for this
```
DICOM:
# --------------------------------------------------------------------------------
# DICOM key-value heuristics (DICOM fields that are mapped to the BIDS labels)
# --------------------------------------------------------------------------------
  participant_label:                              # A <<DICOM attribute>> that is used as participant_label instead of the subject-label from the sourcefolder
  session_label:                                  # A <<DICOM attribute>> that is used as session_label instead of the session-label from the sourcefolder
```

**Comment by rutgervandeelen** [comment]
Should we put this in a separate tab `participant session` in the main window perhaps?

**Comment by marcelzwiers** [comment]
Yes, I was thinking the same

_____________________
Sent from my phone

Op vr 7 jun. 2019 16:14 schreef Rutger van Deelen <notifications@github.com

**Comment by rutgervandeelen** [comment]
The plan is to add this together with the DICOM input file listing in the same `BIDS map` tab.

**Comment by marcelzwiers** [comment]
see 84bb7fc67261641b407cdd11bc242b9d82920d6e
