### ISSUE TITLE
BIDScoin test fails; missing schema directory

### ISSUE THREAD

**Issue by smeisler** [Donders-Institute/bidscoin#130]
**Describe the bug**
The directory `schema` is missing from the BIDScoin python installation.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27028726/158026837-21dab85a-6a5e-4585-b46c-c68e86f28b32.png">

**To reproduce**
1. Create fresh Anaconda environment `conda create -n bidscoin -c conda-forge pip dcm2niix`
2. Install BIDScoin 3.7.1 `pip install bidscoin[deface]`
3. Test BIDScoin `bidscoin -t`

**Software version**
 - BIDScoin version 3.7.1
 - CentOs 7.

**Comment by marcelzwiers** [comment]
Oops, forgot to put _init__.py files to the schema folders (after copying them from the BIDS specification). I will release 3.7.2 a.s.a.p., thanks for reporting!

**Comment by marcelzwiers** [comment]
I've just released 3.7.2, the installation should now be ok
