### ISSUE TITLE
The bidseditor crashes when using a trackpad on MacOS

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#131]
**Describe the bug**
The bidseditor crashes on MacOS when you use your trackpad to click on the `[edit]` button. Everything works normally when you use a mouse, so this seems to be a bug in PyQt5 or in the upstream Qt5 library. The lines (559-560) of bidseditor code (where the position of the clicked widget is wrongly read) are:

```python
button   = self.focusWidget()
rowindex = samples_table.indexAt(button.pos()).row()
```

**Screenshots**
<img width="579" alt="trackpad_error" src="https://user-images.githubusercontent.com/15156015/159018619-50b560a2-1654-425e-b42e-8643e9d9fc7c.png">

**Software version**
BIDScoin 3.7.2
PyQt5 5.15.6
PyQt5-Qt5 5.15.2
PyQt5-sip 12.9.1
macOS Catalina Version 10.15.7

**Comment by bendhouseart** [comment]
@marcelzwiers am able to reproduce this bug occasionally... 

Seems to depend on where initial clicking occurs, have noticed while adding plugin to bidscoin.

Observed: Crashes when `row_index` at [bidseditor line 560](https://github.com/Donders-Institute/bidscoin/blob/c40dba014c13dc378402c88b7dd7c6109e8d880d/bidscoin/bidseditor.py#L560) this error can be/is reproduced when `row_index=-1`. A bit stuck on it at the moment, but nice to hear that it's not just me.

*Software Versions*
BIDSCOIN 3.7.4
pandas
matplotlib
numpy
pydicom>=2
PyQt5>=5.12.1
ruamel.yaml>=0.15.35
coloredlogs
tqdm>=4.60.0
multiecho>=0.25
python-dateutil
nibabel
pypet2bids
bids_validator

macOS Monterey Version 12.5.1, running on Rosetta

**Comment by bendhouseart** [comment]
Should mention that this occurs with trackpad and external mouse as well.

**Comment by marcelzwiers** [comment]
Hi Anthony, nice to hear from you, didn't know you were still interested in (or working on) a BIDScoin plugin. Actually, I have worked quite a bit on implementing unit/integration tests, CI and documentation, and am about to release v3.8.0. It would be nice to squash this in...

p.s. let me know if you need help or input on your plugin

**Comment by marcelzwiers** [comment]
I tried to catch the event and log it. So if you want to try it, get the latest code and before running the bidseditor set BIDSCOIN_DEBUG=TRUE as an environment variable...

p.s. In the latest doc, I explained a bit better how the [extended attributes](https://bidscoin.readthedocs.io/en/latest/bidsmap.html#structure-and-content) (that I implemented at the time for the pet2bids plugin) work, hope that helps

**Comment by bendhouseart** [comment]
> Hi Anthony, nice to hear from you, didn't know you were still interested in (or working on) a BIDScoin plugin. Actually, I have worked quite a bit on implementing unit/integration tests, CI and documentation, and am about to release v3.8.0. It would be nice to squash this in...
> 
> p.s. let me know if you need help or input on your plugin

Had some delays on my end, but still very much interested as you've done the hard work of writing a nice GUI'd converter.  Will follow up with this in a different thread/draft PR though.

**Comment by bendhouseart** [comment]
> I tried to catch the event and log it. So if you want to try it, get the latest code and before running the bidseditor set BIDSCOIN_DEBUG=TRUE as an environment variable...

Ok, I see what you added [here](https://github.com/Donders-Institute/bidscoin/commit/2fe9328c19daded945d6f9c7dbbda505bdfbe20a) to catch it. I should mention that I'm only consistently seeing the crash when I've loaded the PET2BIDS plugin and click on the edit button in the window below

**Comment by marcelzwiers** [comment]
I see that you only have one run-item (which makes sense for PET), which is probably the reason of the crash, because the bidseditor doesn't interact with the plugins

**Comment by bendhouseart** [comment]
> 

Well now you're just confusing me b/c when it doesn't error out I get this:

<img width="1312" alt="Screen Shot 2023-01-06 at 9 44 37 AM" src="https://user-images.githubusercontent.com/28850131/211096864-d1f4d14f-962f-4cd5-903b-5d10e85180fc.png">

Merged in your latest changes from master into my fork's branch log is attached.

[bidsmapper.log](https://github.com/Donders-Institute/bidscoin/files/10362974/bidsmapper.log)

It should be noted that I haven't gotten it to crash while plugged into my docking station at work with a wired mouse, so yes perhaps that magic trackpad is the issue.

**Comment by marcelzwiers** [comment]
So, looks good or? Same as what I get: https://bidscoin.readthedocs.io/en/stable/screenshots.html#id3
With MRI you normally have a list of mappings, when you edit an item in the list you get the window you just showed? Or waht's confusing you?

**Comment by marcelzwiers** [comment]
Btw, one other thing (unrelated) I notice from your screenshot is that the filesize property doesn't seem to work... (I don't own a mac, so I can't check these things)

**Comment by bendhouseart** [comment]
> the filesize property doesn't seem to work

Ehh, I can live with that.

Speaking of Mac woes, Pyqt5 only runs m1 Macs via x86 emulation in rosetta (which took a while for me to figure out, too long in fact). It might be worth bumping bidscoin up to pyqt6 so Macintosh's can be brought more easily into the fold. I'd be happy to help with that after I get this plugin integrated.

**Comment by marcelzwiers** [comment]
> Speaking of Mac woes, Pyqt5 only runs m1 Macs via x86 emulation in rosetta (which took a while for me to figure out, too long in fact). It might be worth bumping bidscoin up to pyqt6 so Macintosh's can be brought more easily into the fold. I'd be happy to help with that after I get this plugin integrated.

I made a dumb one-to-one port to Qt6, wouldn't mind if you could test it out :-)
https://github.com/Donders-Institute/bidscoin/tree/qt6

**Comment by marcelzwiers** [comment]
Our computing infrastructure is still at CENTOS `v7`, but Qt6 requires `v8.4`, so I will postpone merging the qt6 branch into master until we upgrade our infrastructure. Moreover, Github Actions misses some libraries for `ubuntu-latest` (libEGL.so.1), and I don't know how to solve this
