### ISSUE TITLE
Error running bidscoin -t

### ISSUE THREAD

**Issue by andreifoldes** [Donders-Institute/bidscoin#132]
Hello

**Describe the bug**
When running bidscoin -t as per the tutorial I get the following:
2022-03-18 16:38:05 - ERROR | Failed to run:
module add dcm2niix; dcm2niix -u; module add dcm2niix; dcm2niix
Errorcode 1:

WARNING: Unsupported option '-u'
ERROR: Unable to locate a modulefile for 'dcm2niix'
ERROR: Unable to locate a modulefile for 'dcm2niix'
ERROR: Unable to locate a modulefile for 'add'
ERROR: Unable to locate a modulefile for 'dcm2niix'
ERROR: Unable to locate a modulefile for 'dcm2niix'

**To reproduce**
installed dcm2niix using conda, installed modules and installed bidscoin and then in my conda environment I run bidscoin -t

**Software version**
 - BIDS-version:           1.7.0
 - BIDScoin-version:       3.7.2,
 - Windows

**Comment by marcelzwiers** [comment]
I see, did you follow the windows path (e.g. `"C:\Program Files\dcm2niix\dcm2niix.exe"`), as described here?

https://bidscoin.readthedocs.io/en/stable/options.html#dcm2niix2bids-plugin

**Comment by andreifoldes** [comment]
Right! I forgot about that however when changing it to

`
path: "C:\Users\Username\Anaconda3\envs\fmri\Library\bin\dcm2niix.exe"   
`
I now get
```
2022-03-18 17:22:08 - ERROR | Failed to run:
dcm2niix -u; dcm2niix
Errorcode 5:
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20211006  MSC1916  (64-bit Windows)
 Error: invalid option '-u; dcm2niix'

Error: Input folder invalid: dcm2niix
```

Not sure where the -u is coming from...

**Comment by marcelzwiers** [comment]
Ok, sorry, the test is currently tailored to linux, as it sequentially executes two commands (`dcm2niix -u; dcm2niix`). This doesn't work like that on Windows indeed, I'll change the test. You can ignore the error, I think your installation is fine (but reopen this issue if it is not)
