### ISSUE TITLE
DICOM to BIDS (SIEMENS)

### ISSUE THREAD

**Issue by lizannea** [Donders-Institute/bidscoin#133]
**Describe the bug**
Dear BIDScoin Siemens users,

I have been trying to use BIDScoin 3.7.0 to convert my DWI DICOM data to BIDS format for the field maps. Unfortunately, the filed maps aren’t conform the standards due to an attached e1 (echo 1) and e2 (echo 2) to the following images:
- Magnitude 1
- Magnitude 2
- Phase difference

I read this could be solved by 'only' specifying the magnitude 1 after which the magnitude 2 will be picked up by BIDScoin, however this didn’t solve my error.

I have included an example of the conversions and the identified errors. Could you help me by pointing out how to change the setting so the e1 and e2 won’t get attached to the BIDS format.

Many thanks.

**Screenshots**
Files:
![image](https://user-images.githubusercontent.com/68213542/159194894-56522f20-e20c-4aa8-9acc-84b7e2bfbd69.png)

Errors:
![image](https://user-images.githubusercontent.com/68213542/159194955-ae22a617-8d85-434b-a792-d5b0d66be8f8.png)

**Software version**
 - BIDScoin version 3.7.0
 - Linux

**Tags**
@civier

**Comment by marcelzwiers** [comment]
Fieldmaps are a bit unpredictable in the way they are stored and converted by dcm2niix. I've tested various combinations, but your situation apparently wasn't one of them. Can you perhaps paste the part of the logs where the fieldmaps are converted? You can find it in: `[yourbidsfolder]/code/bidscoin/bidscoiner.log` (and search for `magnitude1` or so)

**Comment by marcelzwiers** [comment]
How are your DICOM files organized? Are the magnitude1 and magnitude2 images stored in one folder?

**Comment by lizannea** [comment]
Dear Marcel, 

Thank you for your quick response. 

I've included a screenshots of the bidscoiner log: 
<img width="1341" alt="Screenshot 2022-03-22 at 15 23 33" src="https://user-images.githubusercontent.com/68213542/159407725-3649279c-3ab8-4462-a15c-f9ebd1e22c22.png">

**Comment by lizannea** [comment]
Yes, the magnitude1 and magnitude2 are both stored in one DICOME folder.

**Comment by civier** [comment]
@marcelzwiers Hello Marcel, and thank so much for helping @lizannea with that. I co-supervise her, and you're a great help for us! (I'm Oren from SOVABIDS, if you don't make the connection yet ;-)

Do you mind if I ask you something?
I understand that in the Donders you run bidscoiner on a system that has modules. May I ask if you also run bidsmapper on the same system? The issue is that I know of very few systems that has both the modules system and GUI, so I'm curious.
(I aware it's a bit off-topic, so if you prefer, you'e welcome to respond to my email instead. It's in my Github profile page)

**Comment by marcelzwiers** [comment]
Hi Oren,

Our users mostly have Windows machines and to access our HPC / use linux tools, we also have a small number of shared linux login/head/desktop nodes (from which they can submit jobs to the cluster). These login nodes are identical to the cluster nodes (useful for testing jobs) and hence also share the same modules

**Comment by marcelzwiers** [comment]
![image](https://user-images.githubusercontent.com/15156015/159471063-fd6d1fbd-6ca5-40c2-adc5-60e3062bcbb8.png)

**Comment by civier** [comment]
Thanks @marcelzwiers Very interesting setup.
It makes me think if the Neurodesk ecosystem (https://neurodesk.github.io/) to which I contribute can simplify your setup, but I'm too busy this week to write you about it.
I'll write you when I have more time, but you are welcome to check the website in the meantime.

**Comment by lizannea** [comment]
Hi Marcel, thank you so much for helping. 

The bidscoin -t gives the following output:
<img width="1284" alt="Screenshot 2022-03-22 at 22 46 17" src="https://user-images.githubusercontent.com/68213542/159475650-c2aa85f4-5c76-43f5-920a-b35b11af2638.png">
<img width="1284" alt="Screenshot 2022-03-22 at 22 46 39" src="https://user-images.githubusercontent.com/68213542/159475669-c6fee04b-1038-4d03-9d2b-735f991cc2ab.png">

**Comment by marcelzwiers** [comment]
Did you get any other warnings/errors? After the conversion there should have been a renaming step which I don't see. Did you change any of the BIDScoin Options?

I cannot reproduce this issue with our product fieldmap sequence, would it be possible to share the fmap seriesfolders with me? I would only need the top slice or so (i.e. one magnitude1, one magnitude2 and one phasediff DICOM image)... Also, the bidscoiner.log file would be helpful

**Comment by lizannea** [comment]
Hi Marcel, I'm unsure if this is related but after removing the "module add dcm2niix" from {command: module add dcm2niix; dcm2niix}. I re-ran the BIDScoiner comment, and the correct BIDS format was generated.. 

Thank you so much for you help!

**Comment by lizannea** [comment]
![Screenshot 2022-03-24 at 13 28 08](https://user-images.githubusercontent.com/68213542/159829931-6861bdfc-eb90-4092-b3ea-368a0e3fd2a2.png)
