### ISSUE TITLE
Having a filepath column in the BIDS editor GUI

### ISSUE THREAD

**Issue by civier** [Donders-Institute/bidscoin#134]
**Is your feature request related to a problem? Please describe.**
I'm using bidsmapper in order to find out what modality is stored in each sequence subfolder (the way our DICOMs are saved, the subfolders are simply the serial number of the sequence in the scanning session). Notice that I'm not interested in converting to BIDS, but I found BIDScoin to be very useful for the task at hand (thanks developers for a great software with so many use cases!).
Right now, I need to click "Edit" on each row in the "BIDS editor" window, and then maximise the "Edit BIDS mapping" window that opens in order to see the full filepath. This way I know that the specific sequence subfolder (the last part of the fullpath) has the modality of the row I'm editing.

**Describe the solution you'd like**
I want the "BIDS editor" to have a filepath column, and that if the filepath is long, the part of the string shown in the column will be the rightmost (so I can see the last part of the path). This way I can easily see what modality each subfolder is.

**Describe alternatives you've considered**
I guess that there are other software that can do that, but BIDScoin is already installed and it has very good heuristics to detect the modality of every sequence subfolder.
Other solutions I considered is somehow force BIDScoin to display a row in the "BIDS editor" window for EACH AND EVERY of the sequence subfolder. This way the serial number of the row will match with the sequence subfolder number. However, I see that BIDScoin often skips some sequence subfolders. I'm not sure why, but if that can be changed, please let me know.

**Additional context**
I attach a screenshot of the "BIDS editor" windows displaying 46 rows. whereas in practice there are 56 sequence subfolders for the specific participant.

<img width="1680" alt="Screen Shot 2022-04-12 at 5 12 21 pm" src="https://user-images.githubusercontent.com/8280611/162902214-2b53be1a-c4bc-484a-9bda-ce3ed6440e96.png">

**Comment by marcelzwiers** [comment]
In the main window, if you hover with your mouse over a file (either DICOM input or BIDS output), you can see the full path in the status bar at the bottom, is that not what you mean?

**Comment by marcelzwiers** [comment]
And with respect to your remark about the 46 rows vs 56 sequence subfolders, I presume that is because BIDScoin shows a (normally very short) list of the different data types, not a (very long) list of all the sequences of all the subjects

**Comment by civier** [comment]
Actually, all 56 folders are from the same subject.

Is it common for a scanner to save exactly the same data type across
several sequence folders? Does it usually happen when the same sequence is
being run multiple times? If not, when? (we have a Siemens scanner).

I can definitely check why there are multiple sequence folders with exactly
the same dicom header for the specific subject we scanned, but just wonder
about your experience with that?

Thanks ahead,
Oren

**Comment by marcelzwiers** [comment]
Yes, from the same subject or from multiple subject, BIDScoin shows a sequence only once (i.e. sequences are considered repeats if the subset of DICOM attributes have the same values)

**Comment by marcelzwiers** [comment]
So basically what you see in the bidseditor are the rules, i.e. how to convert each source datatype into a bids datatype. It's an overview of all the different types of scans, not an overview of all the data directories (because there would be many repeats)

**Comment by civier** [comment]
All clear now. I should think how this would affects converting scans where some sequences were repeated twice because the first scan didn't go well. Is there any recommended procedure on how to use BIDScoin in such situations?

Three points regarding the actual problem I had:

1) adding the AcquisitionTime to the attributes solved it, so I'm very happy now :-) Thank you so much.
I don't know how frequent it is that people actually want to ensure that each sequence folder has its own row in the GUI, but you might consider adding this option as a flag to BIDScoin (adding AcqusitionTime in many places in the template is tedious). For me, it will definitely be useful.

2) In cases where the sequence folders do not contain the serial number of the sequence (does it ever the case?), having a column with filepath might still be useful after all. It is true that the user can hover over the dicom file name and see the filepath, but still -- sometime a user might want to create a report of all the rows and their associated folders (by taking a screenshot), and this is impossible right now. Without being able to create a report, the BIDScoin GUI needs to be kept open, which is inconvenient.

3) I noticed that when I hover over the dicom filename in the "BIDS editor" GUI, there is small pop-up that says something like "double click to inspect the header information (Copy: Ctrl+C)". I guess that the Ctrl+C part refers to the fact that if I select the cell in the table, I can press Ctrl+C to copy it. If so, then it's quite confusing, because I initially thought it means that pressing Ctrl+C will copy the header information. It would be better to drop the "Copy: Ctrl+C" altogether, and instead, have a separate pop-up indicating Ctrl+C is available when the user actually selects the cell (or other cells in the table)

Hope this is helpful,
Oren

**Comment by marcelzwiers** [comment]
I admit it's a bit hidden, but [here](https://bidscoin.readthedocs.io/en/stable/preparation.html) it says:
> BIDScoin will skip (Linux-style hidden) files and folders starting with a . (dot) character. You can use this feature to flexibly omit subjects, sessions or runs from your bids repository, for instance when you restarted an MRI scan because something went wrong with the stimulus presentation and you don’t want that data to be converted and enumerated as run-1, run-2. Thanks for your feedback :-)
