### ISSUE TITLE
bidseditor GUI missing "DICOM mappings" and "PAR mappings" tabs

### ISSUE THREAD

**Issue by DanNBullock** [Donders-Institute/bidscoin#136]
**Describe the bug**
The bidscoin bidseditor GUI does not display tabs for "DICOM mappings" or "PAR mappings"  as depicted [here](https://bidscoin.readthedocs.io/en/stable/workflow.html#main-window).  Instead, it appears to be offering an interface that is essentially the same as the one provided by running the bidsmapper command.  It is quite possible that I am simply misusing the function, however the documentation leads me to expect the aforementioned GUI features in this context.

**To reproduce**
1. After running the default bidsmapper command (with inputs for SUBPREFIX and SESPREFIX)
2. An attempt is made to run bidseditor targeting the default bidsmap.yaml location (i.e. without specifying a particular bidsmap file)
3. However, the only tabs for "Options" and "Data browser" are available. These are the same that are produced/visible with bidsmapper.

**Expected behavior**
It was expected that the bidseditor GUI would include columns for "DICOM mappings" or "PAR mappings" 

**Screenshots**
Screenshot attached.  
- Upper left: command to start bidseditor targeting 'out' directory
- Upper right: bidseditor 3.7.2 interface without expected tabs "DICOM mappings" or "PAR mappings" 
- Lower left: bidscoin default directory structure with default outputs
- Lower right: contents of bidsmap.yaml file
![bidsCoinInterface](https://user-images.githubusercontent.com/13334205/167034326-ec952bff-fce5-4592-b505-2a40893ce900.png)

**Software version**
 - BIDScoin version: 3.7.2
 - OS Linux Ubuntu 21.04 MATE

**Additional context**
DICOM data is from NHP subjects, and may thus not exhibit standardized conventions

**Comment by marcelzwiers** [comment]
The bidseditor GUI show tabs for DICOM or PAR (or another format) mappings in the bidsmap. If the bidsmapper didn't find any DICOM (etc) source files, it doesn't show the (empty) tabs. So the bidseditor shows expected behaviour and the problem is that the bidsmapper is not looping over your subject/session directories. In order to understand what is going wrong I need to know the exact bidsmapper command and the full path to one of your DICOM files

**Comment by DanNBullock** [comment]
Thanks for the quick response!

In the previous example the bidseditor was run from the _hueDIConv_Test_ directory (apologies for the misnomer-I'm trying a lot of different approaches to resolve my bids-ificaiton problems).  _bidsmapper_ was previously run in this directory targeting the _subjects_ directory as the "sourcefolder" input and _out_ as the "bidsfolder", with additional inputs for prefixes (thus: bidsmapper subjects out -n 'ST' -m 'MR-SE').  The _subjects_ directory currently only contains one subject (directory named "ST001-NHP_Andrea-20190524") which itself contains ~60 directories, one for each scan session.  This appears to me to reflect the "flat DICOM organization" described on the [data preparation documentation page](https://bidscoin.readthedocs.io/en/latest/preparation.html#required-source-data-structure).  In this fashion, the path to an example DICOM file would be: 

`hueDIConv_Test/subjects/ST001-NHP_Andrea-20190524/MR-SE013-diff_pt58iso_fh_pat3_b1k2k_115dir_MR-ST001-SE013-0001.dcm`

![bidsEditor_interface](https://user-images.githubusercontent.com/13334205/167206118-67e10660-af39-497d-ab4f-ad9d57890bf7.png)
![terminal_output](https://user-images.githubusercontent.com/13334205/167206119-5330d230-5ffd-4514-b67b-44258bea0198.png)

(in the example, the bidsmap.yaml file was saved as bidsmap2.yaml, however this was later renamed to bidsmap.yaml.  Deleting these products and rerunning _bidsmapper_ resulted in the same GUI issue.)

**Comment by marcelzwiers** [comment]
Your sessions don't have a prefix `MR-SE` as they start e.g. with `MR-ST001-SE`. So try for instance `bidsmapper subjects out -n ST -m MR`?

**Comment by marcelzwiers** [comment]
But one thing you don't have sessions, so you should not use the `-m MR-SE` option

**Comment by DanNBullock** [comment]
I think I discovered the issue, in that there appears to have been a multitude of schemas used for naming and structuring the dicom files I am working with.  Apologies for the issue here.  I think my approach will be to manually identify the distinct schemas, and process each one separately with bidscoin.
