### ISSUE TITLE
module add dcm2niix fails (mac OS)

### ISSUE THREAD

**Issue by amhaun01** [Donders-Institute/bidscoin#137]
Hello, I'm trying to get this BIDScoin tool to work, and I am hung up immediately on the step that was the issue in this thread (https://github.com/Donders-Institute/bidscoin/issues/43)

testing fails on:

> 2022-05-25 15:47:13 - INFO | --------- Testing the 'dcm2niix2bids' plugin ---------
> 2022-05-25 15:47:13 - INFO | Succesfully imported 'dcm2niix2bids'
> 2022-05-25 15:47:13 - INFO | Testing the dcm2niix2bids installation:
> 2022-05-25 15:47:13 - INFO | Running: module add dcm2niix; dcm2niix -u; module add dcm2niix; dcm2niix
> 2022-05-25 15:47:13 - ERROR | Failed to run:
> module add dcm2niix; dcm2niix -u; module add dcm2niix; dcm2niix
> Errorcode 0:

I see something about "changing path" in the comments and above, but I don't understand what to do (what is "module add" etc).

dcm2niix is there and I can call it from command line, use it through matlab etc:

> (mri) andrews-imac:~ amhaun01$ which dcm2niix
> /Users/amhaun01/miniconda3/envs/mri/bin/dcm2niix

thanks for any help
-andrew

**Comment by amhaun01** [comment]
(nevermind)

**Comment by marcelzwiers** [comment]
If you can run dcm2niix from the command you don't need the `module add dcm2niix;` part (which will have no effect except that it will generate a warning). You can remove it as explained here:

https://bidscoin.readthedocs.io/en/stable/options.html#dcm2niix2bids-plugin
