### ISSUE TITLE
No dicom mapping results

### ISSUE THREAD

**Issue by landge** [Donders-Institute/bidscoin#138]
Hi,
I am trying to organize the CT-data from an imaging study that contains both CT, CT-angiography, and brain MR scans etc.

As suggested in the documentation, I have edited a template file and run bidsmapper. But bidsmapper does not find a single match apparently. At least no output or data samples are shown in the bidseditor. There is further no entry in the resulting bidsmap.yaml file.

I am not sure why this happens, but I get the feeling that I am missing something.
Our dicom files are organized in a sub-..../ses-.... directory structure.

This is my template:

anat:       # ----------------------- All anatomical runs --------------------
  - provenance: IM-0001-0001.dcm      
        attributes: &anat_dicomattr   # An empty / non-matching reference dictionary that can be derefenced in other run-items of this data type
      Modality: CT
      ProtocolName:
      SeriesDescription: "CT Caput"
      ImageType:
      SequenceName:
      SequenceVariant:
      ScanningSequence:
      MRAcquisitionType:
      SliceThickness: 
      FlipAngle:
      EchoNumbers:
      EchoTime:
      RepetitionTime:
      PhaseEncodingDirection:
    bids: &anat_dicoment_nonparametric  
      acq: <SeriesDescription>    
      ce:
      rec:
      run: <<1>>                  # This will be updated during bidscoiner runtime (as it depends on the already existing files)
      part: 
      suffix: clinical
    meta:                         

No mappings are found or displayed in the editor. 
How is it possible to troubleshoot this issue? 
And: the same happens when I use the default template. 

Thanks  in advance.

**Comment by marcelzwiers** [comment]
You can use `dicomsort` first to sort the dicoms in subdirectories:
```python
dicomsort preprocessed_baerum --subprefix sub- --sesprefix ses-
```
Making a custom template requires more skills / advanced knowledge about BIDScoin. It pays off when the automatic datatyping is not working properly and you want to use BIDScoin more often

**Comment by marcelzwiers** [comment]
But I think your use case is valid, I will make un update to accommodate for it
