### ISSUE TITLE
Getting 'TypeError: 'NoneType' object is not subscriptable' when testing BIDScoin

### ISSUE THREAD

**Issue by Catyre** [Donders-Institute/bidscoin#139]
Hello,
When attempting to install BIDScoin, then testing it with `bidscoin -t`, I run into this error:

<img width="820" alt="Screen Shot 2022-06-03 at 11 37 34 AM" src="https://user-images.githubusercontent.com/7707850/171900023-42c5e293-01b0-4619-94ec-80b9ef84895d.png">

I am not really sure how to proceed, as I have followed the installation instructions exactly (including installing dcm2niix, although I haven't set it to be run in the bidsmap yet), and there is no troubleshooting information available in the documentation that is pertinent to this problem.

Attempting to install the bids module manually with `pip install bids` was also fruitless.

It should be noted that I haven't yet set the options of the bidsmap to run the dcm2niix executable, but the phrasing of the docs suggests that I don't need this to run `bidscoin -t` (since it suggests using that command to help with the process of setting up dcm2niix)

As a side question, and sorry if this is a stupid question, but how do I open the BIDScoin GUI?

Any help would be greatly appreciated.  Thanks in advance!

**Comment by marcelzwiers** [comment]
I am puzzled 'pip install bidscoin' is not working, but I am away for the
weekend, will look at it Tuesday

_____________________
Sent from my phone

Op vr 3 jun. 2022 18:02 schreef Caleb Remocaldo ***@***.***>:

**Comment by Catyre** [comment]
I found the issue.  After printing out the `ImportError` explicitly in `bidscoin.py`, I learned that the original error was that I did not have the modules 'numpy.core._multiarray_umath' and 'pandas._libs.join'.  Simply updating my versions of both pandas and numpy fixed the issue.

**Comment by marcelzwiers** [comment]
Any idea on why this happened? I do have `numpy` and `pandas` in the `requirements.txt` file...
