### ISSUE TITLE
dcm2niix setup issue.

### ISSUE THREAD

**Issue by TamerGezici** [Donders-Institute/bidscoin#140]
I am trying to show the path for dcm2niix to bidscoin but it is not working. I had an error when it's set to `module add dcm2niix; dcm2niix
`
so I decided to use:  F:/MRIcroGL/Resources/dcm2niix.exe 

I edited the .yaml files and gave them the path like this, but bidscoin still tried using module add even though the bidsmap template was set to this path: 
![image](https://user-images.githubusercontent.com/11014942/171928623-00e0583d-0fe5-44e9-bf23-d729c3cd2d40.png)

*It could be that I don't know proper yaml syntax, but then why did it still try using the default way? It was doing it with module add.

So then I tried it through the options of bidsmapper, and I ran into this:

![image](https://user-images.githubusercontent.com/11014942/171930637-7afe833e-285d-4cda-82f1-46ed579e7b3c.png)

Why is it trying to run dcm2niix with an -u tag? There doesn't exist such tag when I try running the .exe on my own.

![image](https://user-images.githubusercontent.com/11014942/171929927-771a0512-1fb2-448b-ada2-14f4fa5658fe.png)

**Software version**
 - BIDScoin version (latest)
 - Win 10

**Comment by marcelzwiers** [comment]
I am away for the weekend, and will look at it Tuesday. But the module is
used in Linux. For windows you can just remove it it (see the bidscoin
plugin documentation)

_____________________
Sent from my phone

Op vr 3 jun. 2022 20:52 schreef Tamer Gezici ***@***.***>:

**Comment by TamerGezici** [comment]
> 

Sure. Thanks. By the way I just tried it on my desktop, C:\Users\tamer\Desktop\dcm2niix.exe

and it started generating a bunch of nifti files in my desktop, I moved the executable to C:\Users\tamer\Desktop\study3\dcm2niix\dcm2niix.exe and the error came back.

**Comment by marcelzwiers** [comment]
Only now I see that the `-u` option is only available in the linux version of dcm2niix... This is not a problem, it only causes an error when testing

**Comment by TamerGezici** [comment]
I see. Thanks for the clarification and quick fix.

**Comment by marcelzwiers** [comment]
I presume everything works correctly now, if not please reopen this issue
