### ISSUE TITLE
Error when using rawmapper: "AttributeError: 'str' object has no attribute 'name'"

### ISSUE THREAD

**Issue by Catyre** [Donders-Institute/bidscoin#141]
**Describe the bug**
When running `rawmapper`, an attribute error is raised complaining that the string `series` has no attribute `name`.

**To reproduce**
1. Follow the tutorial up to the use of the `rawmapper` utility
2. Run `rawmapper` with `rawmapper raw` (or any variation of the path, including absolute path)

**Expected behavior**
The program runs normally.

**Screenshots**
![Screen Shot 2022-06-14 at 1 44 29 PM](https://user-images.githubusercontent.com/7707850/173663197-3901c604-eb67-4e6f-b323-8c5d96a4ccad.png)

**Software version**
 - BIDScoin version: 3.7.2
 - OS (e.g. Windows, Linux, MacOS): MacOS Monterey

**Additional Comments**
It's possible I'm not using the command correctly, as this is my first time using it, but looking at `rawmapper -h` suggests that I'm using it in a correct way.

**Comment by marcelzwiers** [comment]
I see, it's a bug that shows up for data repositories without a DICOM Series organization (I think). Should be patched now (install from GitHub or wait for the next release), but please reopen if not
