### ISSUE TITLE
Bideditor haves trouble opening, using a non fixed prefix

### ISSUE THREAD

**Issue by ccomella** [Donders-Institute/bidscoin#145]
**Describe the bug**
Running the bidsmapper doesn't produce any error. However, it can't open bidseditor. 

**Expected behavior**
In my case, my source folders doesn't have a fixed prefix. The source folder is save as: 3digitsnumber_NAME_numbers, a name example is: 010_NAME_3580, which 010 changes and also 3580, just NAME is a fixed prefix. 
I runned bidsmapper using this code: 
bidsmapper -n "???_NAME" -m "NAME_2" sourcefolder bidsfolder

I tried using bidsmapper -n "??_NAME" -m "NAME_2" sourcefolder bidsfolder in a folder which are save as a 2 digit number and it worked 

**Screenshots**

![Screenshot from 2022-06-29 11-34-06](https://user-images.githubusercontent.com/108267084/176411836-61cab30c-4d7d-4307-ad75-f3bed59477e3.png)

**Software version**
- bidscoin 3.7.2
 - OS (Linux)

**Comment by marcelzwiers** [comment]
Hi, sorry for the crash, the bidseditor should indeed have come up with a warning or so. Just to get this straight, in your example, what is the subject id you want to use, is it `010` or `3580`, or both? I think you probably could use:

```console
bidsmapper -n "*NAME" -m "NAME_2" sourcefolder bidsfolder
```
And then in the bidseditor, for the subject label use: `<<filepath:/.*NAME(.*)/>>` to extract `3580` or `<<filepath:/(.*)NAME.*/>>` to extract `010`

**Comment by marcelzwiers** [comment]
p.s. FYI, using a `?` in your prefix resulted in  a crash because it was later interpreted in a regular expression. Using `*` doesn't have this issue

**Comment by marcelzwiers** [comment]
If the above doesn't work for you, then installing the latest source from github should solve your error (see the installation documentation). If not, you can reopen this issue
