### ISSUE TITLE
Make non-editable fields grey, editable fields white

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#15]
The user has to double click to find out which fields are editable, it would be better if that would become clear from the interface, e.g. by making the background or or the font in that field in non-editable fields grey, compared to black/white in editable fields

**Comment by rutgervandeelen** [comment]
See commit 1c60b360e966bd192b78c828a637c4d25072f548 in `refactor_bidseditor` branch

**Comment by marcelzwiers** [comment]
It looks good, but I don't think this is necessary for the main window, which is not editable anyhow. Perhaps for the main window it would be better to have the read/green coloring reflect the fields that will be editted. So like this:

![image](https://user-images.githubusercontent.com/15156015/58957181-645f6000-87a0-11e9-95e2-4511ddca03de.png)

**Comment by marcelzwiers** [comment]
I think the ideal interface would have red edit buttons that turn black after the user has used them once (i.e. clicked 'OK' in the edit window). All other cells would have black text, except for the modality cells that are always green when Modality in bids.bidsmodalities and otherwise red.

**Comment by marcelzwiers** [comment]
![image](https://user-images.githubusercontent.com/15156015/58973040-448b6480-87bf-11e9-8956-bc74b1af3730.png)

**Comment by rutgervandeelen** [comment]
See commit 027acf0841c2d9fd829118100fa28fed281d52bf
