### ISSUE TITLE
Converting fmap from MPM-dataset

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#150]
Hello,
we recently acquired some MPM-data and wanted to bring them into the BIDS. Basically, the dataset consists of "anat" and "fmap" data. We had no problem with the conversion of the anat part, but some issues with the fmap.
Each of the anat data is accompanied with an short fmap of the head and the body coil (RB1COR in BIDS terms). For details be referred to the screenshot. The bids-editor accepts all options (all names are green) and the bidscoiner actually returns no error (No BIDScoin errors or warnings were reported). However, these RB1COR-fmaps are stored in /derivatives/SiemensHealthineers/sub-1/ses-1/fmap/sub-1.... What is happening here? Why is the destination folder not the bids-root directory? 
Also, the intendedfor is not updated with the actual dataset (still: <<PDw>> for example).
Thank you so much for your help!

![fmap_bidseditor](https://user-images.githubusercontent.com/52704390/189609089-6bcd9034-629b-4726-8ed7-7f4cc51edd96.png)

**Comment by marcelzwiers** [comment]
Hi, I understand your confusion, but storing the `RB1COR` data as derivative data would not have been my choice either, I just followed this BIDS specification:
https://bids-specification.readthedocs.io/en/stable/99-appendices/11-qmri.html#quantitative-maps-are-derivatives

What I understood from that specification is that RB1COR is a quantitative fmap, and should be stored as a derivative (i.e. in the way you have it now). 

Furthermore, the `IntendedFor` field is always relative to the participant subfolder, and hence cannot point to anything in the derivatives folder:
https://bids-specification.readthedocs.io/en/stable/99-appendices/14-glossary.html#intendedfor-metadata

So, what I would do is use the new `B0FieldIdentifier` and B0FieldSource` metadata fields, as fas as I know these are not limited in that way.

**Comment by karl-koschutnig** [comment]
Hi, and thanks for the quick response!!
You are totally right - I completely missed the "derivatives" part for the qmri in the BIDS - specifications. 
I was relying on the only [MPM-dataset](https://osf.io/k4bs5/) I could find :  
Here the *RB1COR* files are in the subjects folder under map! 

I guess you did everything right! Still, I am confused with the specifications in that particular case. 
Thanks! Karl

**Comment by marcelzwiers** [comment]
BIDScoin complies with BIDS version 1.7.0, but that MPM dataset says: {"BIDSVersion": "1.5.0"}. Perhaps that's why it is still in the root fmap folder?

**Comment by karl-koschutnig** [comment]
... this makes sense! Thank you so much for your help!!
