### ISSUE TITLE
singularity version fails on ImportError

### ISSUE THREAD

**Issue by dmd** [Donders-Institute/bidscoin#151]
What I did:

```
$ wget https://raw.githubusercontent.com/Donders-Institute/bidscoin/master/singularity.def
```

then

```
$ singularity build bidscoin.sif singularity.def
```

then

```
$ singularity exec -B $PWD/sourcedata/:/in:ro -B $PWD/bids/:/out /data/singularity-images/bidscoin.sif bidsmapper /in /out
Traceback (most recent call last):
  File "/usr/local/bin/bidsmapper", line 5, in <module>
    from bidscoin.bidsmapper import main
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidsmapper.py", line 24, in <module>
    from PyQt5 import QtCore, QtGui
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

What I expected: Something other than it immediately failing to run.

**Comment by marcelzwiers** [comment]
Mhhh, I didn't make the singularity definition myself, but have you had a look at this issue?
https://github.com/Donders-Institute/bidscoin/issues/143

**Comment by marcelzwiers** [comment]
And this:
https://bidscoin.readthedocs.io/en/stable/installation.html#troubleshooting

**Comment by dmd** [comment]
Aha. Ok, yes, the Singularity container is flawed - it is missing several packages it needs to run.

However, I seem to be running in the non-Singularity version now that I've installed (as per #143) xcb-util-wm and xcb-util-renderutil.

**Comment by marcelzwiers** [comment]
I am happy to take suggestions for improvement :-)

**Comment by dmd** [comment]
AH, the troubleshooting section was actually all I needed. Adding that `strip` worked.  Would having that there harm people not on Centos 7.5?

**Comment by marcelzwiers** [comment]
I don't know, but I rather not mess with such core settings and potentially cause issues for other people. Unless someone can assure me it's ok or has a better solution I am leaving this issue up to the troubleshooting section
