### ISSUE TITLE
Register a Research Resource Identifier (RRID) for BIDScoin 

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/bidscoin#155]
See https://scicrunch.org/resources/data/source/nlx_144509-1/search. This is similar as ORCID providing identifiers for people. 

As an example: FieldTrip has [rrid:scr_004849](https://scicrunch.org/resources/data/record/nlx_144509-1/SCR_004849/resolver?q=fieldtrip&l=fieldtrip&i=rrid:scr_004849).

**Comment by marcelzwiers** [comment]
Thanks for the suggestion

> Successfully Submitted
Your Resource has successfully been submitted and has the Resource ID: SCR_022839
