### ISSUE TITLE
fieldmap - EffectiveEchoTime

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#165]
Hi experts, 

I am struggling a little bit with bringing a gre-fieldmap into the BIDS. It is a (Siemens) Fieldmap with 2 magnitudes and 1 phase diff. Problem is that the bids mapper does not (or can not) differentiate between those three (magnitude1, magnitude2 and phase diff). As a consequence I can not define them correctly. 
I guess an additional Attribute with "EffectiveEchoTime" could do the trick?!  

We are using XA31 and the EchoTime Attribute is not supported (empty - see attached screenshot).

I would really appreciate your help!

Thanks 
Karl

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/52704390/211846516-e031da78-d062-4250-b23f-19ef51d77d96.png">

**Comment by marcelzwiers** [comment]
Ah, I see, we haven't moved over to XA yet, so I am not aware of such issues. I find it also to be weird that the EchoTime is empty (as it is a [required attribute](https://dicom.innolitics.com/ciods/mr-image/mr-image/00180081)). But sure, replacing (or adding) EffectiveEchoTime to the template bidsmap should solve this

**Comment by marcelzwiers** [comment]
(assuming that this value is in the header. Would be nice if there is also info on the echo-number)

**Comment by marcelzwiers** [comment]
I wouldn't mind adding EffectiveEchoTime to all template run-items, I think I'll do that

**Comment by marcelzwiers** [comment]
p.s. I noticed in your screenshot that the `filesize` and `nrfiles` properties are empty (i.e. not working). What operating system and python version are you using?

**Comment by karl-koschutnig** [comment]
Just for the record:

Operating System: DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
Python: python3.10

**Comment by marcelzwiers** [comment]
I suppose it works for you now? Feel free to reopen this issue if not :-)
