### ISSUE TITLE
Unexpected `<<filepath:...>>` change within bidsmap.yaml

### ISSUE THREAD

**Issue by mabiede** [Donders-Institute/bidscoin#166]
**Description**

Adding part of the source data folder to the `['datatype']['subject']` or `['datatype']['session']` raises a lot of `Could not update the bidsmap session label expression:` warnings.

- initial subject path (from template): `<<filepath:/M_S(\d{3})_\d{2}/>>`
- initial session path (from template): `<<filepath:/M_S\d{3}_(\d{2})/>>`

- source folders e.g.: `/data/2023/01/20/M_S001_01` (dates, subject id, and session id are increasing)

Running the bidsmapper changes the subject and session <<filepath>> to the following:

- `rawfolder = "/data/2023/01/20"`
    - <<filepath:.*/20.*/M_S(\d{3})_\d{2}/>>
    - <<filepath:.*/20.*/M_S\d{3}_(\d{2})/>>
- `rawfolder = "/data/2023/01/21"`
    - <<filepath:.*/21.*/20.*/M_S(\d{3})_\d{2}/>>
    - <<filepath:.*/21.*/20.*/M_S\d{3}_(\d{2})/>>
- aso.
    - the current parent folder of the "subject-session" gets prefixt to the rest

results in

```log
ERROR | Could not parse sub/ses-id information from /data/2023/01/24/M_S015_01/some_file.par
    using: <<filepath:.*/23.*/22.*/21.*/20.*/M_S(\d{3})_\d{2}/>>'
```

- Is this related to one of the latest changes since bidscoin 3.7.2?
- Why does the `['datatype']['subject']` has to be updated at all? The `provenance` attribute already holds the absolute data path of the file.
- Once the error above is shown a subject identifier `filepath23222120MSd5d2` is created for all following sessions on that date.

This might be an issue, that if bidsmapper is rerun, the `code/bidscoin/bidsmap.yaml` is preferred over the used `bidsmap.yaml` template.

**Expected behavior**

If a regex is provided for the subject and session id within the `bidsmap.yaml` template, this should be added to the output `core/bidscoin/bidsmap.yaml` without changing it.

Basic information about the data like `['Options']` or `['datatype']['subject']` should always be read from the template. Once the bidsmapper runs, e.g. the `['datatype']['func']` of the `core/bidscoin/bidsmap.yaml` gets extended ("upsert") by the newer files.

**Software version**
 - BIDScoin version 3.7.4
 - Docker infrastructure, base image Ubuntu 20.04.3 LTS
 - Python 3.8.10 (external dependency)

**Comment by marcelzwiers** [comment]
BIDScoin expects a subject/session folder organization, but you have put a date folder before the subject folder. I have never seen such a use case (also acquisition date is information you are often not allowed to share) and I suspect that BIDScoin can't handle that out of the box. You are mentioning BIDScoin 3.7.2, does that mean it works for you with versions before that?

If the subject/session regular expression in the template bidsmap contains subject session prefixes (which is very common), and the user runs the bidsmapper with different prefixes (which is a valid use case), then the bidsmapper makes an attempt to update the prefixes in the regular expressions accordingly. That's a tricky operation (I am happy to try to improve that code), but if that goes wrong, you should just be able to enter/restore the right value in the bidseditor? Doesn't that work? I understood you created your own template, right? Perhaps you can try if it helps if, in there, you also update the prefixes and do not pass them to the bidsmapper?

p.s. As for your question about updating, I am not sure what you mean. What you see in the bidsmap / bidseditor is a shortlist of all the source datatypes in your repository, not a longlist of all your subjects. So the provenance path does not hold the info for all your subject and session labels, in fact, these need to be parsed for every subject/session, and that is what the regular expression is supposed to do.

**Comment by marcelzwiers** [comment]
I am planning a new release and will try to solve your case before that if I can

**Comment by mabiede** [comment]
Thanks for your fast reply. It would be great if bidscoin could handle this in a new release.

As far as I remember, yes, with 3.7.2 worked. I had to pause the development of the pipeline for quite a while.

I tried to find the statement in your codebase, which is handling those directory prefixes. I guess it's in [bidsmapper.setprefix](https://github.com/Donders-Institute/bidscoin/blob/d0c9d79fe49008a9e17791193eec4fe55f0d7523/bidscoin/bidsmapper.py#L180) function.

Our goal is to get an automated pipeline, from our raw data (which in our case has the dates in the path) to BIDS. Unfortunately, using the bidsmapper UI isn't an option, and manually updating the yaml file after each run would just be a workaround.

About updating `['datatype']['subject']`. Is the `['datatype']['subject']` field (from the generated `core/bidscoin/bidsmap.yaml`) used again by the bidscoiner or other tools?

Updating this value for the current bidsmapper run seems to be fine, but I'd suggest using the default regex for additional runs.

I'll try to use `/data` as `rawfolder` and include the date into the regex in the meantime.

**Comment by marcelzwiers** [comment]
In my last commit, I added a little check that may help you a bit (and it is in `setprefix()` indeed). I think it helps you because I suspect you don't pass a sub-/ses-prefix to bidsmapper?

The `['datatype']['subject']` field is used also by `bidscoiner` (to determine the subject/session label).

**Comment by marcelzwiers** [comment]
If you are not going to use the bidseditor, you could perhaps skip the bidsmapper altogether and pass your template bidsmap straight to the bidscoiner

**Comment by marcelzwiers** [comment]
I think if you add a catch-all run-item, it would work. Something like this (for DICOM):
```
  extra_data: # ----------------------- All extra data -------------------------
  - provenance:
    attributes:
      ProtocolName: .*
```

**Comment by marcelzwiers** [comment]
Otherwise, run-items may be skipped and an error message is generated. But perhaps that's what you want, then forget about the catch-all run-item

**Comment by mabiede** [comment]
> If you are not going to use the bidseditor, you could perhaps skip the bidsmapper altogether and pass your template bidsmap straight to the bidscoiner

Thanks, this works with adding the full path to the bidsmap file.

**Comment by marcelzwiers** [comment]
Great to hear, I guess that closes this issue? Feel free to reopen when you have more hiccups

**Comment by mabiede** [comment]
@marcelzwiers Changes from a Bug report into a Feature request ;-)

**Comment by marcelzwiers** [comment]
@mabiede The latest code now has a bidsmapper option to skip updating the subject/session label expressions, does that work for you? And if not, did passing the bidsmap directly to bidscoiner work for you?

**Comment by marcelzwiers** [comment]
Good to hear. p.s. I see you are a Docker user, so you may be interested to know that I added a (minimized) Dockerfile to BIDScoin:
https://bidscoin.readthedocs.io/en/latest/installation.html#using-a-docker-container
