### ISSUE TITLE
PAR / REC to BIDS

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#173]
### Discussed in https://github.com/Donders-Institute/bidscoin/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **Freeklinders** January 31, 2023</sup>
Dear Marcel,

I managed to bidscoin all the files in my dataset, though I keep receiving the following errors for all my files when trying to validate the new bids folder;
ERROR CODE 1: (NOT INCLUDED):
Files with such naming scheme are not part of BIDS specification.
ERROR CODE 2: ACQ_NAME_CONTAIN_ILLEGAL_CHARACTER
acq Name contain an Illegal Character hyphen or underscore. Please edit the filename as per BIDS spe
structure.

My (bids) folder structure is as follows (example field map):
BIDS_con_new/sub-1001/fmap/sub-1001_acq-WIPB0epiSENSE_magnitude_fieldmaphz.json

In the bids mapper all my files were green and I received the same error when I left out the whole acquisition field in the bids mapper (thereby getting rid of the capitals).

Do you have any idea what I am doing wrong?

Thanks a lot in advance!

Best,
Freek</div>

**Comment by marcelzwiers** [comment]
I think I have an idea what is causing this, namely that dcm2niix produced a nifti-file without an accompanying json sidecar file? Can you confirm this @Freeklinders?

**Comment by Freeklinders** [comment]
Hi Marcel, 

All images have an accompanying .json file!

**Comment by marcelzwiers** [comment]
Mhhh, strange. And did you get any BIDScoin warnings or errors? (you can still see them in the logfile in `yourbidsfolder/code/bidscoin`)

**Comment by Freeklinders** [comment]
2023-02-14 11:15:43 - bidscoin - ERROR Failed to run:
module add dcm2niix;dcm2niix -b y -z y -i n -f "sub-1077_acq-sT1W3DTFE32channel_T1w" -o "/data/fjlinders/Data_TMS_BIDS/BIDS_con_new/sub-1077/anat" "/data/fjlinders/Data_TMS_BIDS/RAW/sub-1077/1077_1_sT1W_3D_TFE_32_channel_2_1.PAR"
Errorcode 0:
/bin/sh: module: command not found

This one I get for every participant!

**Comment by marcelzwiers** [comment]
That error is innocent (and will no longer appear in the latest version of the code). I'm puzzled, perhaps you can upgrade to the latest version and run the bidsmapper/bidscoiner like this:
```console
pip install --force-reinstall --no-deps git+https://github.com/Donders-Institute/bidscoin
SET BIDSCOIN_DEBUG=TRUE
```
And then run your bidsmapper / bidscoiner. Would be a big help if you can send me the resulting `bidscoiner.log` file

**Comment by marcelzwiers** [comment]
I would like to solve your issue, but I need more information to do so. By any chance, can you share a sample of your fieldmap data with me?

**Comment by marcelzwiers** [comment]
I am closing this due to a lack of information, feel free to re-open it.
