### ISSUE TITLE
Fail to run dcm2niix due to its version

### ISSUE THREAD

**Issue by colIapse** [Donders-Institute/bidscoin#177]
Hi Marcel,
Thank you for your contribution for making dcm2bids a easier thing!
After reading your introduction of this app,I was really amazed for its convenience and user-friendly GUI.
But unfortunately，it seems that I met with some problem during installation.
I am just wondering whether you can do me a favor to help solve the installation problem ：）
Thanks a lot！

Here is the bug,while I have installed the newest version of dcm2niix,which is released at 20/7/2020,during my test of bidscoin,it still will report a bug which says ERROR CODE3:
![image](https://user-images.githubusercontent.com/126434134/221462774-cd1cb0db-1b65-43a9-90db-25d8e327d19c.png)

I am not sure what cause this bug,whether due to the version of dcm2niix or any other things.When I use dcm2niix independently,it can work .
 
And my bidscoin version is 3.7.4.

At  last,please forgive my poor expression,I am just a beginer in this field,And please allow me to extend my heartfelt respects again.

Kind regards!

**Comment by marcelzwiers** [comment]
Fortunately, that error is totally innocent (the `-v` option produces an errorcode, but it's not error) and I actually already patched it in the upcoming new release. Thanks for reporting!

**Comment by colIapse** [comment]
Thanks for answering！Please allow me to have another further question，if this errorcode doesn't make any sense,then it means that I can use bidscoin indeedly.If so,when I use the GUI to test,actually I can ignore the errorcode too,am I right?And the function of this app will not be influenced by the error.
Here are the screenshots.Thanks!
![image](https://user-images.githubusercontent.com/126434134/221506166-f605543f-bace-442b-8ec1-1e15c54653c0.png)


Kind regards!

**Comment by marcelzwiers** [comment]
true, it's the same test. Normally, an errorcode = 0 means that there were no errors, and different errors get different numbers. Dcm2niix however, decided to return an errocode=3 when it is asked for the version (see https://github.com/rordenlab/dcm2niix/blob/master/ERRORS.md). This is against the convention and is causing confusion (and I therefore filter it out it the upcoming version of BIDScoin)

**Comment by colIapse** [comment]
Thank you for your answer! I really appreciate that you are sooooo patient. It really helps me a lot.
Kind Regards
