### ISSUE TITLE
Date shift(s) when dataset bidsification happens in multiple code calls.

### ISSUE THREAD

**Issue by smoia** [Donders-Institute/bidscoin#178]
** General summary **
Related to #109 and [this line of code](https://github.com/Donders-Institute/bidscoin/blob/6c33ac3ce00bcfb781b8384aecc1110f14246485/bidscoin/plugins/dcm2niix2bids.py#L396).
Tagging @CesarCaballeroGaudes that raised this issue!

Acquisition date and time shift is really important to ensure anonymity. The current code forces all dates to be the same (Jan 1st 1925). This messes a little bit up with longitudinal/multi-session data acquisition, where month and day of week are important factors.
Is there something we can do to improve this little bit?

** Additional detail **
This issue is particularly important for clinical and/or longitudinal datasets.
In the first case, given the possible sparsity of data coming in, users might do dataset conversions a bit at a time, but might want to maintain internal consistency in terms of dates.
In the second case, knowing how much time passed between scans could be really important for a plethora of reasons (circadian rhythms, time between runs, ...), hence internal consistency is still something to look for. 

** Next steps **
It would be fantastic to have the option to either turn off the feature, or even better to provide a date shift to apply to the date, so that the scans are internally consistent.
This would act on the line of code linked above, but especially on either the CLI of the bidscoiner or on the YAML file (probably the first venue is better).

**Comment by marcelzwiers** [comment]
By default BIDScoin follow the BIDS recommendation to anonymize dates:

>Note that, depending on local ethics board policy, date time information may not need to be fully detailed. For example, it is permissible to set the time to 00:00:00 if reporting the exact recording time is undesirable. However, for privacy protection reasons, it is RECOMMENDED to shift dates, as described below, without completely removing time information, as time information can be useful for research purposes.

>Dates can be shifted by a random number of days for privacy protection reasons. To distinguish real dates from shifted dates, is is RECOMMENDED to set shifted dates to the year 1925 or earlier. Note that some data formats do not support arbitrary recording dates. For example, the [EDF](https://www.edfplus.info/) data format can only contain recording dates after 1985. For longitudinal studies dates MUST be shifted by the same number of days within each subject to maintain the interval information. For example: 1867-06-15T13:45:30

If you don't want this, you can set the `anon` flag to `'n'` in the [Options](https://bidscoin.readthedocs.io/en/latest/options.html#dcm2niix2bids-plugin)

**Comment by CesarCaballeroGaudes** [comment]
thank you @marcelzwiers, we will proceed as you suggested.

**Comment by marcelzwiers** [comment]
I think managing between-session date shifts from within bidscoiner is a bit beyond the scope of bidscoiner. It is better to develop a separate (date) anonymization tool to run on a bids repository as a post-processing step
