### ISSUE TITLE
documentation: program name

### ISSUE THREAD

**Issue by michaelf500** [Donders-Institute/bidscoin#179]
The documentation on 
https://bidscoin.readthedocs.io/en/stable/installation.html#testing-bidscoin

has examples of how to run 'bidscoin' eg
`$ bidscoin -t                        # Test with the default template bidsmap`

However, there does not seem (in BIDScoin-version: 3.0.8) to be a bidscoin executable, just bidscoiner.

Maybe the documentation should be changed?

**Comment by marcelzwiers** [comment]
Hi Michael,

The link you are using is for v4.0.0, for the documentation of v3.0.8 you should go to (the link is there on the bottom of the docs menu):

https://bidscoin.readthedocs.io/en/3.0.8/

Best,
Marcel

**Comment by michaelf500** [comment]
Hi Marcel

Thanks, I get it. However, 3.08 is what I get with running pip install
bidscoin, so I assumed that was the latest version.

Best wishes

Michael

**Comment by marcelzwiers** [comment]
That very strange because the latest version on pypi is 4.0.0:
https://pypi.org/project/bidscoin/

Can you try `pip install --upgrade bidscoin`? Or, if that doesn't help `pip install --force-reinstall bidscoin`?

**Comment by michaelf500** [comment]
Hi Marcel

I still get 3.08

However, I realise that  I am using an old version of python (Python 3.6.9)
on Ubuntu 18.04
which might be contributing to the problem.

I did try installing bidscoin 4.0.0 by downloading from the github, and I
get an error message relating to not finding a recent version of setuptools.

Best wishes

Michael

**Comment by marcelzwiers** [comment]
That makes sense, I think that solves it (let me know if things don't work out for you with python >= 3.8)
