### ISSUE TITLE
Fail to convert DWI DICOM files with Errorcode 139: Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by ella09may** [Donders-Institute/bidscoin#184]
Hi there,

BIDScoin is such a great package for DICOM-to-BIDS converting and thank you so much for developing and maintaining this elegant tool. 

I got an error when using **BIDScoin** to convert multimodal DICOM files (T1w, rest-fMRI, and dwi) to BIDS formats. The output folder for DWI is empty while the other two have been completed without any error. 

The details of the error can be found below:
```bash
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023-05-26 16:34:57 - ERROR | Failed to run:
dcm2niix -b y -z y -i n -l n -f "sub-410001_ses-01_run-1_dwi" -o "/media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi" "/media/zqn/Imaging/test1/sourcedata/sub-410001/ses-01/007_oblDTInew"
Errorcode 139:

Segmentation fault (core dumped)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

When I used the **dcm2niix** to convert the DWI DICOM file to Nifti, I successfully got the `.bval`, `.bvec`, `.json`, and `.nii.gz` files as outputs although some warning as below:
```bash
/home/zqn/Applications/MRIcroGL_linux/MRIcroGL/Resources/dcm2niix -f "%f_%p_%t_%s" -p y -z y -o "/media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi" "/media/zqn/Imaging/test1/sourcedata/sub-410001/ses-01/007_oblDTInew"
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.4.0 x86-64 (64-bit Linux)
Found 800 DICOM file(s)
Warning: Unable to compute slice times for GE Diffusion
Convert 800 DICOM as /media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi/007_oblDTInew_SCH-new_20180707102422_7 (256x256x50x16)
Conversion required 1.640890 seconds (1.640549 for core code).
```

Information about my OS: `Ubuntu` 22.04;
Python environment for running `bidscoin`: `python` v3.8.16, `bidscoin` v4.0.0, `dcm2niix` v1.0.20230411; 
`dcm2niix` version when using `MRIcroGL`: v1.0.20220720.

Is it possible to solve this error? Is this error related to my data or something else? 
Any help will be appreciated.

Qiannan Zhao

**Comment by marcelzwiers** [comment]
Hi Qiannan, thank you for your kind words, I'm happy that you find BIDScoin useful. It seems to me that the dcm2niix version that you are using in BIDScoin crashes on your data. The first thing to try is go back to the same (older) dcm2niix version, e.g. by changing your `dcm2niix` command to `/home/zqn/Applications/MRIcroGL_linux/MRIcroGL/Resources/dcm2niix` in the bidseditor

![image](https://github.com/Donders-Institute/bidscoin/assets/15156015/97ee88aa-43d8-49dd-8193-7d82fae540a7)

**Comment by ella09may** [comment]
The converting for DWI files is done without any errors after I change the dcm2niix command.

@marcelzwiers Thank you so much! You made my day.
