### ISSUE TITLE
Does the combination of `nibabel2bids` with `spec2niibids` change a Nifti file or just rename it?

### ISSUE THREAD

**Issue by ella09may** [Donders-Institute/bidscoin#185]
Hi there,

I have some rest-fMRI data in Nifti format, and the original DICOM files are no longer available, so there are no corresponding `.json` files for these data. 

But I knew these fMRI scanning used the same protocol as some other DICOM files. So the parameters, such as TR, TE, and slice thickness, are the same. The `.json` files of those DICOM files could be easily acquired using `BIDScoin`.

Now I have come out with two possible solutions:
**1. Use `BIDScoin` to convert the Nifti files**
Can I copy the `.json` file that used the same protocol to the Nifti source data folder and use the combination of `nibabel2bids` with `spec2niibids` to convert the mix of Nifti (in rs-fMRI modality) and DICOM (in T1w and DWI modalities) files to BIDS format together? This has been successfully done after testing, but I am afraid such procedures would change the Nifti files. **Does the combination of `nibabel2bids` with `spec2niibids` change a Nifti file or just rename it?** If it just renames the Nifti files, this solution can save me a lot of time, and I could use these BIDS data for further processing.

**2. Copy the Nifti files to the BIDS output folders after other modalities have been successfully converted**
I can use `BIDScoin` to convert the modalities with DICOM files, and after that, manually add and rename the Nifti files to the `func` subfolder in the output. This way is kind of time-consuming.

Information about my OS: Ubuntu 22.04;
Python environment for running `bidscoin`: `python` v3.8.16, `bidscoin` v4.0.0, `dcm2niix` version: v1.0.20220720.

Which way is more reasonable? Or are there any better solutions for this issue? Any help will be appreciated.
Qiannan Zhao

**Comment by marcelzwiers** [comment]
Hi Qiannan,

Your solution 1 sounds like a good plan and should not change the nifti files, just the name and (if you like) the gz zip-extenstion.

**Comment by marcelzwiers** [comment]
Alternatively, instead of copying the json files for every subject, you can copy the content of the json to the meta dictionary in the bidseditor. I think that is the easiest / most transparent solution of all

**Comment by ella09may** [comment]
@marcelzwiers Thank you so much! That sound cool to not copy the `.json` file for every subject. I'll have a try.

**Comment by ella09may** [comment]
It works!

**Comment by marcelzwiers** [comment]
Good to hear :-)
