### ISSUE TITLE
Can I use dynamic value to fill in a suffix

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#188]
I tried to use a dynamic value to fill in a `suffix` value, for example, use `<SeriesDescription:anat-(.*?)_ses>` to retrieve `T1w` from `anat-T1w_ses-B_acq-T1wHCPLI` SeriesDescription. BIDScoin creates a drop-down for a suffix with one value being `<SeriesDescription:anat-(.*?)_ses>`.

I don't know if it's an expected behavior. This feature works as expected for other fields like `acq`.

**Comment by marcelzwiers** [comment]
Interesting use case that I haven't considered so far. I've just made a small patch, can you test it?

**Comment by marcelzwiers** [comment]
It's actually the bidseditor that crashes. I just fixed it (hopefully, because the bidseditor is not covered by my pytests :-))

**Comment by mateuszpawlik** [comment]
It seems to work but the warning is still there:
```
WARNING | Invalid run-item with suffix: "<SeriesDescription:anat-(.*?)_ses>" (anat -> sub--unknown/ses--unknown/DICOM_anat_id001)
```

**Comment by marcelzwiers** [comment]
Yes, I was expecting that a bit. When the template bidsmap is loaded, it is checked for BIDS validity. However, the run-items in the template don't have associated data sources, which are needed to update the values dynamically. I'll see if I can handle it a bit more gracefully

**Comment by marcelzwiers** [comment]
Should be better now

**Comment by mateuszpawlik** [comment]
I'm not sure what exactly to check because the warning is the same.

**Comment by mateuszpawlik** [comment]
I built it again, just to be sure, and the warning is still there :thinking:

**Comment by mateuszpawlik** [comment]
With cbf56d0 the warning is gone.

**Comment by marcelzwiers** [comment]
That is intended (but indeed a bit verbose) behaviour, it means that the dynamic suffix could not be checked against the BIDS schema
