### ISSUE TITLE
Please clarify GPLv3 licensing

### ISSUE THREAD

**Issue by musicinmybrain** [Donders-Institute/bidscoin#190]
**Describe the bug**

While the trove classifiers in `pyproject.toml` and the `LICENSE.txt` file in `bidscoin` indicate the project can be used under the GPLv3, there is no license notice as recommended in https://www.gnu.org/licenses/gpl-howto.html.

A consequence of this is that it is not entirely clear whether the precise intended license is, in SPDX terms, [`GPL-3.0-only`](https://spdx.org/licenses/GPL-3.0-only) or [`GPL-3.0-or-later`](https://spdx.org/licenses/GPL-3.0-or-later). (A conservative assumption would be the former.)

**To reproduce**
1. Search the repository for a license notice.

**Expected behavior**
The exact license terms are clear. Ideally, a license notice of the form recommended by GNU is present.

**Software version**
 - BIDScoin version: 4.0.0
 - OS (e.g. Windows, Linux, MacOS): N/A

**Additional context**

**Comment by marcelzwiers** [comment]
I [added](https://github.com/Donders-Institute/bidscoin/commit/0f74da65d8f512c89659ec6537dd35f8348fec38) a new license description in the README and an SPDX identifier in the main `__ini__` file (I think adding it to every file is cumbersome and not really needed). Do you think this is enough or is there more I could do?

**Comment by musicinmybrain** [comment]
> I [added](https://github.com/Donders-Institute/bidscoin/commit/0f74da65d8f512c89659ec6537dd35f8348fec38) a new license description in the README and an SPDX identifier in the main `__ini__` file (I think adding it to every file is cumbersome and not really needed). Do you think this is enough or is there more I could do?

Thanks! Speaking only as a Fedora Linux packager, this is helpful and should be sufficient to establish the correct license and pass package review for the distribution. (There are some dependencies we need to package up first.)

Whether or not it would be legally or practically helpful to you or to some users to have a copyright and license notice of the form recommended by GNU somewhere in the source is somewhat beyond me.

**Comment by marcelzwiers** [comment]
Ok, I'll consider it good enough, thank you for your feedback!
