### ISSUE TITLE
bidscoin automatically adds `*.nii*` to IntendedFor file name pattern

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#191]
I used `<<dwi/*_dwi.nii>>` pattern to specify the IntendedFor images for a dwi fieldmap. This pattern didn't find any files. I think it is because bidscoin [automatically appends `*.nii*` to my pattern](https://github.com/Donders-Institute/bidscoin/blob/20ba693c1ba99c1a3df805a71ffbcd2722ab324e/bidscoin/bidscoiner.py#L293C122-L293C122).

This behavior in [not documented](https://bidscoin.readthedocs.io/en/stable/bidsmap.html#fieldmaps-intendedfor).

**Comment by marcelzwiers** [comment]
You're right, it now works with and without a file suffix (well, I didn't test it but I'm sure it works ;-))

**Comment by mateuszpawlik** [comment]
Oh, thank you :-) I just fixed the pattern on my side.
