### ISSUE TITLE
No module named 'pytest' while executing bidsmapper

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#193]
**Describe the bug**
When executing bidsmapper I get `No module named 'pytest'` error. I see `pytest` in the optional dependencies.

**To reproduce**
1. Execute bidsmapper
2. See error in the `bidsmapper.log`:
   ```
   ERROR | Could not import /root/.local/pipx/venvs/bidscoin/lib/python3.11/site-packages/bidscoin/plugins/dcm2niix2bids.py: No module named 'pytest'
   ```

**Expected behavior**
I guess `pytest` should be installed as a dependency and the error shouldn't then happen.

**Software version**
 - BIDScoin version: development `2899e04`
 - installed with `pipx install git+https://github.com/Donders-Institute/bidscoin.git@2899e04`
 - OS: Debian 12 in Docker on Debian 11

**Comment by mateuszpawlik** [comment]
Maybe pipx causes troubles.

**Comment by marcelzwiers** [comment]
Thanks for reporting this, I will look into it when I am back from my
holidays (the 10th of August)...

_____________________
Sent from my phone

Op do 27 jul. 2023 19:17 schreef Mateusz Pawlik ***@***.***>:

**Comment by mateuszpawlik** [comment]
I used [pipx](https://pypa.github.io/pipx/) to install BIDScoin in a Docker container. This is a recommended way to install Python applications by, for example, Debian 12. pipx creates a virtual environment in which it installs the application and all its Python dependencies. My guess is, pipx didn't know about the pytest dependency.

pipx kindly allows to install manually ([`pipx inject` command](https://pypa.github.io/pipx/docs/#pipx-inject)) a missing module. Executing `pipx inject bidscoin pytest` solved the problem for me.

**Comment by marcelzwiers** [comment]
Mhhh, pytest is no longer used in bidscoin, but only when running bidscoin tests:

https://github.com/search?q=repo%3ADonders-Institute%2Fbidscoin%20%22import%20pytest%22&type=code

But this line in the dcm2niix2bids plugin has a pytest dependency, for which I now added a work-around (#e55898274fd2f5d68a15afc425d95784e7278cd2). Does this solve your error?

**Comment by mateuszpawlik** [comment]
It seems to be fine now. I installed BIDScoin with `pipx install git+https://github.com/Donders-Institute/bidscoin.git@e558982` and executed it. There were no complaints on pytest missing.

**Comment by mateuszpawlik** [comment]
Btw. pipx allows for a very quick installation and testing :-)
