### ISSUE TITLE
Difficulty re-running bidscoiner with new participants (maybe file location related?)

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#194]
**Describe the bug**

Re-running Bidscoiner from a new filesystem/directory structure.
Bidsmap.yaml stays the same, but new participants added to my raw data directory.
When I finish running the bidscoiner, there is a "sub-" subject folder, but no subject folders.
e.g.:

INFO | --> Coining: /30days/uqtshaw/BeLong_processing/raw_all_dicomsorted_zips/sub-011/ses-01/020-T2star_2d_bipolar-inphase_GRE_16ME_aspire_p7.p7.2
INFO | Running: dcm2niix -b y -z y -i n -l n -f "sub-_acq-2dbipolarinphaseGRE16MEaspirep7p72_run-1_mod-T2star2dbipolarinphaseGRE16MEaspirep7p72_echo-16_GR" -o "/30days/uqtshaw/BeLong_processing/BeLong_brain_BIDS_20230529/sub-/extra_data" "/30days/uqtshaw/BeLong_processing/raw_all_dicomsorted_zips/sub-011/ses-01/020-T2star_2d_bipolar-inphase_GRE_16ME_aspire_p7.p7.2"
INFO | Output:
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.3.0 x86-64 (64-bit Linux)
Found 15 DICOM file(s)
Warning: Assuming mosaics saved in reverse order due to 'sSliceArray.ucImageNumb'
Convert 15 DICOM as /30days/uqtshaw/BeLong_processing/BeLong_brain_BIDS_20230529/sub-/extra_data/sub-_acq-2dbipolarinphaseGRE16MEaspirep7p72_run-1_mod-T2star2dbipolarinphaseGRE16MEaspirep7p72_echo-16_GR_e16 (336x336x15x1)
Conversion required 0.555997 seconds (0.293178 for core code).

INFO | ------------------- Subject 2/28 -------------------
ERROR | Could not parse required sub-<label> information from /30days/uqtshaw/BeLong_processing/raw_all_dicomsorted_zips/sub-013/ses-01/001-Localizer/SUB-013.MR.RESEARCH_TOM.0001.0001.2021.12.01.09.54.12.76178.258127961.IMA using: <<filepath:/raw_all_dicomsorted/sub-(.*?)/>> -> 'sub-'
INFO | >>> Skipping processed session: /30days/uqtshaw/BeLong_processing/BeLong_brain_BIDS_20230529/sub- already has ['anat', 'dwi', 'extra_data'] data (you can carefully use the -f option to overrule)
INFO | ------------------- Subject 3/28 -------------------
ERROR | Could not parse required sub-<label> information from /30days/uqtshaw/BeLong_processing/raw_all_dicomsorted_zips/sub-014/ses-01/001-Localizer/SUB-014.MR.RESEARCH_21034_BELONG.0001.0001.2022.02.18.11.23.29.958454.276314191.IMA using: <<filepath:/raw_all_dicomsorted/sub-(.*?)/>> -> 'sub-'
INFO | >>> Skipping processed session: /30days/uqtshaw/BeLong_processing/BeLong_brain_BIDS_20230529/sub- already has ['anat', 'dwi', 'extra_data'] data (you can carefully use the -f option to overrule)

**Expected behavior**
New participants to be converted to nifti, old ones tro remain the same

I ran bidscoiner ./raw ./bids

**Screenshots**

**Software version**
 - BIDScoin version 4.0
 - OS (Linux)

**Comment by marcelzwiers** [comment]
Thanks for reporting this, I will look into it when I am back from my
holidays (the 10th of August)...

_____________________
Sent from my phone

Op vr 28 jul. 2023 04:30 schreef Thom Shaw ***@***.***>:

**Comment by mateuszpawlik** [comment]
The map file would help.

I see the error:
> ```
>  ERROR | Could not parse required sub- information from /30days/uqtshaw/BeLong_processing/raw_all_dicomsorted_zips/sub-013/ses-01/001-Localizer/SUB-013.MR.RESEARCH_TOM.0001.0001.2021.12.01.09.54.12.76178.258127961.IMA
>   using: <filepath:/raw_all_dicomsorted/sub-(.*?)/> -> 'sub-'
>  ```
Shouldn't the subject pattern be surrounded with double `<< >>`? This is how I'm using it.

**Comment by marcelzwiers** [comment]
I see that your new data is in `raw_all_dicomsorted_zips` but your bidsmap subject field (`<filepath:/raw_all_dicomsorted/sub-(.*?)/>` is using a different (older) path, i.e. `raw_all_dicomsorted`. I'll see if I can easily add a check for this issue

**Comment by marcelzwiers** [comment]
I had a look and I think it's more complicated and error prone to catch use cases where the path of the raw-folder changes between different runs of bidsmapper and/or bidscoiner. The best solution is open the bidsmap in the bidseditor and update the path in the subject and session fields by hand. I'll add some [Troubleshooting](https://bidscoin.readthedocs.io/en/stable/troubleshooting.html) documentation of this issue...

**Comment by marcelzwiers** [comment]
Alternatively, if you don't want any rawfolder paths in your bidsmap, you can use bidsmapper's `--no-update` option (the first time you run it on the raw folder). The downside is that the subject label parsing may be less robust (especially if you have no aor a very short subject prefix)

**Comment by marcelzwiers** [comment]
Feel free to reopen this issue if your problem persists
