### ISSUE TITLE
Add the possibility to track bidscoin usage

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#200]
**Is your feature request related to a problem? Please describe.**
Currently, it is unclear how much and how bidscoin is used

**Describe the solution you'd like**
Using an opt-in/out user setting (#197), I want to get information on:
- When a BIDScoin session is started
- The (hashed) user-ID  + host-ID
- The country (optional)
- The function that is called
- The error(s) that occurred
- The python version + operating system

Perhaps this information can be gathered and put into a dashboard using a combination of:
- A BIDScoin domain on the DCCN Apache server that logs the tracking URL requests made from BIDScoin. Such a request could look like: https://bidscoin.dccn.nl/tracking?call=bidsmapper&user=1234&host=5678&[max_total_length_url=2048_characters]
- [Logstash](https://www.elastic.co/logstash)
- The DCCN [Grafana](https://grafana.com/) server

**Describe alternatives you've considered**
I've considered [etelemetry](https://github.com/sensein/etelemetry-server) (used by e.g. heudiconv, nipype -> fmriprep, mriqc, etc)

**Comment by robertoostenveld** [comment]
here is a part of the apache log (ip addresses on the left cut off) 

![image](https://github.com/Donders-Institute/bidscoin/assets/899043/5e45233d-7b7d-4b69-a3b6-9256b545f42b)

**Comment by hurngchunlee** [comment]
Another option using google analytics: https://practicaldatascience.co.uk/data-science/how-to-send-data-to-google-analytics-in-python-using-pygamp

**Comment by marcelzwiers** [comment]
Perhaps, but pygamp only had 6 commits altogether and seems no longer supporting the new API?
https://github.com/flyandlure/pygamp/issues/2

**Comment by marcelzwiers** [comment]
Is Grafana Loki perhaps a solution?
https://grafana.com/oss/loki/

**Comment by hurngchunlee** [comment]
> Is Grafana Loki perhaps a solution? https://grafana.com/docs/loki/latest/get-started/overview/

Grafana Loki is very interesting.  It may be also useful for collecting and analyzing server logs concerning IT security.  Will have a look into it.

**Comment by marcelzwiers** [comment]
I just downloaded a [kali-linux virtualbox](https://www.kali.org/get-kali/#kali-virtual-machines) on my windows-10 machine, installed bidscoin and ran `bidscoin -` without any problem. I will try WSL on my personal windows-11 laptop later

**Comment by marcelzwiers** [comment]
The Loki <> Grafana option seems to be the way forward. You can now see bidscoin tracking with:
```
$ bidscoin --tracking show
INFO | trackusage = 'yes'       # Upload anonymous usage data if 'yes' (maximally 1 upload every 1 hour)
Data upload example: -> https://telemetry.donders.ru.nl/bidscoin
{
   event:       bidscoin
   bidscoin:    4.1.1
   python:      3.11.5
   system:      Linux
   release:     5.14.21-150500.55.19-default
   userid:      2feb5e843ccb54a41416f963a6c88a5d
   hostid:      e138231a68ad82f054e3d756c6634ba1
}

NB: As you can see above, BIDScoin does NOT upload any identifying details about you nor
information about the data. Uploaded data is used to generate usage and error statistics,
and helps the developers to improve BIDScoin
```
