### ISSUE TITLE
Update bidscoin on Neurodesk

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#206]
Hi Marcel, 

we recently switched to [Neurodesk](https://www.neurodesk.org) on our Server and would like to use bidscoin within this environment. Bidscoin is already prepared on Neurodesk, but the version needs to be updated (3.7.0). 
Can you reach out to Neurodesk or should I aks there for an update? 
Thanks, best
Karl

**Comment by marcelzwiers** [comment]
I think it is better if you do that, so they see there is a user demand. I am happy to help them if they encounter issues when upgrading. I have never worked with neurodesk and went to their github page to do a bidscoin keyword search. Without looking into it in depth, I did spot some old settings there (e.g. about bidstrainer, which doesn't exist anymore), and also several tools that are missing (e.g. slicereport, echocombine, etc). Furthermore, bidscoin is installed without spec2nii2bids....

**Comment by marcelzwiers** [comment]
Ok, I've opened a discussion on neurodesk, let's close this and continue over there:
https://github.com/orgs/NeuroDesk/discussions/371
