### ISSUE TITLE
Add citation information for plugin tools

### ISSUE THREAD

**Issue by wtclarke** [Donders-Institute/bidscoin#208]
Please could you add citation information for the tools that act as plugins to `bidscoin`? Plugins like `spec2nii`, 'dcm2niix' and `PET2BIDS` request that users cite other outputs when used, however it's very easy for users to miss this when using tools, like `bidscoin` that wrap these other tools.

[PET2BIDS citation info](https://github.com/openneuropet/PET2BIDS#citation)
[spec2nii citation info](https://github.com/wtclarke/spec2nii#citing-spec2nii)
[dcm2niix citation info](https://github.com/rordenlab/dcm2niix#referencing)

Would you consider listing these (and any others you know of) in the readme? Of course, with a note that they are only needed if certain functionalities are used. Do you also give citation information as an output to the user? I noticed something called `duecredit` in the source code. Is there a way that plugin developers can make this easier/automated for you?

**Comment by marcelzwiers** [comment]
I added a duecredit file myself for others to collect BIDScoin citations, but I don't create a duecredit report for the software that BIDScoin uses. Good point, I will implement that for the next release! For non-python tools, such as dcm2niix, I will add that manually. Will you add a due file for spec2nii (it's really easy, just add the file and import due.py e.g. in your main __init__.py file)

**Comment by marcelzwiers** [comment]
I added a duecredit citation for dcm2niix and spec2nii (nibabel already has one and pet2bids is nearly dead). I was able to generate a duecredit report from the commandline (although somehow it didn't work for all bidscoin tools), but I failed to interface with duecredit directly from within BIDScoin. For more info on duecredit see:

https://github.com/duecredit/duecredit

**Comment by marcelzwiers** [comment]
Mhh, I'm giving it up, duecredits lost its credits with me. I'll think of another way to add references...

**Comment by marcelzwiers** [comment]
For now, I added a link in the README to the plugins page for further citation info:
https://bidscoin.readthedocs.io/en/latest/plugins.html#dcm2niix2bids-a-plugin-for-dicom-and-par-rec-data

**Comment by marcelzwiers** [comment]
Ok, I got the duecredit lib to work, see:
https://github.com/duecredit/duecredit/issues/189

I still don't know how to use it programmatically, but that will be for later

**Comment by wtclarke** [comment]
Hi @marcelzwiers ,

Thanks for the quick and positive response. Much appreciated. I'll take a look at the suggestion you made for spec2nii shortly.

Will
