### ISSUE TITLE
Failed to execute bidscoin with 4.2.1

### ISSUE THREAD

**Issue by AzyshFotbnxe** [Donders-Institute/bidscoin#209]
**Describe the bug**
I have recently updated bidscoin from 4.0.0 to 4.2.1. Then, bidscoiner always failed with warning me TypeError: can only concatenate str (not "CommentedSeq") to str

**To reproduce**
Go to bidscoiner sourcefolder targetfolder

**Expected behavior**
It should coin the file to bids

**Screenshots**
![image](https://github.com/Donders-Institute/bidscoin/assets/44931458/726fa6c6-c954-4a6a-9732-1991123837fc)

**Software version**
 - BIDScoin version 4.2.1
 - OS Windows 10

**Comment by marcelzwiers** [comment]
I cannot look into it properly right now but I suppose you also got the
warning that your bidsmap was created with an older version? If so, then
that is the reason for your error. You can try converting the colon
separated bidsignore string into a list (bidseditor > options) or throw
away your bidsmap and rerun the bidsmapper.

_____________________
Sent from my phone

Op do 30 nov 2023 21:35 schreef sanosenx86 ***@***.***>:

**Comment by sanosenx86** [comment]
Thanks, that fixed the problem.
