### ISSUE TITLE
ERROR | Could not parse required sub-<label> label 

### ISSUE THREAD

**Issue by rbonicel** [Donders-Institute/bidscoin#211]
Hello,

**Describe the bug**
When  running the `bidsmapper -s raw/ bids/`, I get from some files that the sub-label cannot be parsed from a filepath such as "/home/robin/Documents/Database/PIP/bids/code/bidscoin/provenance/sub-99181100824104/ses-01/99181100824104/01-/601-FMRI_TE37TR800_DYN500_6MIN47_PA_SENSE1_6/IM_0001". Because of that, I cannot change the file name in the BIDS Editor GUI from those listed files because the subject id is not found.

**To reproduce**
Not sure the problem can be reproduced without my dataset

**Expected behavior**
I excepted the parser to find the subject's PSC1 ID as it is clearly stated in the file path listed in the error.

**Screenshots**
This error prevents me to properly rename the files listed in the GUI : 
![Screenshot from 2023-12-14 17-43-04](https://github.com/Donders-Institute/bidscoin/assets/48990813/96964cd1-1c82-4c71-a92e-60a8c2b8285a)

Here are the prints I added in the bids.py script, in the `subid_sesid` function and in the `dynamicvalue` function
![Screenshot from 2023-12-14 17-33-04](https://github.com/Donders-Institute/bidscoin/assets/48990813/6e9568b3-b550-40aa-8f95-bc19678771a4)
![Screenshot from 2023-12-14 17-33-20](https://github.com/Donders-Institute/bidscoin/assets/48990813/80c84aef-035a-411c-b980-e3a4e26a033d)
Here is the terminal screenshot I get from all those prints : 
![Screenshot from 2023-12-14 17-37-38](https://github.com/Donders-Institute/bidscoin/assets/48990813/7d26927f-4710-4ee1-baec-fa87e91d0079)

**Software version**
 - BIDScoin version 4.2.1
 - OS (e.g. Windows, Linux, MacOS) Linux Ubuntu 20.04

**Additional context**
I checked my DICOM files to see if the PatientName tag (0010, 0010) was present and properly filled for said subject, and it is the case.

In some of the "value" prints, I get `<<filepath:/raw_bids/sub-.*?/ses-(.*?)/>>` without parenthesis in the "sub regex. Is that expected, as the code line initially defines the subid as `<<filepath:/raw_bids/sub-(.*?)/>>` ? Does the absence of parenthesis prevents to regex to work properly ?
This error occurs on 50 files amongst 2 subjects in my database, as it is the first time I run it as a test, and to properly fill in the bidsmap.yaml.

Thanks
Robin

**Comment by marcelzwiers** [comment]
I am not sure if I fully understand how your data is organized, do you have a DICOMDIR file in your subject/session folder? Can you give me the path of a DICOM file of two subjects? And to debug, can you run the bidsmapper without the `-s` flag (makes it harder for me)?

**Comment by marcelzwiers** [comment]
See also:
https://bidscoin.readthedocs.io/en/stable/preparation.html

**Comment by rbonicel** [comment]
Hello,
I prepared my data according to the https://bidscoin.readthedocs.io/en/stable/preparation.html page for the first test. I organised it adding the "sub-" prefix before the subject ID and renaming the sessions accordingly. My data follows a DICOMDIR layout. Please see below : 
![Screenshot from 2024-01-02 10-01-04](https://github.com/Donders-Institute/bidscoin/assets/48990813/ec9c5deb-4df6-4ac6-b39a-3ae36eeefbfd)
One subject has dicom and mrs data, the other only has dicom data. 
The dicom paths are as follows : 
raw_bids/sub-99181100824104/ses-01/DICOM/IM_001 for example 

I used the `-s` flag because the runs without it got me an error saying the the used dicom file that were copied temporarily to another location were apparently deleted by the command itself, and for those files, it isn't possible to change the data type or any other naming parameter. 
![Screenshot from 2024-01-02 11-41-13](https://github.com/Donders-Institute/bidscoin/assets/48990813/aa1ef49f-6b5b-4cf6-b61b-5ab1514d0326)
![Screenshot from 2024-01-02 11-41-27](https://github.com/Donders-Institute/bidscoin/assets/48990813/9e063b7f-8f91-401f-9d10-56f86552c7da)

This last screenshot is extracted from the terminal output of the `bidsmapper raw_bids/ bids/` command. All  the files listed in the bidseditor that need review are deleted from the temp folder.
The path listed in those last screenshots are created by the command itself, as my data follows he DICOMDIR layout.

Hope this helps. I can provide any further information needed.
Thanks

Robin

**Comment by marcelzwiers** [comment]
That certainly helps. First of all, you probably don't have to rename your folder using a `sub-` prefix, because the prefix can also be passed as an input argument to bidsmapper. Second, I see you have a DICOMDIR file in your session folder, which is going to be used by bidscoin to find your DICOM files. Did you reorganise your DICOM files, i.e. make the DICOMDIR file invalid?

**Comment by rbonicel** [comment]
My data is initially organized as follows : 
`subjectid1_W1
 subjectid1_W2
 subjectid2_W1` 
and so on in the origin folder. 

I just rearranged the data as previously stated, with a `sub-` prefix and the right `ses-` prefix according to the timepoint. I then copied the whole dicom folder to another location with the proper `sub/ses` prefixes. If I look in the DICOMDIR file, the `(0004, 1500) Referenced File ID` should still be valid because the folder tree such as `['DICOM', '00000003', 'IM_1483']` (for example) should be intact. Does bidscoin uses another tag in the DICOMDIR file to find the dicom files, such as `0004, 1400) Offset of the Next Directory Record ` ?

Because my data is moved around, compressed in `tar.gz` for example. But the `Referenced File ID` supposedly remains untouched through the process.

Another thing is that the Philips anonymization process on the MRI console deletes the `SeriesDescription` tag, so for all dicom files I recreate it by filling it with `ProtocolName` tag which still contains the sequence name in my data, or other sequence related info when the `ProtocolName` is not present. But this shouldn't corrupt the DICOMDIR file if I'm not mistaken.
I do need the  `SeriesDescription` tag for the bidscoiner to work, I figured.

**Comment by marcelzwiers** [comment]
I got a bit puzzled because your error is caused by a missing prepended `raw_bids` part in the provenance store (i.e. it should have been `/bids/code/bidscoin/provenance/raw_bids/sub-etc`. A quick workaround would be to replace the `raw_bids` sub-string in your subject/session regexps with `provenance`. However, I do like to better understand what is happening here, and solve it properly... Could you try removing the `ses-..` folders in `raw_bids`, i.e. put the DICOMDIR data directly in the `sub-..` folders?

**Comment by marcelzwiers** [comment]
A useful debugging print statement would be to change the lines (around 129) to:

```python
                for sesfolder in sesfolders:
                    if store:
                        print(f"***DEBUG***: sesfolder={sesfolder}" if unpacked else '')
                        store = {'source': sesfolder.parent.parent.parent.parent if unpacked else rawfolder.parent,
                                 'target': bidscoinfolder/'provenance'}
```

**Comment by rbonicel** [comment]
> A useful debugging print statement would be to change the lines (around 129) to:
> 
> ```python
>                 for sesfolder in sesfolders:
>                     if store:
>                         print(f"***DEBUG***: sesfolder={sesfolder}" if unpacked else '')
>                         store = {'source': sesfolder.parent.parent.parent.parent if unpacked else rawfolder.parent,
>                                  'target': bidscoinfolder/'provenance'}
> ```

Could you please tell me to which script you are referring in this comment ? In the `bids.py` script, around line 129, it's where the `properties` is defined.

**Comment by marcelzwiers** [comment]
Sorry, that print statement is for the bidsmapper.py

**Comment by marcelzwiers** [comment]
Good, now the next step. I think DICOM files were not properly named because of the missing (anonymized) `SeriesDescription` field. Didn't you get any warning saying: `File already exists: ..`?

**Comment by rbonicel** [comment]
> Good, now the next step. I think DICOM files were not properly named because of the missing (anonymized) `SeriesDescription` field. Didn't you get any warning saying: `File already exists: ..`?

Yes absolutely, for all files I think. So a new name was created. Do I need to clean something else before running the bidmapper with clean data ? I checked the `/home/robin/.bidscoin/4.2.1/templates` but they seemed untouched. 

FIY, the start of the command looks like this : 
![Screenshot from 2024-01-03 17-37-10](https://github.com/Donders-Institute/bidscoin/assets/48990813/83a58844-42da-476a-9008-42d5e6603ab0)
Should I be worried about the  `Could not validate every run-item in the bidsmap`

**Comment by marcelzwiers** [comment]
In your path I see sub-folders names `01-` (right after the subject folder), what are those? That looks suspicious to me...

**Comment by marcelzwiers** [comment]
> Should I be worried about the Could not validate every run-item in the bidsmap

No, I should probably delete that print statement. Bidsmaps are checked for correctness when loaded, however, some fields cannot be automatically checked because of some complicated BIDS specifications

**Comment by marcelzwiers** [comment]
Btw, you can also run `dicomsort` directly on (a testcopy of) the raw subject folder. That easier / quicker

**Comment by rbonicel** [comment]
> In your path I see sub-folders names `01-` (right after the subject folder), what are those? That looks suspicious to me...

I do not know. This path is created by the script itself when it notices that the `File already exists` and creates a new name. For example : `WARNING | File already exists: /tmp/tmpi96jvjbs/home/robin/Documents/Database/PIP/raw_bids/sub-99181100856109/DICOM/00000002/IM_2037 -> /tmp/tmpi96jvjbs/home/robin/Documents/Database/PIP/raw_bids/sub-99181100856109/99181100856109-w1/01-/901-WIP_DTI_PIPDIR_B1000PA_TE75TR6400_ISO2/IM_2037`

I understand the first path, as it is what I expect from for my exam folder. But the second path seems created by the script gathering info from the DICOM file itself : 
`99181100856109-w1` is the content of `(0010, 0010) PatientName` tag. `901-WIP_DTI_PIPDIR_B1000PA_TE75TR6400_ISO2` is the concatenation of `(0020, 0011) SeriesNumber` tag, a `-` and the `SeriesDescription` tag. I thought `01-` was the session number added by the bidsmapper command.

Upon looking for the warning in `dicomsort.py`, I get the following construction for `newfilename`, in the `sortsession` function : 
![Screenshot from 2024-01-04 09-59-03](https://github.com/Donders-Institute/bidscoin/assets/48990813/cfa7aa10-95cf-4040-a76c-9c20d0ac3281)

So I'm guessing that the construction of the `newfilename` in the `construct_name` creates this. Do you know from where this `01-` part could come from ? I didn't see in the dicom header which info could be used for this. 
I'll run `dicomsort` alone with some prints and post the result here.

**Comment by rbonicel** [comment]
> Btw, you can also run `dicomsort` directly on (a testcopy of) the raw subject folder. That easier / quicker

I think the reason I didn't run `dicomsort` alone in the first place is this : 
![Screenshot from 2024-01-04 10-13-20](https://github.com/Donders-Institute/bidscoin/assets/48990813/d83b64f1-62a5-421d-838a-27ee16a3f6a4)

I'm using the hospital connection which used to be problematic but now they changed it and I can access the internet, git, do commits and pc updates. So any call to `urlopen` should work.

**Comment by rbonicel** [comment]
I ran the `dicomsort` on the non ano subject, `99181100857100`. It works perfectly without any `File already exists` warning and gave the following folder : 
![Screenshot from 2024-01-04 13-49-54](https://github.com/Donders-Institute/bidscoin/assets/48990813/a5330b47-9544-4a02-a5e9-f1936499284f)
I renamed the created folder `99181100857100` to `sub-99181100857100` (because I got the error that started this issue, `ERROR | Could not parse required sub-<label> label from`, and ran the following command : `bidsmapper -n 'sub-' '/home/robin/Documents/Database/PIP/raw_bids_non_ano/99181100857100_W1/' '/home/robin/Documents/Database/PIP/bids'`.
![Screenshot from 2024-01-04 13-41-45](https://github.com/Donders-Institute/bidscoin/assets/48990813/f0bc7fe9-40f2-4457-ad1a-684e81a8e79e)

I renamed successfully the files that needed : 
![Screenshot from 2024-01-04 13-42-07](https://github.com/Donders-Institute/bidscoin/assets/48990813/d44b5c61-0c83-4709-a84b-56881ccb285a)

I then ran `bidscoiner '/home/robin/Documents/Database/PIP/raw_bids_non_ano/99181100857100_W1' '/home/robin/Documents/Database/PIP/bids'` and got the following result : 
![Screenshot from 2024-01-04 13-44-23](https://github.com/Donders-Institute/bidscoin/assets/48990813/7e95fafc-fbcb-4b20-be5e-8cc8cb763390)
which is what I expected. So I guess with this non ano exam, it worked well. 

For the other subjects, I need to keep the origin data as is, but create the `SeriesDescription` tag and run everything. 
What I don't get is that the `dicomsort.py` has these lines 
![Screenshot from 2024-01-04 14-00-40](https://github.com/Donders-Institute/bidscoin/assets/48990813/ca5440e5-c879-4188-93d5-bfdbe6db124e)
in the `construct_name` function, so I shouldn't need to create the extra tag, because I have the `ProtocolName` tag available. 

So my final questions are  : 
- why is the `ProtocolName` tag not taken as an alternative when `SeriesDescription` is not available ?
- How to get rid of the `File already exists` warning which gets to code to perform operations that are not suitable for the process to succeed ?

Thanks for all the help on the matter.

**Comment by rbonicel** [comment]
Hello,

I tried running the `dicomsort` function on my whole cohort. I still get the `File already exists` warning for all my files, so I fear that in the end, the same problem as before occurs. If you have any advice to make this warning disappear, it would help me greatly. 

I came across another error which is the following : 
![Screenshot from 2024-01-15 10-23-43](https://github.com/Donders-Institute/bidscoin/assets/48990813/523a4550-38ef-4f2f-90d1-40485443a337)

I tried to open said file with `pydicom` and it got me `InvalidDicomError: File is missing DICOM File Meta Information header or the 'DICM' prefix is missing from the header. Use force=True to force reading`
Same with `MRIConvert` : `Not added. File is <128 byes. Not a valid DICOM file.`

So I'm wondering why the `dicomsort` function doesn't set the file aside on its own but raises an error, if the file is not of valid type/corrupted. 
I can remove it from my folder and keep going, doing this for all files raising the same error, but I'm wondering about the error handling process of `dicomsort` in such case.

Thank you.

**Comment by marcelzwiers** [comment]
> So I guess with this non ano exam, it worked well.

Good, so it seems that missing DICOM fields have caused all the issues. Dicomsort uses `SeriesDescription` (or, if that's not available it will fall back to `ProtocolName`), as well as `SeriesNumber` (or, if that's not available it will fall back to  `SeriesInstanceUID`). Is the latter perhaps also removed in the anonymization step?

> So my final questions are :
> -  why is the ProtocolName tag not taken as an alternative when SeriesDescription is not available?

I'm pretty sure it will be used and that you don't need to re-write the SeriesDescription field yourself

> - How to get rid of the File already exists warning which gets to code to perform operations that are not suitable for the process to succeed?

In principle, the warning should not happen, but it may be the result of missing `SeriesNumber` values. The warning itself is innocent (it's just about giving the file a new name). It's really difficult for me to see what is going from a distance. Is there any chance you can give me copy of one of your anonymized datasets (the two session of one subject)?

**Comment by marcelzwiers** [comment]
Perhaps you can tell people not to anonymize the data so aggressively, it's really silly and causing massive problems

**Comment by rbonicel** [comment]
> Perhaps you can tell people not to anonymize the data so aggressively, it's really silly and causing massive problems

Since I started this issue, I asked the MRI team to stop using Philips' anonymization process altogether. I'll take care of it with a lighter routine. The tests gave better results with non-anon data, so I will proceed like this from now on. I need to save old data, though. 

> Good, so it seems that missing DICOM fields have caused all the issues. Dicomsort uses SeriesDescription (or, if that's not available it will fall back to ProtocolName), as well as SeriesNumber (or, if that's not available it will fall back to SeriesInstanceUID). Is the latter perhaps also removed in the anonymization step?

The last two should be available is th edicom, even with the Philips anon process. I proceeded to two tests : one running `dicomsort` on the modified data with the extra tag and one running it on the origin data, using `ProtocolName` as the highest available info in your list. Good news is that I get the same result in both cases.  So indeed, the re-writing of the `SeriesDescription` can be discarded. 

> I'm pretty sure it will be used and that you don't need to re-write the SeriesDescription field yourself

Yes indeed

But I still have some trouble on some exam folders, with one of the following two errors : 
- nothing is sorted in the exam (and the data is untouched
- some or most of the exam is sorted, leaving out some unsorted sequences, present in the origin exam. 

Can I send you some of this data out of github ? I'll try running the fails again with a printed log if possible.

**Comment by marcelzwiers** [comment]
You will also get the error: `Missing 'SeriesDescription' ..` if both your SeriesDescription and your ProtocolName fields are empty (I suppose that's what happened).

I'd like to understand what causes your issue with the path to the DICOMDIR file, can you perhaps insert `print(f"***DEBUG***: sesfolder={sesfolder}" if unpacked else '')` in bidsmapper.py (around line 129, see earlier some post) and report its output? Does the non-anonymized DICOMDIR data work normally if you include the ses-folders?

```matlab
                for sesfolder in sesfolders:
                    if store:
                        print(f"***DEBUG***: sesfolder={sesfolder}" if unpacked else '')
                        store = {'source': sesfolder.parent.parent.parent.parent if unpacked else rawfolder.parent,
                                 'target': bidscoinfolder/'provenance'}
```

> I don't know which path to feed the dicomsort function for it to work

If you lost the DICOMDIR file, you can perhaps run dicomsort directly on the ses-folder? Again, it's unfortunately quite difficult to debug from a distance

> but it only sorts a few sequences of the whole exam

Is that for the anonymized data?

**Comment by marcelzwiers** [comment]
> If you could help me on those last two exams, if I send you the data, that'd be great.

Sure, just email me so we can arrange a safe transfer

**Comment by rbonicel** [comment]
While we set up the transfer for the two remaining exams, I started mapping the correctly sorted exams. 
I ran the `bidsmapper` function once and started renaming about 60 files (in 650 that needed renaming). I figured that I'd save the `bidsmap.yaml` in the default `bidsfolder/code/bidscoin` folder corresponding to the cohort.

When I ran the `bidsmapper` again, all the same files popped again in the editor, including the ones I already renamed by hand. All files were labeled "exclude", though, where I though that the second run would rename all the same name sequences according to the few first I did by hand.  Is it not how it's supposed to be ?

For example, one sequence is named `T1ADNI` for one exam, and I renamed it `t1anatomical` in the `acq` field. I expected that all `T1ADNI` in the other exams would be renamed in the same fashion. 

Thanks

**Comment by marcelzwiers** [comment]
650 files? Is that renaming in the bidseditor or do you mean the filenames themselves? The latter shouldn't be necessary, so I assume you mean the bidseditor. And that's not good at all! The bidsmap should be a shortlist of the different scan that you made, not a list of all your scans. I suspect that there is a DICOM field in the bidsmap template that varies from scan to scan. If you remove that then you will have a very short list

**Comment by rbonicel** [comment]
650 files-ish to be renamed in the bidseditor, yes. See below : 
![Screenshot from 2024-01-18 16-44-45](https://github.com/Donders-Institute/bidscoin/assets/48990813/a6d4e1ce-5aee-48d3-903a-4831f1893e7f)
The `SeriesNumber` may vary, along with some of the sequences names (`SeriesDescription/ProtocolName`), but not so much. 

How do I cleanly remove/ignore the info that varies from the bidsmap template, please ? I'll start with TR/TE until I get a short list.

**Comment by marcelzwiers** [comment]
SeriesNumer is not used in the template bidsmap to identity scans. I mean
something like this:

```yaml

attributes: &anat_dicomattr   # An empty / non-matching reference
dictionary that can be dereferenced in other run-items of this data
type
  Modality:
  ProtocolName:
  SeriesDescription:
  ImageType:
  SequenceName:
  PulseSequenceName:
  SequenceVariant:
  ScanningSequence:
  EchoPulseSequence:          # Enhanced DICOM
  MRAcquisitionType:
  SliceThickness:
  FlipAngle:
  EchoNumbers:
  EchoTime:
  EffectiveEchoTime:
  RepetitionTime:
  InPlanePhaseEncodingDirection:

```

Op do 18 jan 2024 om 16:48 schreef Robin Bonicel ***@***.***>:

**Comment by marcelzwiers** [comment]
Your bidseditor should have less than 10 items or so

Op do 18 jan 2024 om 17:17 schreef Marcel Zwiers ***@***.***>:

**Comment by marcelzwiers** [comment]
I will make a FAQ about this, because this a nogo

Op do 18 jan 2024 om 17:18 schreef Marcel Zwiers ***@***.***>:

**Comment by rbonicel** [comment]
I have one or two exams that have no info except the `SeriesNumber`, so I'm alright with the fact that I need to renamed all those sequences at least once. But for the rest, I have the `ProtocolName`. Commenting on items doesn't get me lower than 218 files in the bidseditor so far. (I have some `PS_` and `XX_` files to discard as `exclude`, also. I don't get why they are listed as they're not dicom files. 

I guess I'll have to do the renaming on those 218 files, because I don't want to corrupt the template too much by removing too many items. Or am I missing some item that can be safely removed from the template ?

**Comment by marcelzwiers** [comment]
For a single scan (e.g. a T1w) there should only be one entry in the
bidseditor. If you have more, then you should open (click on edit) and
compare two items and see which DICOM fields are different between the
scans. They should be the same

Op do 18 jan 2024 om 17:25 schreef Robin Bonicel ***@***.***>:

**Comment by rbonicel** [comment]
I check 3 exams so far. With the commenting of both  `EchoTime` and `RepetitionTime` in the bidsmap template, I seem to have only one file per sequence for each exam. 
If this is the expected behaviour, then we're good and I need to rename all the 218 files. I excepted the same sequence across every exam (e.g a T1w) to be present in the bidseditor only once according to its name, taking into account that I commented two values that can slightly change between exams (TR and TE).

I'm running the bidseditor on all the cohort for the first time, so one file per sequence and per exam could very well yield 218 files, taking into account that the `dicomsort` sorted a lot of useless files such as : 
![Screenshot from 2024-01-18 17-49-00](https://github.com/Donders-Institute/bidscoin/assets/48990813/ac5bd8ea-de0e-45da-b02c-26c906617674)
Those files, however non dicom format, would still need sorting as "exclude" data.

**Comment by marcelzwiers** [comment]
The idea is that you tell bidscoin how to convert each scan, then bidscoin
will do that for each subject. You don't have to tell bidscoin how to
convert individual subjects

Op do 18 jan 2024 om 18:00 schreef Marcel Zwiers ***@***.***>:

**Comment by rbonicel** [comment]
Ok, then I'll look into that and check why I have so many files, focusing on the MRI sequences and image files. 

Another question in that aspect is that I have a lot of `PS_` and `XX_` files to process. Those files are non DICOM, hence they have very few `attributes` in the bidseditor (which is normal), and their `ProtocolName` and `SequeceName` vary according to the time of the acquisition, which is written in the name. Given that, I understand that I have a lot of files to rename from the same sequence across exams.

Wouldn't it be better to discard those `PS_` and `XX_` files from the mapping ? Or are those useful for spectro sorting ? (I don't see the point of them in MRI sequences such s T1w or fMRI.

**Comment by rbonicel** [comment]
I renamed all the files that needed it in the bidseditor, and validated the created bidsmap. 
![Screenshot from 2024-01-22 16-25-14](https://github.com/Donders-Institute/bidscoin/assets/48990813/a5ee6083-c1cf-42ad-ab2f-f8b63c3a9315)
Is it normal that there's a `DICOM` field in the bids sequence names, as shown above ? 

When running `bidscoin /raw /bids` , the terminal prints that it's "leaving out" all the sequences in the exams, not only the labeled "exclude data". I'm left with empty exam folders in the `/bids` directory, empty `tsv` and `json` files. I have some properly renamed in the `bidseditor`, though, as shown by the "True" statement when validating the data, so I don't get the absence of conversion.

**Comment by marcelzwiers** [comment]
> I started renaming all the 216 listed files in the bidseditor

That's really not the idea

**Comment by rbonicel** [comment]
> > I started renaming all the 216 listed files in the bidseditor
> 
> That's really not the idea

I know, but I think it made sense regarding what you told me and my previous comment, about the names (`SeriesDescription` and/or `ProtocolName`) slightly changing between sequences, or dicom tags present/absent due to the Philips anon process. I think the bidseditor works fine in that aspect, and it's our protocol that was not properly set up.
I did a backup of the created bidsmap, to keep it when using the `-f` flag by mistake...which I did.

**Comment by marcelzwiers** [comment]
I made a fix for your parsing error, but I still need to look into why not all scan types are found. You can already install and try the latest version like this:

```console
pip install --force-reinstall --no-deps git+https://github.com/Donders-Institute/bidscoin
```

**Comment by marcelzwiers** [comment]
The renaming warnings are annoying (because there are so many) but harmless

**Comment by marcelzwiers** [comment]
Ok, I added another tweak, the latest version should work much better for you

**Comment by rbonicel** [comment]
> Ok, I added another tweak, the latest version should work much better for you

Thanks. I'll try it on the two remaining exams I sent you ? This should fix the sorting of those exams ? 
What about the "leaving out" of every and all sequences ? Will the tweak fix it too ? 

I seem to recall in one of my early tests that once I renamed a few sequences in the `bidseditor`, saved the bidsmap and reloaded it, every item in the list was labeled as `exclude` data, which could well explain current behaviour.

**Comment by rbonicel** [comment]
Ok, I'll try fixing the dataset. 

The main concern with the `exclude` datatype is that when running the `bidscoin /raw /bids` command, it leaves out every single sequence of every single exam, not converting a single thing, although I properly renamed some files. 
Another related question I have is the following : when I rename the fields on a sequence I want to keep, but related to a file to exclude (a `PS_` or `XX_` file), will it consider every sequence with the same name as `exclude` ? 
Those `PS_` or `XX_` files are sorted alone in a folder named `000_SequenceNameToKeep`, so I figured that they needed to be removed, as files and also sequences. But maybe I'm mistaken, and that explains that all goes to the `exclude` type ?

This is the last issue I need to fix, and all will be right after.

**Comment by marcelzwiers** [comment]
Filenames are irrelevant unless you use `<fileparts>` or so in your bidsmap. The automatic datatyping to `exclude` has to do with the `exclude` run-items in the template bidsmap (they are to greedy for you). I would like it if you could test things without making so many hacks, because 1) it should work out of the box anyway, and 2) it becomes very difficult for me to understand what is caused by bidscoin and what is caused by your hacks

**Comment by marcelzwiers** [comment]
I think your best option would be to run dicomsort first, e.g. like this:
```console
dicomsort rawfolder -i sub- -j ses- -p '.*'
bidsmapper rawfolder bidsfolder
```

**Comment by rbonicel** [comment]
Sure thing, sorry about the complexity of the problem. 
Since this comment [https://github.com/Donders-Institute/bidscoin/issues/211#issuecomment-1894208337](url), I work on the original data. I completely dropped the dataset where I created extra tags when I figured it was my understanding of the commands and their flags that was at fault. 

When I got the result that `dicomsort` created the sorted sequence folders alongside the original data ( `DICOM` folder and `DICOMDIR` file) such as : 
![Screenshot from 2024-01-24 17-45-41](https://github.com/Donders-Institute/bidscoin/assets/48990813/e38f90e4-3813-4abf-ba19-ba382d26f352)
I removed the original data before going to the next step. Should I leave it in the folder ? (I was worried it would take duplicated data, both sorted and original folders)

Will run the `dicomsort` with the `-p` flag on the remaining data.

Sorry again about the inconvenience.

**Comment by rbonicel** [comment]
> ```
> dicomsort rawfolder -i sub- -j ses- -p '.*'
> ```

This command with the `-p` flag sorted all data in the two remaining exams I had (the ones I sent you). Great news, all my exams are now properly sorted !

**Comment by marcelzwiers** [comment]
Good, and you still have a long- instead of a short-list in the bidseditor?

**Comment by rbonicel** [comment]
Yes. I ran the `bidsmapper` command twice : 
- once with the original `bidsmap_dccn.yaml` template or `v4.3.0` with the last tweaks : it gave me more than 650 files
- one commenting all 9 occurrences of `EchoTime` and 10 occurrences of `RepetitionTime` in the template : it gave me 223 files

I have a bit more files than previously because I added the last 2 exams that were missing from the previous run. 
So that's ok by me, but if you did something regarding the list in the `bidseditor`, it had no effect on list length.

**Comment by marcelzwiers** [comment]
Can you give me a screenshot of two identical scans in the bidseditor, such that I can see the parameters (i.e. click on edit -> screenshot, and then the same for the other scan)?

**Comment by marcelzwiers** [comment]
>  10 occurrences of RepetitionTime
I don't know what that means

**Comment by rbonicel** [comment]
> > 10 occurrences of RepetitionTime
> 
> I don't know what that means

I commented the parameters `RepetitionTime` and `EchoTime` in the bidsmap template as you advised, so those parameters wouldn't be considered to compare sequences in the bidseditor

**Comment by marcelzwiers** [comment]
Right, so as I see it your dicomsort problem is solved and the long-list problem is due to anonymization. I guess that closes this issue, but feel free to re-open if not. Thanks for your feedback!

**Comment by rbonicel** [comment]
Yes, the dicomsort problem is sorted ! 
This issue is now closed.
Thanks so much for you extensive help, and sorry to have mixed various issues. I might open another one about the `bidscoiner` command that I got mixed up in this issue.
