### ISSUE TITLE
Add easy to check output with information on what source was converted to what BIDS files

### ISSUE THREAD

**Issue by DominikaZ** [Donders-Institute/bidscoin#217]
Hello, I would like to suggest a new feature for bidscoin - it would be great if bidscoin could generate information about what source files where converted to what out files and it would be really amazing if the information could include some file metadata that user will define, for example SeriesDescription - if user maps a lot of data based upon this attribute, user can quickly identify if the mappings look correct when this information will be included. Or SeriesNumber, for easier orientation in files and so on.

I understand that this is a little stretch, however, it can be really valuable because user can quickly scan the results of bidscoin run in one file to see if everything was converted (or skipped) correctly, as opposed to checking all files individually. This information can be seen also from bidsmap, but bidsmap won't include changes done due to runs or dcm2niix postfixes.

Maybe this can be done in accordance with [BEP028_BIDSprov](https://github.com/bids-standard/BEP028_BIDSprov/tree/master), which would add more complexity, but would be beneficial for provenance tracking.
In that case, the provenance would include a lot more information, so it would be great if we could just grab e.g entries with label "input" and "output", to quikly check the results. User defined metadata could be maybe included via outputting also what bidsmap entry was used for conversion.

**Comment by marcelzwiers** [comment]
BIDSprov is nice but involves adding a whole framework, and I doubt whether anyone is ever going to use it. So let's first get a better idea of what the goal is. I myself would for instance like to save records with tags, bidsmap-provenance, inputfiles, command, outputfiles. Because of the variable length, this doesn't match well with tsv files, which is also why the BIDSprov is all about jsons.

**Comment by marcelzwiers** [comment]
So does it have to be human readable, computer readable or both?

**Comment by marcelzwiers** [comment]
If it only needs to be human-readable, then adding a special provenance logger would perhaps be sufficient (it's a simple thing to do), for machine-readable it will probably be json. I don't readily see how it can be both?

**Comment by DominikaZ** [comment]
Maybe we could save jsons in a way that allows people convert them to any human-readable form they like? I feel like making it machine readable can have more power.
Do you think that there is a way to also include in the json provenance bidsmap entry that was used for conversion, meaning concrete entry from bidsmap.yaml used by bidscoiner? The entry includes attributes, which we can check that are ok regarding the output image.

**Comment by marcelzwiers** [comment]
> Do you think that there is a way to also include in the json provenance bidsmap entry that was used for conversion, meaning concrete entry from bidsmap.yaml used by bidscoiner

Yes, but that would require a (small) change to bids.`get_matching_run()`, to have it return the bidsmap provenance string. That provenance string acts as an (in practice unique) identifier, so that you can always look up the entire run-item.

**Comment by marcelzwiers** [comment]
```python
def find_run(bidsmap: Bidsmap, provenance: str, dataformat: str='', datatype: str='') -> Run:
    """
    Find the (first) run in bidsmap[dataformat][bidsdatatype] with run['provenance'] == provenance

    :param bidsmap:     This could be a template bidsmap, with all options, BIDS labels and attributes, etc.
    :param provenance:  The unique provenance that is used to identify the run
    :param dataformat:  The dataformat section in the bidsmap in which a matching run is searched for, e.g. 'DICOM'. Otherwise, all dataformats are searched
    :param datatype:    The datatype in which a matching run is searched for (e.g. 'anat'). Otherwise, all datatypes are searched
    :return:            The (unfilled) run item from the bidsmap[dataformat][bidsdatatype]
    """
```

**Comment by marcelzwiers** [comment]
> Yes, but that would require a (small) change to bids.get_matching_run(), to have it return the bidsmap provenance string

I will make that change now, as it can be easily done without any consequence

**Comment by DominikaZ** [comment]
> > Do you think that there is a way to also include in the json provenance bidsmap entry that was used for conversion, meaning concrete entry from bidsmap.yaml used by bidscoiner
> 
> Yes, but that would require a (small) change to `bids.get_matching_run()`, to have it return the bidsmap provenance string. That provenance string acts as an (in practice unique) identifier, so that you can always look up the entire run-item.

Makes sense!

**Comment by DominikaZ** [comment]
> BIDSprov is nice but involves adding a whole framework, and I doubt whether anyone is ever going to use it. So let's first get a better idea of what the goal is. I myself would for instance save records with [(optional) tags, bidsmap-provenance, inputfiles, command, outputfiles]. Because of the variable length, this doesn't match well with tsv files, which is also why the BIDSprov is all about jsons.

I think we can still output jsons in BidsProv format if we like it without needing that framework, just creating the entries in that format, for example:

bidscoin default agent without activities and entities:
```
               "@context": "https://raw.githubusercontent.com/bids-standard/BEP028_BIDSprov/master/context.json",
               "BIDSProvVersion": "dev",
               "Records": {
                   "Software": [
                       {
                           "@id": "urn:" + agent_id,
                           "RRID": "RRID:SCR_022839",
                           "@type": "prov:SoftwareAgent",
                           "Label": "Bidscoin",
                           "Version": __version__
                       }
                   ],
                   "Activities": [],
                   "Entities": [],
               },
```

Then when running bidscoin, adding Activities performed and Entities used.
It is more complicated though, then outputting `[(optional) tags, bidsmap-provenance, inputfiles, command, outputfiles]`.

Also, regarding including the bidsmap entry used for conversion, I don't think BidsProv supports it - I am not sure in what format would the entry for that be. If we would like to add all keys and values of that entry, it could be maybe under `params` parameter of Activity, but that is I think supposed to be for key:value pairs used in command of that activity.
I think that maybe we can just save the unique provenance identifier of that bidsmap entry in these jsons, but if we go with bidsprov, I am again not sure under what tag to include it.

**Comment by marcelzwiers** [comment]
I'm ok with adding some complexity to make things more future proof. I would, however, like to keep things/complexities away from the plugins as much as possible

**Comment by marcelzwiers** [comment]
I'm working towards a new bidscoin release (4.3), perhaps this issue can still be part of it? Do you want to make a PR with the changes that you would like to have? I will help out developing it from there

**Comment by DominikaZ** [comment]
Sure!

For BEP028, we could maybe do something like this:

```
{
    "@context": "https://raw.githubusercontent.com/bids-standard/BEP028_BIDSprov/master/context.json",
    "BIDSProvVersion": "dev",
    "Records": {
        "Software": [
            {
                "@id": "urn:363748e0-c76d-4cc6-b8a6-4269bf81fab9",
                "RRID": "RRID:SCR_022839",
                "@type": "prov:SoftwareAgent",
                "Label": "bidscoin",
                "Version": "4.3.0"
            },
            {
                "@id": "urn:8e9053c3-3a35-4c02-8ae0-6de38336fcd7",
                "RRID": "SCR_023517",
                "@type": "prov:SoftwareAgent",
                "Label": "dcm2niix",
                "Version": "v1.0.20220505"
            }
        ],
        "Activities": [
            {
                "@id": "urn:1bafeb8d-264b-4dd9-9be4-ce2a5f1c9df5",
                "Label": "bidsmapper",
                "AssociatedWith": "urn:363748e0-c76d-4cc6-b8a6-4269bf81fab9",
                "Command": "bidsmapper myproject/raw myproject/bids -t bidsmap_custom",
                "Parameters": {},
                "Used": []
            },
            {
                "@id": "urn:c8651006-ceba-42bb-8f8f-64167d9f026d",
                "Label": "bidscoiner",
                "AssociatedWith": "urn:363748e0-c76d-4cc6-b8a6-4269bf81fab9",
                "Command": "bidscoiner myproject/raw myproject/bids",
                "Parameters": {},
                "Used": []
            },
            {
                "@id": "urn:3b18fdf9-45dc-4536-a632-1c4463a7717a",
                "Label": "dcm2niix",
                "AssociatedWith": "urn:8e9053c3-3a35-4c02-8ae0-6de38336fcd7",
                "Command": "dcm2niix -b y -z y -i n -l n -f 'sub-01_T1w' -o 'myproject/bids/sub-01/anat' 'myproject/raw/sub-01/std1_03_t1_mprage_sag_p2_1isow/'",
                "Parameters": {
                    "bidsmap_provenance": "myproject/raw/sub-01/std1_03_t1_mprage_sag_p2_1isow/00001.dcm"
                },
                "Used": ["urn:4362208f-ea8b-4b4f-8f7c-f2d7b21d342b"]
            },
            {
                "@id": "urn:4d3a9181-2aad-4589-93cc-ccc93f0a0e4e",
                "Label": "dcm2niix",
                "AssociatedWith": "urn:8e9053c3-3a35-4c02-8ae0-6de38336fcd7",
                "Command": "dcm2niix -b y -z y -i n -l n -f 'sub-01_task-bold25isotr980rest_sbref' -o 'myproject/bids/sub-01/func' 'myproject/raw/sub-01/std1_04_bold_25iso_tr980_rest_SBRef'",
                "Parameters": {
                    "bidsmap_provenance": "myproject/raw/sub-01/std1_04_bold_25iso_tr980_rest_SBRef/00001.dcm"
                },
                "Used": ["urn:9b584ee0-b95e-4942-aece-23c6d7eac565"]
            }
        ],
        "Entities": [
            {
                "@id": "urn:86648548-ef86-4c65-acb2-f66f919cd602",
                "Label": "bidsmap.yaml",
                "AtLocation": "/home/smith/myproject/bids/code/bidscoin/bidsmap.yaml",
                "GeneratedBy": "urn:1bafeb8d-264b-4dd9-9be4-ce2a5f1c9df5"
            },
            {
                "@id": "urn:1023f701-3809-4dfa-a5db-95a8bf03b9b4",
                "Label": "dataset_description.json",
                "AtLocation": "/home/smith/myproject/bids/dataset_description.json",
                "GeneratedBy": "urn:c8651006-ceba-42bb-8f8f-64167d9f026d"
            },
            {
                "@id": "urn:12f091f0-d4d2-4e45-80db-433d4bcac9ec",
                "Label": "README.md",
                "AtLocation": "/home/smith/myproject/bids/README.md",
                "GeneratedBy": "urn:c8651006-ceba-42bb-8f8f-64167d9f026d"
            },
            {
                "@id": "urn:c49fe0fe-52a2-4c2d-98ca-3786b8af1015",
                "Label": "skipped",
                "AtLocation": "/home/smith/myproject/raw/sub-01/std1_01_AAHead_Scout/00001.dcm"
            },
            {
                "@id": "urn:c18b49a9-f7c6-4e36-9954-3a562af73d72",
                "Label": "skipped",
                "AtLocation": "/home/smith/myproject/raw/sub-01/std1_02_localizer/00001.dcm"
            },
            {
                "@id": "urn:4362208f-ea8b-4b4f-8f7c-f2d7b21d342b",
                "Label": "std1_03_t1_mprage_sag",
                "AtLocation": "/home/smith/myproject/raw/sub-01/std1_03_t1_mprage_sag/00001.dcm"
            },
            {
                "@id": "bids::sub-01/anat/sub-01_T1w.nii.gz",
                "Label": "sub-01_T1w.nii.gz",
                "AtLocation": "/home/smith/myproject/bids/sub-01/anat/sub-01_T1w.nii.gz",
                "GeneratedBy": "urn:3b18fdf9-45dc-4536-a632-1c4463a7717a"
            },
            {
                "@id": "urn:9b584ee0-b95e-4942-aece-23c6d7eac565",
                "Label": "std1_04_bold_25iso_tr980_rest_SBRef",
                "AtLocation": "/home/smith/myproject/raw/sub-01/std1_04_bold_25iso_tr980_rest_SBRef/00001.dcm"
            },
            {
                "@id": "bids::sub-01/func/sub-01_task-bold25isotr800rest_echo-1_bold.nii.gz",
                "Label": "sub-01_task-bold25isotr800rest_echo-1_bold.nii.gz",
                "AtLocation": "/home/smith/myproject/bids/sub-01/func/sub-01_task-bold25isotr980rest_echo-1_sbref.nii.gz",
                "GeneratedBy": "urn:4d3a9181-2aad-4589-93cc-ccc93f0a0e4e"
            },
            {
                "@id": "bids::sub-01/func/sub-01_task-bold25isotr980rest_echo-1_part-phase_sbref.nii.gz",
                "Label": "sub-01_task-bold25isotr980rest_echo-1_part-phase_sbref.nii.gz",
                "AtLocation": "/home/smith/myproject/bids/sub-01/func/sub-01_task-bold25isotr980rest_echo-1_part-phase_sbref.nii.gz",
                "GeneratedBy": "urn:4d3a9181-2aad-4589-93cc-ccc93f0a0e4e"
            }
        ]
    }
}
```

However, I am a bit unfamiliar with jsonld and I am not sure how the user can then frame this with pyld in order to extract direct information about from what inputs came what outputs.
For sure, one could just load this json, create dictionary **entities** and **activities**, with ids as keys (to have direct access by id). Then create result directory by iterating over activities, adding to result that activity and for param used change the id to corresponding entity data (from created entity dictionary) and then iterate over entities to check those that have param Generated_by to add them to responding result activity, because activity doesn't have Generates or something similiar. Which would kinda result in ` [(optional) tags, bidsmap-provenance, inputfiles, command, outputfiles]` dictionary.

Not sure if it is not too much work, but maybe there is more direct approach utilizing jsonld.

This also bends the definition of BEP028 a little bit regarding
                "Parameters": {
                    "bidsmap_provenance": "...."
                },
to include which bidsmap entry was used. It is probably meant to be for e.g command: bidsmapper myproject/raw myproject/bids -t bidsmap_custom   then params: {"-t": "bidsmap_custom"}
Maybe it is also incorrect to have as outputs of dcm2niix final bidscoin outputs, because in some cases bidscoin renames the files afterwards so e.g. dcm2niix outputs should be files ..._e1_ph and the renaming should maybe be separate activity - rename. Which would complicate things.
I simplified param used and put there only the first 001.dcm instead of all used that were in the folder.
Skipped files with label "skipped" also do not have params with bidsmap_provenance which would be really useful to include based upon which bidsmap entry they were labeled as ones to skip.

This example is just a try to define how it could look like in BEP028.
Outputting directly `[(optional) tags, bidsmap-provenance, inputfiles, command, outputfiles]` as json without the need to lookup entities by id could be easier.

**Comment by marcelzwiers** [comment]
Like I said in your PR, I rather postpone BEP028 till it becomes relevant (if ever). For now I implemented a simple `bidscoiner.tsv` solution. Feel free to re-open if you miss anything
