### ISSUE TITLE
Derivatives data

### ISSUE THREAD

**Issue by DominikaZ** [Donders-Institute/bidscoin#218]
** General summary **
Function `bids.get_derivatives` decides what converted data go under derivatives folder. Would it be possible to add option for user to define that some of those won't go to derivatives? For example, we have some `RFFieldMaps` we would like to store under `fmap` as opposed to under `derivatives/Siemens/.../fmap`

**Comment by marcelzwiers** [comment]
Yes, that sounds reasonable. The specifications for what has to go into derivatives are a bit vague anyhow, so it's a good idea to let the user overrule that. I'll see if I can easily add an options for this

**Comment by marcelzwiers** [comment]
I added an option to make exceptions to what goes into derivatives. Is this what you had in mind?

**Comment by DominikaZ** [comment]
Yes, thank you! It works flawlessly.
