### ISSUE TITLE
Add CSA header support

### ISSUE THREAD

**Issue by DominikaZ** [Donders-Institute/bidscoin#219]
**Is your feature request related to a problem? Please describe.**
For some of our datasets, it would be safer for us to map via attributes in CSA header (e.g dcm2niix attribute `PulseSequenceDetails` that is extracted from this header). It would be amazing if bidscoin could also check this header if Manufacturer is Siemens in `bids.get_dicomfield`. I believe this can be also connected to #212.

**Describe the solution you'd like**
For example, `dicom_parser` https://github.com/open-dicom/dicom_parser could be used for this or smaller `csa_header` https://github.com/open-dicom/csa_header/tree/main#quickstart. Or something custom of course. For handling nested tags, maybe user could write tag1.tag2 which would be then splitted.

(I apologize for the multiple requests, and I appreciate your help with them. Thank you!).

**Comment by DominikaZ** [comment]
I understand that CSA header is a bit of a pain and will disappear in the future, however, many datasets are still using it and the transition will take time. I think if `dicom_parser` or `csa_header` would be used, reading it won't be such a big pain, the article mentions how `dicom_parser` can be used, `csa_header` cen be used like this:
```
from csa_header import CsaHeader

dcm = pydicom.dcmread("/path/to/file.dcm")
data_element = dcm.get((0x29, 0x1020))  # CSA Series Header Info
raw_csa = data_element.value
parsed_csa = CsaHeader(raw_csa).read()  # Final CSA header attributes in dictionary of dictionaries
```

Do you think it can be pain because of performance?
Is there something we could do for our data, like reading it with our script beforehand and writing somewhere useful information from CSA header that bidscoin could see?

**Comment by marcelzwiers** [comment]
Ok, that doesn't look too painful indeed. It doesn't have to impact performance that much because it can be implemented such that the CSA header is only parsed if the regular header doesn't contain the tag

**Comment by marcelzwiers** [comment]
Mhh, if I try it out in my bidscoin venv I get:
```console
pip install csa_header
ERROR: Could not find a version that satisfies the requirement csa_header (from versions: none)
ERROR: No matching distribution found for csa_header
(venv) marzwi@localhost:~/PycharmProjects/bidscoin> pip install csa_header
```

**Comment by marcelzwiers** [comment]
A more important issue is that the CSA header can have a nested structure, e.g. as in:
```python
>>> parsed_csa["SliceArray"]["Slice"][instance_number]["Position"]["Tra"]
```
This poses a problem for bidscoin, as it doesn't have a notion of this and extracts single keys (attributes) from the header

**Comment by DominikaZ** [comment]
> Mhh, if I try it out in my bidscoin venv I get:
> 
> ```
> (venv) marzwi@localhost:~/PycharmProjects/bidscoin> pip install csa_header
> ERROR: Could not find a version that satisfies the requirement csa_header (from versions: none)
> ERROR: No matching distribution found for csa_header
> ```

Yes, I am really sorry about that. It seems the repo is not on pypi although it claims it. So it can be added via:
'csa_header @ git+https://github.com/open-dicom/csa_header.git' in `pyproject.toml` dependencies. I tried it and it gives error that:
`csa_header requires a different Python: 3.8.10 not in '>=3.9'`
So this is not a way to go :(. Maybe if it would be updated.

`dicom_parser` when added to dependencies works, Getting CSA header:
```
from dicom_parser import Image
image = Image("/path/to/siemens/csa.dcm")
csa = image.header.get("CSASeriesHeaderInfo")  # Final CSA header attributes in dictionary of dictionaries
```

Other tags can be also extracted like this:
```
parsed_value = image.header.get('ImagingFrequency', '')
raw_value = image.header.raw['ImagingFrequency'].value
```

**Comment by DominikaZ** [comment]
> A more important issue is that the CSA header can have a nested structure, e.g. as in:
> 
> ```python
> >>> parsed_csa["SliceArray"]["Slice"][instance_number]["Position"]["Tra"]
> ```
> 
> This poses a problem for bidscoin, as it doesn't have a notion of this and extracts single keys (attributes) from the header

Maybe if user puts in attribute that is separated e.g by dots, it could be splitted and used like this:
```
key_string = "SliceArray.Slice.instance_number.Position.Tra
keys = key_string.split('.')
result = csa
for key in keys:
    if isinstance(result, dict):
        result = result.get(key, '')
    else:
        return ''

return key
```

**Comment by marcelzwiers** [comment]
If you want, you can open a PR with just 1 added line, e.g. on line 589 in `bids.py`:
```python
                # Try a recursive search
                if not value and value != 0:
                    for elem in dicomdata.iterall():
                        if tagname in (elem.name, elem.keyword, str(elem.tag), str(elem.tag).replace(', ',',')):
                            value = elem.value
                            break

                # Try reading the CSA header
                # TODO: Add some code here

                if not value and value!=0 and 'Modality' not in dicomdata:
                    raise ValueError(f"Missing mandatory DICOM 'Modality' field in: {dicomfile}")
```
In this way we can work together on it (if I do the PR I think I then can't give you permission to commit)

**Comment by DominikaZ** [comment]
> If you want, you can open a PR with just 1 added line, e.g. on line 589 in `bids.py`:
> 
> ```python
>                 # Try a recursive search
>                 if not value and value != 0:
>                     for elem in dicomdata.iterall():
>                         if tagname in (elem.name, elem.keyword, str(elem.tag), str(elem.tag).replace(', ',',')):
>                             value = elem.value
>                             break
> 
>                 # Try reading the CSA header
>                 if not value and value != 0:
>                     pass                # TODO: Add some code here
> 
>                 if not value and value!=0 and 'Modality' not in dicomdata:
>                     raise ValueError(f"Missing mandatory DICOM 'Modality' field in: {dicomfile}")
> ```
> 
> In this way we can work together on it (if I do the PR I think I then can't give you permission to commit)

Created :). I apologize, I will be unavailable throughout the day tomorrow. However, I will start working on it in the evening. Thank you for giving it a try!
