### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#22]
Add a tab where users can edit the bidsmap Options

**Comment by rutgervandeelen** [comment]
See commit eb1492cca9164c67a8d96cdf3ad63ebc49f2434f to the `master` branch.
A tab has been added with functionality to edit the `Options` section in the BIDSmap.
In addition, tooltips have been added.

Please review the validation of the user input. For example, 
1. Do we allow the BIDS version to be edited? It should namely be the version in `version.txt`.
2. Should we validate the `dcm2nixx` path and arguments?

**Comment by rutgervandeelen** [comment]
See commit 387bab6add62467bd1cd6085d02375c1c0dc1ae8 with latest changes.
