### ISSUE TITLE
Clicking on item in bidsmapper GUI crashes program

### ISSUE THREAD

**Issue by DominikaZ** [Donders-Institute/bidscoin#222]
This bug was introduced in commit `Add typing hints for bidsmap datatypes`: a184d75bc6b5fd96a74457267f9e325b90e1607e

row 881 in `bidseditor.py`:
```
        self.bidsdatatypes: List[str]    = [datatype for datatype in template_bidsmap[self.dataformat] if datatype not in self.unknowndatatypes.union(self.ignoredatatypes, {'subject', 'session'})]
```
unknowndatatypes is a list, so calling union on it crashes with:
`AttributeError: 'list' object has no attribute 'union'`

**Comment by marcelzwiers** [comment]
Thanks for reporting!
