### ISSUE TITLE
B0FieldSource as a list

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#228]
**Describe the bug**
If multiple fieldmaps are used for one functional image, the `B0FieldSource` should be a list. We're having trouble to compose that list in the mapping file. We used the yaml syntax but it seems not to work.

The log of bidscoiner doesn't have any entry for `B0FieldSource` under functional files.

**To reproduce**
Use something like this in the mapping file
```
B0FieldSource: 
  - magnetude1
  - magnetude2
  - phasediff
```

**Expected behavior**
`B0FieldSource` key with JSON array is added to the functional json files.

**Software version**
 - BIDScoin version 4.2.1
 - OS Debian 11

**Comment by marcelzwiers** [comment]
I'm not sure if I understand the problem, as the BIDS specification defines just a single tag, not a list, right? So
```
B0FieldSource: 
  - tag1
  - tag2
  - tag3
```
should be converted to
```
B0FieldSource: tag1tag2tag3
```
???

**Comment by marcelzwiers** [comment]
> B0FieldIdentifier | RECOMMENDED | string or array of strings
Aha, I didn't know this, I'll see what I can do

**Comment by mateuszpawlik** [comment]
[BIDS specification](https://bids-specification.readthedocs.io/en/stable/glossary.html#b0fieldsource-metadata) says that it's a string or an array of strings. I don't really know how tools should use it, but with `IntendedFor` we can say that we use three fieldmaps for one functional image.

**Comment by mateuszpawlik** [comment]
Should be fine but it shouldn't matter [both forms are correct syntax](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#yaml-basics).

**Comment by marcelzwiers** [comment]
Yes I know, but I mean that's how you can pass it in the bidseditor?

**Comment by mateuszpawlik** [comment]
Ah, I'm not using the BIDS editor :see_no_evil: But if I did, I'd be fine with the compact syntax.

**Comment by marcelzwiers** [comment]
I just tested it and, except for the `<<session>>` value, it worked just fine? In the template I did:
```yaml
    meta: &fmap_meta
      B0FieldIdentifier: [tag1, <<session>>tag2]
 ```
And the I got this in the json sidecar file:
```json
    "B0FieldIdentifier": [
        "tag1",
        "<<session>>tag2"
    ]
```

**Comment by mateuszpawlik** [comment]
Looks fine to me. I can try to test more next week (with the `<<session>>` tag) as we're planning to upgrade to BIDScoin 4.3.0 and test some mappings.

**Comment by marcelzwiers** [comment]
Actually, entering `[tag1, <<session>>tag2]` in the bidseditor is interpreted as a string, so that doesn't work (but then `<<session>>` does), giving for `sub-001_ses-01_acq-fieldmap2p4iso_magnitude1.json`:
```json
    "B0FieldIdentifier": "[tag1, 01tag2]"
```

**Comment by marcelzwiers** [comment]
NB: passing `["tag1", '<<session>>tag2']` in the bidseditor correctly (besides `<<session>>`) gives:
```json
    "B0FieldIdentifier": [
        "tag1",
        "<<session>>tag2"
    ]
```
