### ISSUE TITLE
IntendedFor field not stored

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#23]
To produce this bug:
1) Click on the 'edit' button in the main window of the bidseditor
2) Choose 'fmap' as a BIDS modality
3) Add some text in the 'IntendedFor' cell
4) Click 'OK'
5) Click on the 'edit' button of the edited/fmap sample
6) The IntendedFor cell is empty :-(

**Comment by marcelzwiers** [comment]
The yaml-file with IntendedFor field also looks broken:

`  - provenance: /home/mrphys/marzwi/tmp/4Marcel_fmap/raw/sub-001/ses-mri01/006-AAHead_Scout_32ch-head-coil_MPR_tra/00001_1.3.12.2.1107.5.2.19.45416.2017121915053941999777073.IMA
    attributes:
      SeriesDescription: AAHead_Scout_32ch-head-coil_MPR_tra
      SequenceVariant: SP
      SequenceName: '*fl3d1_ns'
      ScanningSequence: GR
      MRAcquisitionType: 3D
      FlipAngle: '8'
      EchoNumbers: 1
      EchoTime: '1.37'
      RepetitionTime: '3.15'
      ImageType: "['ORIGINAL', 'PRIMARY', 'MPR', 'ND', 'NORM']"
      ProtocolName: AAHead_Scout_32ch-head-coil
      PhaseEncodingDirection:
    bids:
      acq_label: AAHeadScout32chheadcoilMPRtra
      run_index: <<1>>
      dir_label: ''
      suffix: epi
      IntendedFor: ''
      ce_label: ''
      rec_label: ''
      task_label: ''
      echo_index: ''
      ? ''
      : <<test>>
`

**Comment by rutgervandeelen** [comment]
I have noticed two issues related to this bug:
1. `IntendedFor` is not properly handled when updating the BIDS map
2. An unwanted empty key `""` is added when the BIDS modality is changed.

The first issue is easy to solve. Change 
```
# Obtain the orginal bidsmap key name from the short display name
key = DISPLAY_KEY_MAPPING.get(display_key, '')
```
to:
```
# Obtain the original bidsmap key name from the short display name
# If no mapping is available use the display key name itself
key = DISPLAY_KEY_MAPPING.get(display_key, display_key)
```

I am currently investigating how to solve issue 2.

**Comment by rutgervandeelen** [comment]
When BIDS modality changes, the BIDS values in the table change, and the `cell_was_clicked` function is triggered. If this is the case, we do not want the BIDS values to be updated. I propose to change the cell_was_clicked function to

```

**Comment by marcelzwiers** [comment]
Resolved by dropping the '_label' and '_index' from the template
