### ISSUE TITLE
New BIDS feature of dcm2niix

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#231]
When checking dcm2niix for a new release, I came across it's new [BidsGuess feature](https://github.com/rordenlab/dcm2niix/tree/master/BidsGuess). It should help wrapper software like BIDScoin in producing BIDS data.

**Comment by marcelzwiers** [comment]
Yes, thanks, Chris Rorden already notified me about this. But unfortunately it's not useful for BIDScoin (BIDScoin does its own guessing by way of the template bidsmap)

**Comment by marcelzwiers** [comment]
What would possibly be useful is a dcm2niix option to use the BIDS entities in the output name to store information that is now appended to the output name (which causes a lot of pain for BIDS converters)
