### ISSUE TITLE
Postfix error

### ISSUE THREAD

**Issue by madeleinebarter** [Donders-Institute/bidscoin#232]
I'm trying to convert an entire 135 participant data set into BIDS format. Each subject has both PAR/REC files and DICOM files, as organized in the picture. The bidsmapper is only recognizing the PAR/REC files and not taking in the DICOM files. How do I resolve this? Also, for some participants, bidsmapper won't recognize any files and will just move onto the next participant. I'm running BIDScoin 4.3.2 and MacOS Sonoma with an M2 chip

<img width="1592" alt="Screenshot 2024-04-03 at 2 57 15 PM" src="https://github.com/Donders-Institute/bidscoin/assets/165948257/06f292af-cc6e-4e05-afbf-74e5010dda8b">

**Comment by madeleinebarter** [comment]
Update, I changed the folder name dicom to DICOM and now it parses the DICOM files, but it is ignoring the PAR/REC files

**Comment by madeleinebarter** [comment]
Sorry, another update. I realized that I only need it to read the PAR/REC files, so it's all good now. However, when I ran the bidscoiner with my new bidsmap, it cycled through all of sub-001 and then errored out on sub-002. I am getting this error code : "Unexpected postix 'echo-1' found" How do I fix this?

<img width="1380" alt="Screenshot 2024-04-03 at 3 55 58 PM" src="https://github.com/Donders-Institute/bidscoin/assets/165948257/113e7e1d-300b-4ef1-a27c-82ee0e5842d5">

**Comment by marcelzwiers** [comment]
On Google I found this post about python 3.6 and MacOS. Are you by any chance using python 3.6?

> If you have installed Python 3.6 on OSX and are getting the "SSL: CERTIFICATE_VERIFY_FAILED" error when trying to connect to an https:// site, it's probably because Python 3.6 on OSX has no certificates at all, and can't validate any SSL connections. This is a change for 3.6 on OSX, and requires a post-install step, which installs the certifi package of certificates. This is documented in the file [ReadMe.rtf](https://github.com/python/cpython/blob/560ea272b01acaa6c531cc7d94331b2ef0854be6/Mac/BuildScript/resources/ReadMe.rtf#L35), which you can find at /Applications/Python\ 3.6/ReadMe.rtf (see also the file [Conclusion.rtf](https://github.com/python/cpython/blob/560ea272b01acaa6c531cc7d94331b2ef0854be6/Mac/BuildScript/resources/Conclusion.rtf#L15-L19), and the script [build-installer.py](https://github.com/python/cpython/blob/560ea272b01acaa6c531cc7d94331b2ef0854be6/Mac/BuildScript/build-installer.py#L207-L220) that generates the macOS installer).

**Comment by madeleinebarter** [comment]
I upgraded and re-ran bidsmapper and bidscoiner, it no longer gives me a postfix error, but it still stops running at that same spot. I'm not sure what the issue could be
<img width="2055" alt="Screenshot 2024-04-05 at 11 22 18 AM" src="https://github.com/Donders-Institute/bidscoin/assets/165948257/62671b3f-086f-48e5-84e8-3396cb3896d8">

**Comment by marcelzwiers** [comment]
Ok, I see, I need to skip the file completely. Can you try:

```console
pip install --force-reinstall --no-deps git+https://github.com/Donders-Institute/bidscoin@9ac5195b680a7b6120dd93876ea79ad3e4d6ccfc
```

**Comment by marcelzwiers** [comment]
And if you don't have git, you can 1) download the latest code from github and pip install locally, or 2) just copy the dcm2niix2bids code from github into your installation, or 3) take the latest dcm2niix2bids.py file and import this as a new plugin

**Comment by madeleinebarter** [comment]
Thanks! The postfix error is now fixed for me.

**Comment by marcelzwiers** [comment]
Ok, thanks for reporting this
