### ISSUE TITLE
typo in nibabel2bids.py

### ISSUE THREAD

**Issue by Remi-Gau** [Donders-Institute/bidscoin#233]
I believe there is an error in this line:

https://github.com/Donders-Institute/bidscoin/blob/5fb16295b3e514c4afe052a43bdcb2828ca362b9/bidscoin/plugins/nibabel2bids.py#L158C74-L158C84

I think `datatype` should be `datasource.datatype`.

```python
LOGGER.bcdebug(f"Existing/duplicate '{datasource.datatype}' {datasource.dataformat} sample: {sourcefile}")
```

<details>
<summary>
error
</summary>
<pre>
bidsmapper -b /scratch/anw/edangremont/nipoppy/dataset/bids/code/bidscoin/bidsmap.yaml -p nibabel2bids -n '*' -f /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/ /scratch/anw/edangremont/nipoppy/dataset/bids/

INFO |

INFO | -------------- START BIDSmapper ------------

INFO | >>> bidsmapper sourcefolder=/scratch/anw/edangremont/nipoppy/dataset/scratch/source_data bidsfolder=/scratch/anw/edangremont/nipoppy/dataset/bids bidsmap=/scratch/anw/edangremont/nipoppy/dataset/bids/code/bidscoin/bidsmap.yaml template=/home/anw/edangremont/.bidscoin/4.3.2/templates/bidsmap_dccn.yaml plugins=['nibabel2bids'] subprefix=* sesprefix=None store=False force=True

INFO | Reading: /scratch/anw/edangremont/nipoppy/dataset/bids/code/bidscoin/bidsmap.yaml

INFO | Checking the bidsmap run-items:

INFO | Reading: /home/anw/edangremont/.bidscoin/4.3.2/templates/bidsmap_dccn.yaml

INFO | Adding default bidsmap options from the nibabel2bids plugin

INFO | Checking the bidsmap run-items:

SUCCESS | All datatypes and options in the template bidsmap are valid

INFO | Deleting previous bidsmap: /scratch/anw/edangremont/nipoppy/dataset/bids/code/bidscoin/bidsmap.yaml

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT007/ses-bl (subject 1/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT007/ses-bl

INFO | Discovered 'extra_data' Nibabel sample: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT007/ses-bl/COGT_007_t1.nii.gz

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT008/ses-bl (subject 2/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT008/ses-bl

INFO | Discovered 'extra_data' Nibabel sample: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT008/ses-bl/COGT_008_t1.nii.gz

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT010/ses-bl (subject 3/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT010/ses-bl

INFO | Discovered 'extra_data' Nibabel sample: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT010/ses-bl/COGT_010_t1.nii.gz

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT013/ses-bl (subject 4/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT013/ses-bl

INFO | Discovered 'extra_data' Nibabel sample: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT013/ses-bl/COGT_013_t1.nii.gz

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT014/ses-bl (subject 5/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT014/ses-bl

INFO | Discovered 'extra_data' Nibabel sample: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT014/ses-bl/COGT_014_t1.nii.gz

INFO | Mapping: /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT015/ses-bl (subject 6/116)

VERBOSE | Executing plugin: nibabel2bids -> /scratch/anw/edangremont/nipoppy/dataset/scratch/source_data/COGT015/ses-bl

Traceback (most recent call last):

  File "/scratch/anw/edangremont/nipoppy/nipoppy-env/bin/bidsmapper", line 8, in <module>

    sys.exit(main())

  File "/scratch/anw/edangremont/nipoppy/nipoppy-env/lib/python3.10/site-packages/bidscoin/bidsmapper.py", line 251, in main

    bidsmapper(rawfolder    = args.sourcefolder,

  File "/scratch/anw/edangremont/nipoppy/nipoppy-env/lib/python3.10/site-packages/bidscoin/bidsmapper.py", line 141, in bidsmapper

    module.bidsmapper_plugin(sesfolder, bidsmap_new, bidsmap_old, template, store)

  File "/scratch/anw/edangremont/nipoppy/nipoppy-env/lib/python3.10/site-packages/bidscoin/plugins/nibabel2bids.py", line 158, in bidsmapper_plugin

    LOGGER.bcdebug(f"Existing/duplicate '{datasource.datatype}' {dataformat} sample: {sourcefile}")

NameError: name 'dataformat' is not defined
</pre>
</details>

**Comment by marcelzwiers** [comment]
Yes, correct, `dataformat` should be `datasource.dataformat` (i.e. I agree with your PR)
