### ISSUE TITLE
Quickly add common tags in BIDSMapper/editor

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#235]
**Is your feature request related to a problem? Please describe.**

I'd like to select multiple series and add them to 'anat' or 'exclude' or 'extra_data'

**Describe the solution you'd like**
I think a checkbox to select multiple series in the editor/mapper, then an option to move all of them to 'exclude' for e.g.

**Describe alternatives you've considered**

None - other ideas?

**Comment by marcelzwiers** [comment]
I implemented your feature request with a feature that was on my wish list for a long time (comparing run-items). Is this (the latest github version) what you had in mind?

**Comment by marcelzwiers** [comment]
![image](https://github.com/Donders-Institute/bidscoin/assets/15156015/79cf1ae1-3cf7-4bb2-814a-b0f0f45bb41c)

![image](https://github.com/Donders-Institute/bidscoin/assets/15156015/ed97a341-f805-4f03-a798-972611522b64)

I assume this is what you had in mind, please re-open if not
