### ISSUE TITLE
Unable to find dicoms in the tmp directory that the program creates

### ISSUE THREAD

**Issue by MRIDude** [Donders-Institute/bidscoin#236]
** General summary **
I just installed bidscoin and I am trying to learn how to use it. After installation i did test the installation and i did resolve all errors.  For my first data set to practice on, I moved DICOMS of a single subject with two time points into a folder labeled it sourcedata. I made sure it adhered to the folder structure required in the data organization page of the tutorial.    I ran the command 

` bidsmapper $HOME/bids/sourcedata $HOME/bids`

> INFO | 
> INFO | -------------- START BIDSmapper ------------
> INFO | >>> bidsmapper sourcefolder=/home/aaron/bids/sourcedata bidsfolder=/home/aaron/bids bidsmap=bidsmap.yaml template=/home/aaron/.bidscoin/4.3.2/templates/bidsmap_dccn.yaml plugins=[] subprefix=None sesprefix=None store=False force=False
> INFO | Reading: /home/aaron/bids/code/bidscoin/bidsmap.yaml
> INFO | Checking the bidsmap run-items:
> INFO | Reading: /home/aaron/.bidscoin/4.3.2/templates/bidsmap_dccn.yaml
> INFO | Checking the bidsmap run-items:
> SUCCESS | All datatypes and options in the template bidsmap are valid
> INFO | Mapping: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr0 (subject 1/1)                                                                                                                                      
> INFO | Detected a flat data-structure in: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr0                                                                                                                          
> INFO | Making temporary copy: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr0 -> /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0                                                                   
> INFO | >> Sorting: /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0 (215 files)                                                                                                                     
> VERBOSE |    Creating:  /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/002-t1_mpr_ns_sag                                                                                                          
> VERBOSE |    Creating:  /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/003-t2_tse_tra                                                                                                             
> VERBOSE |    Creating:  /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/001-localizer                                                                                                              
> VERBOSE | Executing plugin: dcm2niix2bids -> /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0                                                                                                       
> INFO | Mapping: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr3 (subject 1/1)                                                                                                                                      
> INFO | Detected a flat data-structure in: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr3                                                                                                                          
> INFO | Making temporary copy: /home/aaron/bids/sourcedata/sub-001/ses-mriVYr3 -> /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3                                                                   
> INFO | >> Sorting: /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3 (355 files)                                                                                                                     
> VERBOSE |    Creating:  /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/003-t2_spc_0p9mm_iso                                                                                                       
> VERBOSE |    Creating:  /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/002-t1_mpr_0p9mm                                                                                                           
> VERBOSE |    Creating:  /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/001-localizer                                                                                                              
> VERBOSE | Executing plugin: dcm2niix2bids -> /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3                                                                                                       
> INFO | Opening the bidseditor                                                                                                                                                                                      
> WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/002-t1_mpr_ns_sag/00004.dcm not found
> WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/003-t2_tse_tra/00164.dcm not found
> WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/002-t1_mpr_0p9mm/00004.dcm not found
> WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/003-t2_spc_0p9mm_iso/00180.dcm not found
> WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/001-localizer/00001.dcm not found
> WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/001-localizer/00001.dcm not found
> WARNING | Can no longer find the source file: /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/002-t1_mpr_0p9mm/00004.dcm
> INFO | -------------- FINISHED! -------------------
> INFO | 
> INFO | The following BIDScoin errors and warnings were reported:
> 
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/002-t1_mpr_ns_sag/00004.dcm not found
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/003-t2_tse_tra/00164.dcm not found
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/002-t1_mpr_0p9mm/00004.dcm not found
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/003-t2_spc_0p9mm_iso/00180.dcm not found
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp5sn36ipa/home/aaron/bids/sourcedata/sub-001/ses-mriVYr0/001-localizer/00001.dcm not found
> 2024-05-13 17:11:32 - WARNING | /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/001-localizer/00001.dcm not found
> 2024-05-14 10:56:53 - WARNING | Can no longer find the source file: /tmp/tmp2bsfpnz5/home/aaron/bids/sourcedata/sub-001/ses-mriVYr3/002-t1_mpr_0p9mm/00004.dcm
> <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 
> INFO | For the complete log see: /home/aaron/bids/code/bidscoin/bidsmapper.log
> NB: That folder may contain privacy sensitive information, e.g. pathnames in logfiles and provenance data samples
> 

So bidcoin was able to see that there is one subject and two sessions with dicoms in the folder. It can also grab info from the DICOMS. However, it labeled the MPRAGE and T2 Space as extra_data and not anat, I tried changing it and it gave an error saying that the DICOMS did not exist in a temp directory. 

Did I do something wrong?

**Comment by marcelzwiers** [comment]
Hi there, you are almost there I think. Your data structure is supported but it is non-standard (from BIDScoin's perspective that is). The tmp data is needed to reorganise the data in a format that BIDScoin supports as standard, but that data needs to be re-accessed once you change the datatype (and in your case the automatic datatyping failed because the prior knowledge in the default template is tailored to the DCCN center). You can pass the `-s` flag to the bidsmapper to store a representative sample of each datatype, which should solve your issue.

Happy bidscoining!

**Comment by MRIDude** [comment]
Ok this works.

**Comment by samuelholly** [comment]
Hello, I have the same problem, however, when I use the `-s` option with `bidsmapper` and attempt to change datatype for a file in bidseditor GUI, I get the following error (holly is my user name):
```
Traceback (most recent call last):
  File "C:\Users\holly\Anaconda3\envs\qsiprep\Lib\site-packages\bidscoin\bidseditor.py", line 1561, in accept_run
    self.output_bidsmap.update(self.source_run.datatype, self.target_run)
  File "C:\Users\holly\Anaconda3\envs\qsiprep\Lib\site-packages\bidscoin\bids.py", line 1513, in update
    self.insert_run(runitem)
  File "C:\Users\holly\Anaconda3\envs\qsiprep\Lib\site-packages\bidscoin\bids.py", line 1475, in insert_run
    targetfile = self.store['target']/sourcefile.relative_to(self.store['source'])
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\holly\Anaconda3\envs\qsiprep\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'D:\\DBS_bidsfolder\\code\\bidscoin\\provenance\\tmpbfrlkihe\\DBS_DCM_files\\sub-002\\ses-01\\016-t2_space_da-fl_sag_p3_iso_0.9\\sub-002_t2_space_da-fl_sag_p3_iso_0.9_262.dcm' is not in the subpath of 'C:\\Users\\holly\\AppData\\Local\\Temp'
``` 
Any help is appreciated.

Samuel
