### ISSUE TITLE
Installation error in Windows 10 pro 

### ISSUE THREAD

**Issue by JulianGaviriaL** [Donders-Institute/bidscoin#244]
During installation, I get the following error:
 ``bids/code/bidscoin/*.log`` files (a summary of them is listed at the end)](error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120)

The installation satisfactorily ended and the follwing plug-ins:
pip install bidscoin                      
pip install bidscoin[dcm2niix2bids]         
pip install bidscoin[spec2nii2bids]

The error seems to be related to:
pip install bidscoin[deface] 

Creating library build\temp.win-amd64-cpython-313\Release\traits\ctraits.cp313-win_amd64.lib and object build\temp.win-amd64-cpython-313\Release\traits\ctraits.cp313-win_amd64.exp
      ctraits.obj : error LNK2001: unresolved external symbol Py_TRASHCAN_SAFE_END
      ctraits.obj : error LNK2001: unresolved external symbol Py_TRASHCAN_SAFE_BEGIN
      build\lib.win-amd64-cpython-313\traits\ctraits.cp313-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for traits
Failed to build traits
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (traits)

**Software version**
 - BIDScoin version 4.4.0
 - Windows 10 pro

**Additional context**
I think this error is due to the O.S. (Windows 10 pro) and microsoft visual studio. The installation in Windows 11 ran smoothly.

**Comment by marcelzwiers** [comment]
Could it be due to using python 3.13?

**Comment by JulianGaviriaL** [comment]
Indeed. The installation ran smoothly in:

- BIDScoin version 4.4.0
- Windows 10 pro
- Python **3.12.6**

**Comment by JulianGaviriaL** [comment]
thank you very much

**Comment by marcelzwiers** [comment]
The problem is that some of bidscoin's dependencies are not yet supporting the new 3.13 version. I expect this to resolve itself soon, when the authors of these dependencies release updates.
