### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/bidscoin#29]
Make windows/widgets scale properly.

**Comment by rutgervandeelen** [comment]
See branch `feature_scale_windows` for the latest results:
* Enable using full screen for main window
* Enable using full screen for edit window
* Tighten inspect window
* Tighten about window

**Comment by marcelzwiers** [comment]
See 94b11446579d542ae52f31c7ee96fc8e009224bc
