### ISSUE TITLE
SpacingBetweenSlices - (slightly) different for all FMRI runs

### ISSUE THREAD

**Issue by karl-koschutnig** [Donders-Institute/bidscoin#39]
Hi and thank you so much for this great tool. I was convinced to use it after a little chat at the OHBM in Roma ;-)

Here is my little problem: 
After upgrading to the latest version we have serious problems defining fmri-sequences in the bidsmapper. The reason seems to be that the DicomTag (0018,0088) Spacing Between Slices is slightly different for each functional run. For example one run is 3.600000000471292 the next is 3.6000000877783. So, is there a way to a) round this value or b) to ignore this attribute?

Thank you
Karl

**Comment by marcelzwiers** [comment]
Funny, I had the same problem today as well and I am working on it. The
easiest way is to just remove the lines from the bidmap_tamplate.yaml file
(then it will also be removed in all the derived yaml files)

Cheers,
Marcel

P.s. I discovered a few more bugs that I also fixed so keep watching for a
new release soon

_____________________
Sent from my phone

Op di 9 jul. 2019 14:21 schreef karl-koschutnig <notifications@github.com>:

**Comment by marcelzwiers** [comment]
I have now solved this (removed the field from the template) in the current (unreleased) version. Use:
`git+https://github.com/Donders-Institute/bidscoin to test this`

**Comment by marcelzwiers** [comment]
ANd for the fun of it, try to run the tools with the `-t bidsnap_dccn` option to see how our site template works out for you :-)
