### ISSUE TITLE
Download tutorial test data

### ISSUE THREAD

**Issue by dlevitas** [Donders-Institute/bidscoin#50]
This is in reference to #49 

We're attempting to run the workflow on the tutorial data (to see how it compares to our data); however, the documentation for getting the test data seems to be geared towards the Donders Institute system (i.e. ```module add bidscoin```). Is there another way for users to get access to the test data?

Thanks!

**Comment by marcelzwiers** [comment]
Added `pulltutorialdata`, see afda3344b2849829fb2fc12f3af41ef6064a82b7
