### ISSUE TITLE
Images from README are not shown on PyPi

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/bidscoin#53]
The README.md is also used as documentation on https://pypi.org/project/bidscoin/. However, the images which appear properly on github are not shown on PyPi.

I had the same issue with EEGsynth on https://github.com/eegsynth/eegsynth and https://pypi.org/project/eegsynth/ but did manage to solve that.

**Comment by marcelzwiers** [comment]
Yes, that is because, unlike github, pypi doesn't support relative url's. I hesitate to fix this by hardcoding full urls (pointing to the images on github), as it seems to be a pypi issue

**Comment by robertoostenveld** [comment]
I had the same issue with https://github.com/eegsynth/eegsynth and https://pypi.org/project/eegsynth/ not only with the (only) image there, but also with the relative links in the README to other pieces of documentation.

I solved that in https://github.com/eegsynth/eegsynth/blob/master/setup.py by not using the plain README.md as `long_description`, but by doing a search-and-replace on the relative URLs, i.e. updating them in the package that is built and sent to PyPi.

**Comment by marcelzwiers** [comment]
The documentation has moved to https://bidscoin.readthedocs.io, I do not fully support docs elsewhere
