### ISSUE TITLE
README

### ISSUE THREAD

**Issue by wsojka00** [Donders-Institute/bidscoin#63]
"Because all the mapping information can be easily edited with the **Graphical User Interface (GUI)**, BIDScoin requires no programming knowledge in order to use it."

GUI link does not work: https://github.com/Donders-Institute/bidscoin/blob/master/screenshots.html

**Comment by marcelzwiers** [comment]
True, it doesn't work from github, but it does from https://bidscoin.readthedocs.io (I have to chose and prefer to have it working there)

**Comment by marcelzwiers** [comment]
I don't see an easy way to resolve this, so I'm closing the issue
