### ISSUE TITLE
PhaseEncodingDirection problem

### ISSUE THREAD

**Issue by alexanderkroner** [Donders-Institute/bidscoin#73]
First of all, thank you for this great tool!

I'm trying to set the PhaseEncodingDirection via the BIDS editor in the DICOM Attributes panel but encountered an issue. When I set the value to e.g. `j-` for a functional run and save the bidsmap.yaml file, both the bidsmapper and bidscoiner detect the run as `extra_data` instead of `func`. This can be reverted by manually editing the PhaseEncodingDirection entry in the bidsmap.yaml file to the default `''` value.

Running the tool without a defined PhaseEncodingDirection works as expected and I can later add that attribute to the BIDS json file. However, I was wondering whether I'm doing something wrong and if there's a way to set it in bidscoin without running into this issue.

**Comment by marcelzwiers** [comment]
Yes, the DICOM attributes panel is for advanced usage (you should have gotten a warning about this (see e.g. also here #70). The DICOM attributes panel is used for recognizing DICOM files. So yes, your edit made it not match the source file anymore. You should edit the BIDS output panel, because that's what you wanted I guess, change the BIDS output name :-)

**Comment by alexanderkroner** [comment]
Thank you for the fast reply! Yes, I got the warning `Expert usage: User has set DICOM['PhaseEncodingDirection'] from '' to 'j-'` but I understand now that the DICOM attributes shouldn't be edited.

Apart from changing the output name by editing the values in the right panel, I would also like to add the `PhaseEncodingDirection` attribute to the BIDS json file. In my case, this attribute is required because I'm using fieldmaps but is currently not included when running bidscoiner. So I guess the only way to correct for that is through manually adjusting the json file, is that right?

**Comment by marcelzwiers** [comment]
In the new version that I am about to release you can do exactly what you
want. You can already try it out by pip installing from GitHub (see
readthedocs)

_____________________
Sent from my phone

Op ma 10 mei 2021 09:28 schreef Alexander Kroner ***@***.***>:
