### ISSUE TITLE
Adjust window size to table contents

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#74]
The `bidseditor` GUI opens with a windowsize that is too small to properly see the table contents. I fiddled around with `adjustSize`, `ResizeToContents` and `sizeAdjustPolicy`, but I can't get it to work. It's probably just one or two lines, so if you have a good understanding of the Qt5 toolkit, I would be happy to get some help here :-)

**Comment by mateuszpawlik** [comment]
I found this a long time ago but didn't had time to try out the porposed solutions: https://forum.qt.io/topic/74787/adjusting-window-size-to-table-contents

**Comment by marcelzwiers** [comment]
Yes, it must be something like that, I tried several settings but I just failed to get it to work properly. At some point I should also port the code to Qt6, perhaps it will be solved then...
