### ISSUE TITLE
Inspect DICOM header

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#8]
In the file browser tab and/or in the edit window, it would be nice to have the option to inspect the full DICOM header, as in bids.py:get_dicomfield:
 `dicomdict = pydicom.dcmread(dicomfile, force=True)      # The DICM tag may be missing for anonymized DICOM files`

**Comment by rutgervandeelen** [comment]
Added code in experimental branch:
If the user double clicks on DICOM filename in the `File browser` tab or in the `BIDS map` tab a popup is presented. 

See commit d39d2c5f1e7c7034e54c448d38180d306f87de9f
