### ISSUE TITLE
[ENH] Allowing the user to put a path pattern to infer subject and session

### ISSUE THREAD

**Issue by yjmantilla** [Donders-Institute/bidscoin#86]
As of now BIDSCOIN constrains its input directory to set of allowed file structures. I understand supporting more file structures can be a headache. 

A nice step towards that which wouldnt need redesign of the directory logic of BIDSCOIN is allowing to infer the subject and session directly from the filepath without the need of fixed labels for them but a "path pattern" provided by the user.

In sovabids I implemented a function inspired in the following feature of mp3tag:

![mp3tag](https://user-images.githubusercontent.com/36543115/122836377-c15edd80-d2b7-11eb-8c95-7c5c294e112b.gif)

So a hacky way of doing it is modifying the subid_sesid method of DataSource in the following way:

```python
    def subid_sesid(self, subid: str= '<<SourceFilePath>>', sesid: str= '<<SourceFilePath>>') -> Tuple[str, str]:
...
        # Add default value for subid and sesid (e.g. for the bidseditor)
        if subid == "<<PathPattern>>":
            # assume sesid has the rule
            if sesid.count('%') != 0 and sesid.count('%') % 2 == 0:
                result = parse_string_from_template(self.path.__str__(),sesid)
            else:
                result = {}
            if 'subject' not in result or 'session' not in result:
                LOGGER.error(f"Could not parse sub/ses-id information from '{self.path.parent}'")
                return '', ''
            LOGGER.info(f"parsed: {result} from {self.path.__str__()}")
            subid = result['subject']
            sesid = result['session']
        if subid == '<<SourceFilePath>>':
...
```
So if the user sets the subid as <<PathPattern>> we try to parse the filepath given what the user inputs on the sesid.

The function to do the parsing is https://github.com/yjmantilla/sovabids/blob/f6a8c0f8801bf1d8806b1e3bb4d537927ab06bef/sovabids/utils.py#L90-L139

The user would need to pass the path pattern using forward slashes to split directories to avoid bugs...

Let me know if I should do a PR.

**Comment by marcelzwiers** [comment]
A quickly looked at your parser and I think if you do `%key1%.%key2% border is my <<key1><key2>>? That's something I could implement without a problem.

**Comment by marcelzwiers** [comment]
I could implement it such that the user gives your pattern as a subprefix as an input argument. In my case it would then be `sub-%subid%` and you can pass your user pattern

**Comment by marcelzwiers** [comment]
What do you use now for a sub- and sesprefix?

**Comment by marcelzwiers** [comment]
If we implement your name-parsing method in `DataSource.filesystem()` method then we can use it everywhere, e.g. in the bids- or meta-table, that may be a very useful enhancement of BIDScoin

**Comment by marcelzwiers** [comment]
![image](https://user-images.githubusercontent.com/15156015/123082982-e4a49c80-d41f-11eb-857d-ff301a2b2c5d.png)

**Comment by marcelzwiers** [comment]
Ok, change of plan, I decided to implement the parsing of the filesystem properties using regular expressions. It turns out they are quite simple for my use case and they have all the power and flexibility when needed. Moreover, regexps are used everywhere, as opposed to the mp3tag parsing syntax. Let's see if we can make sovabids work with it?

**Comment by yjmantilla** [comment]
Sorry for the late reply Marcel, been 

>A quickly looked at your parser and I think if you do %key1%.%key2% to define your keywords and border, that would be equivalent to my <<key1><key2>> dynamic values?

Heck, I would need to test that.

> Can you provide a few examples of your "path patterns"?

Here are some examples I did for testing: https://github.com/yjmantilla/sovabids/blob/main/tests/test_path_parser.py

```
string = r'Y:\code\sovabids\_data\lemon2\sub-010002\ses-001\resting\sub-010002.vhdr'
path_pattern = 'sub-%ignore%\ses-%entities.session%\%entities.task%\sub-%entities.subject%.vhdr'
result = parse_string_from_template(string,path_pattern,'%')

assert result['entities']['subject'] == '010002'
assert result['entities']['session']=='001'
assert result['entities']['task']=='resting'
assert result['ignore']=='010002'

string = r'Y:\code\sovabids\_data\lemon2\sub-010004\ses-001\sub-010004.vhdr'
path_pattern = 'ses-%entities.task%/s%ignore%-%entities.subject%.vhdr'
result = parse_string_from_template(string,path_pattern,'%')
assert result['entities']['task']=='001'
assert result['entities']['subject']=='010004'
assert result['ignore']=='ub'

string = 'y:\\code\\sovabids\\_data\\lemon\\sub-010002.vhdr'

#%%
path_pattern = 'sub-%entities.subject%.vhdr'
result = parse_string_from_template(string,path_pattern,'%')
assert result['entities']['subject'] == '010002'

#%%
path_pattern = '%ignore%\sub-%entities.subject%.vhdr'
result = parse_string_from_template(string,path_pattern,'%')
assert result['entities']['subject'] == '010002'
assert result['ignore'] == 'y:/code/sovabids/_data/lemon' #USE POSIX

#%%
path_pattern = '%entities.subject%.vhdr'
result = parse_string_from_template(string,path_pattern,'%')
assert result['entities']['subject'] == 'y:/code/sovabids/_data/lemon/sub-010002'

#%%
path_pattern = 'sub-%entities.subject%'
result = parse_string_from_template(string,path_pattern,'%')
assert result['entities']['subject'] == '010002.vhdr'
```


>What do you use now for a sub- and sesprefix?

Hmmm, well this is actually really variable. For example one of our datasets looks like this:

![image](https://user-images.githubusercontent.com/36543115/123163787-baf76f80-d437-11eb-914d-a405909bcbf4.png)

That is, there is no prefix u.u . Thats why I dont rely on prefixes but a "path pattern" where the use tells me where in the filepath is the info of interest. 

For example one of the above examples is G1_001_V0_CE.cnt , so the path pattern would be %group%_%subject%_%session%_%task%.cnt . A prefix is not required. Just that there is some kind of separator between different fields of information.


>If we implement your name-parsing method in DataSource.filesystem() method then we can use it everywhere, e.g. in the bids- or meta-table, that may be a very useful enhancement of BIDScoin

I very much agree. Basically any info in the filepath could be retrievable, which may be indeed very useful.

>p.s. Your mp3tag parsing method could also be implemented using regular expressions, which would be more powerful but also more complex for the users

Yes, I agree. REGEX could do so much more but the cost for the user kind of screws with the original purpose.

> So here I don't know how parse_pattern() should look like, I want it to be 1) generic / independent of sovabids and 2) working also for sovabids.

Im not following exactly what you mean by "how parse_pattern() should look like" , you mean how the argument looks like? 
I tried to do the function as generic as possible, so I included an splitter argument (default %). And whatever the users puts between the percentages will be the field. 

The only arbitrary stuff I would think is the dot notation I did for parsing nested keys. This could also be configurable as an argument.

> Maybe I can just use your parse_string_from_template() for this (I don't know what the 'from_template' is / does)?

I think that would be true, although it is kind of bad to require sovabids as an package just for base functionality. Since is just a little idea of sovabids maybe we can just copy the code to the utils of bidscoin?  

The 'from_template' is just kind of a bad name. Basically the template I was referring to was actually de string with the path pattern. (sub-%subject%.cnt) for example. I can change the name for something more appropriate  

> Can you do a PR using the above filesystem-implementation?
> Ok, change of plan, I decided to implement the parsing of the filesystem properties using regular expressions. It turns out they are quite simple for my use case and they have all the power and flexibility when needed. Moreover, regexps are used everywhere, as opposed to the mp3tag parsing syntax. Let's see if we can make sovabids work with it?

I would be open to try your regex code. Mainly the use-case of sovabids is that it doesn't need much knowledge of regex.

**Comment by marcelzwiers** [comment]
I pushed (an untested) commit. The new regexp implementation is actually quite clean and consistent, e.g. I got rid of the <<SourceFilePath>> keyword completely!

**Comment by yjmantilla** [comment]
Ahh I see, I do see the following problem. From my understanding regex is just finding stuff between two strings.

So for example if I have a tree like this ``/dataset/task/session/subject`` then we dont have unique strings separating the fields , we only know the order in which they appear on the path. My intuition is that the current regex implementation couldn't deal with this case because it requires prefixes and/or suffixes unique to the field we are parsing.

Now this use-case may be outside of the scope of bidscoin but I think it can happen in real life. Is there a way to deal with it in regex?

>As you can see in the screenshot, it doesn't yet work 100% correctly yet for sessionless data repositories

Guess the user would just punt "1" in session if there is no session,right?

**Comment by marcelzwiers** [comment]
Wow, that seems to me like a really unhandy way to organize your source data! 8-). I think you can still extract what you need, but the regexp becomes more complicated, e.g. `/.*?/(.*?)/` to extract `task` or `/.*?/.*?/(.*?)/` to extract `session`?

**Comment by yjmantilla** [comment]
>Wow, that seems to me like a really unhandy way to organize your source data! 8-)

Yeap :/ , surprisingly is not that un common. The following are from two random eeg datasets in osf:

![image](https://user-images.githubusercontent.com/36543115/123270332-6ef30c00-d4c5-11eb-937f-db6dca5bc7c5.png)

Although in the left one the sub does have the prefix, the second number doesn't have one, guess it refers to the run or something like that.

In the right one there are no prefixes for subject, nor task, nor session... so yeah hehe, not the best practices.

So in general, is the wild west how researchers 

>  I think you can still extract what you need, but the regexp becomes a bit more complicated, e.g. /.*?/(.*?)/ to extract task or /.*?/.*?/(.*?)/ to extract session?

It does work:
![image](https://user-images.githubusercontent.com/36543115/123271805-cf367d80-d4c6-11eb-9e7f-75e55520a4da.png)
![image](https://user-images.githubusercontent.com/36543115/123271996-f9883b00-d4c6-11eb-80aa-a584b02f1104.png)

So I guess for BIDSCOIN that would be the way for this use-case, so this issue can be closed

For sovabids I think I will add this regex functionality but still retain the other parser because this way of doing it may not be sufficiently intuitive for the less technical users.

**Comment by marcelzwiers** [comment]
Tip, instead of using strings to store path you should really be using the pathlib library, it is fantastic and far superior to os.path.etc.etc.etc. Check [this](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/) out! You don't need to worry about forward backward slashes in your regexp, always posix:

```python
        if tagname.startswith('filepath'):
            if tagname.startswith('filepath:'):
                match = re.search(tagname[9:], self.path.parent.as_posix())
                if match:
                    return match.group(nr)
```
