### ISSUE TITLE
[ENH] remap button on the GUI

### ISSUE THREAD

**Issue by yjmantilla** [Donders-Institute/bidscoin#87]
This issue is related to #86 . If the user changes the subject/session info inside the GUI the a remapping should be done for the changes to stick (or something like that I remember discussing with @marcelzwiers ) . So a button for redoing the bidsmapper may be useful.

**Comment by marcelzwiers** [comment]
I thought about it a bit more, and as long as the bidsmapper has seen all the data then the shortlist should be ok. So I'm closing this issue until it proves to be a problem
