### ISSUE TITLE
[ENH] Allowing the bidscoiner to just wrap around a plugin

### ISSUE THREAD

**Issue by yjmantilla** [Donders-Institute/bidscoin#88]
I managed to use the BIDSCOINER with the sovabids plugin I made, nevertheless one difficulty I had is that the BIDSCOINER currently writes some files and directories of BIDS.

SOVABIDS interfaces with MNE-BIDS which also writes this files and directories. Making some conflicts along the way. 

A way to overcome this is by providing a boolean ``just_wrap`` to the bidscoiner. This boolean would affect only 3 parts of the bidscoiner (as far as i know):

```python
def bidscoiner(rawfolder: str, bidsfolder: str, subjects: list=(), force: bool=False, participants: bool=False, bidsmapfile: str='bidsmap.yaml',just_wrap: bool=False) -> None:
    """
    Main function that processes all the subjects and session in the sourcefolder and uses the
    bidsmap.yaml file in bidsfolder/code/bidscoin to cast the data into the BIDS folder.

    :param rawfolder:       The root folder-name of the sub/ses/data/file tree containing the source data files
    :param bidsfolder:      The name of the BIDS root folder
    :param subjects:        List of selected subjects / participants (i.e. sub-# names / folders) to be processed (the sub- prefix can be removed). Otherwise all subjects in the sourcefolder will be selected
    :param force:           If True, subjects will be processed, regardless of existing folders in the bidsfolder. Otherwise existing folders will be skipped
    :param participants:    If True, subjects in particpants.tsv will not be processed (this could be used e.g. to protect these subjects from being reprocessed), also when force=True
    :param bidsmapfile:     The name of the bidsmap YAML-file. If the bidsmap pathname is relative (i.e. no "/" in the name) then it is assumed to be located in bidsfolder/code/bidscoin
    :param just_wrap:         If you want bidscoiner to just wrap-around a plugin converter (leave everything to them)

    :return:                Nothing
    """
```

```python
    if not just_wrap:
        # Create a dataset description file if it does not exist
        dataset_file = bidsfolder/'dataset_description.json'
        generatedby  = [{"Name":"BIDScoin", "Version":localversion, "CodeURL":"https://github.com/Donders-Institute/bidscoin"}]
        if not dataset_file.is_file():
            LOGGER.info(f"Creating dataset description file: {dataset_file}")
            dataset_description = {"Name":                  "REQUIRED. Name of the dataset",
                                "GeneratedBy":           generatedby,
                                "BIDSVersion":           str(bidscoin.bidsversion()),
                                "DatasetType":           "raw",
                                "License":               "RECOMMENDED. The license for the dataset. The use of license name abbreviations is RECOMMENDED for specifying a license. The corresponding full license text MAY be specified in an additional LICENSE file",
                                "Authors":               ["OPTIONAL. List of individuals who contributed to the creation/curation of the dataset"],
                                "Acknowledgements":      "OPTIONAL. Text acknowledging contributions of individuals or institutions beyond those listed in Authors or Funding",
                                "HowToAcknowledge":      "OPTIONAL. Instructions how researchers using this dataset should acknowledge the original authors. This field can also be used to define a publication that should be cited in publications that use the dataset",
                                "Funding":               ["OPTIONAL. List of sources of funding (grant numbers)"],
                                "EthicsApprovals":    	["OPTIONAL. List of ethics committee approvals of the research protocols and/or protocol identifiers"],
                                "ReferencesAndLinks":    ["OPTIONAL. List of references to publication that contain information on the dataset, or links", "https://github.com/Donders-Institute/bidscoin"],
                                "DatasetDOI":            "OPTIONAL. The Document Object Identifier of the dataset (not the corresponding paper)"}
        else:
            with dataset_file.open('r') as fid:
                dataset_description = json.load(fid)
            if 'BIDScoin' not in [generatedby_['Name'] for generatedby_ in dataset_description.get('GeneratedBy',[])]:
                LOGGER.info(f"Adding {generatedby} to {dataset_file}")
                dataset_description['GeneratedBy'] = dataset_description.get('GeneratedBy',[]) + generatedby
        with dataset_file.open('w') as fid:
            json.dump(dataset_description, fid, indent=4)

        # Create a README file if it does not exist
        readme_file = bidsfolder/'README'
        if not readme_file.is_file():
            LOGGER.info(f"Creating README file: {readme_file}")
            readme_file.write_text(f"A free form text ( README ) describing the dataset in more details that SHOULD be provided\n\n"
                                f"The raw BIDS data was created using BIDScoin {localversion}\n"
                                f"All provenance information and settings can be found in ./code/bidscoin\n"
                                f"For more information see: https://github.com/Donders-Institute/bidscoin\n")

```

```python
    if not just_wrap:
        # Write the collected data to the participant files
        LOGGER.info(f"Writing subject data to: {participants_tsv}")
        participants_table.replace('','n/a').to_csv(participants_tsv, sep='\t', encoding='utf-8', na_rep='n/a')

        LOGGER.info(f"Writing subject data dictionary to: {participants_json}")
        with participants_json.open('w') as json_fid:
            json.dump(participants_dict, json_fid, indent=4)

```

Let me know if i should do a PR

**Comment by marcelzwiers** [comment]
I'm not sure if this is an issue that needs to be solved by BIDScoin? BIDScoin only writes (or updates) these three files if they don't exist, shouldn't MNE-BIDS do the same? Which of the three files cause issues for MNE-BIDS?

**Comment by yjmantilla** [comment]
> I'm not sure if this is an issue that needs to be solved by BIDScoin? BIDScoin only writes (or updates) these three files if they don't exist, shouldn't MNE-BIDS do the same? Which of the three files cause issues for MNE-BIDS?

Indeed the problem is MNE-BIDS, right now is complaining because of the bids version:

>Traceback (most recent call last):
  File "y:/code/sovabids/examples/bidscoin_example.py", line 107, in <module>     
    bidscoiner(rawfolder    = source_path,
  File "y:\code\bidscoin\bidscoin\bidscoiner.py", line 194, in bidscoiner
    module.bidscoiner_plugin(session, bidsmap, bidsfolder, personals)
  File "y:\code\bidscoin\bidscoin\plugins\sova2coin.py", line 238, in bidscoiner_plugin
    write_raw_bids(raw, bids_path=bids_path,overwrite=True)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\mne_bids\write.py", line 1284, in write_raw_bids
    make_dataset_description(bids_path.root, name=" ", overwrite=overwrite,
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\mne_bids\write.py", line 911, in make_dataset_description
    raise ValueError('Previous BIDS version used, please redo the '
ValueError: Previous BIDS version used, please redo the conversion to BIDS in a new directory after ensuring all software is updated

Now, BIDSCOIN should only update/append/merge/do-nothing? if the file exist; but since the file indeed wont exist at start of the call to the bidscoiner, he will make that file before the call to mne-bids is done ; then mne-bids notices there are already some files there and maybe he tries to update but because of the bids version difference, he throws an exception.

Now, I artificially changed the versions so they were the same and saw what happened: Indeed there was no exception.

The following did happen:

- the dataset_description file is overwritten by mne-bids so for example the generated_by : bidscoin field was lost.
- the participants information generated by mne-bids was replaced completely by the an empty participants file written at the end of bidscoin:

https://github.com/Donders-Institute/bidscoin/blob/3ca5a64c9f015c32f35a29de1397864850ac6daf/bidscoin/bidscoiner.py#L214-L220

Now, the empty participants file was my fault (I didn't use the  ``personals`` dictionary inside my alpha bidscoiner sovabids plugin) . Nevertheless this file was indeed written by mne-bids but it got replaced ( meaning bidscoin always replaces the file as the code suggest).


I still think it is a good idea for bidscoin to just pass the information to the chosen bids writer of the plugin via the just_wrap argument I propose; but that is a more personal opinion. The solution in a more conservative way is that the participants json is not always replaced in case it exist.

**Comment by marcelzwiers** [comment]
> The following did happen:
>
> *   the dataset_description file is overwritten by mne-bids so for example the generated_by : bidscoin field was lost.

I think MNE_BIDS should really allow for the possibility that people may use multiple tools to convert a single dataset.

> *   the participants information generated by mne-bids was replaced completely by the an empty participants file written at the end of bidscoin:

That's interesting nevertheless, because I tried to make it such that bidscoin only adds info, never throws anything away. Can you show me how the participants.tsv of MNE-BIDS looked like? But indeed, the plugin should handle it properly, I'll see what I can do to improve this

I can make a flag to not write any [modality agnostic files](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html)

**Comment by yjmantilla** [comment]
> I think MNE_BIDS should really allow for the possibility that people may use multiple tools to convert a single dataset.

I agree, thats on that side.

> the replace suggests so, but it first reads the existing file, then it replaces it with the updated content

Ahh I see, it tries to not throw away the participants as long as they are in the participants table (which is filled by the personals dict if i remember correctly). Since I didn't use the personals dict it just assumed I had no participant info. Guess what is missing is checking if the json exist already instead of relying on run-time variables like the participants table?

>I can make a flag to not write any modality agnostic files
Anyhow I agree with this.

**Comment by marcelzwiers** [comment]
Correct, I was just writing something similar, me reading the table at the start and writing it at the end is probably a continuous cause for problems. I will move updating the table to the plugin and drop passing the `personals` dictionary.

**Comment by marcelzwiers** [comment]
So now it is just the bidsversion in `dataset_description` that gives MNE-BIDS troubles and a bit of loss of 'GeneratedBy' information. I think you can best handle this in your sova2bidscoin plugin (i.e. changing the bidsversion right before you run MNE-BIDS).

**Comment by yjmantilla** [comment]
I agree. That is on MNE-BIDS side. Next week  I will be working on the sovabids backend and also try to do some PRs on mne-bids.
I think this is ready to be closed.
