### ISSUE TITLE
[BUG] (?) 'Recording' is not a required EEG-BIDS field

### ISSUE THREAD

**Issue by yjmantilla** [Donders-Institute/bidscoin#89]
When converting files to bids using the sovabids plugin I get the following warning:

```bash
2021-06-21 15:56:34 - WARNING | Invalid bidsmap: BIDS eeg entity Y:\code\sovabids\_data\lemon_bidscoin_input\sub-010004\ses-001\resting\sub-010004.vhdr -> "recording: None" is not allowed according to the BIDS standard
```

Apparently there is a "Recording" field which Im not setting but I don't remember seeing it on the BIDS-EEG specification, nor I saw it on the schema files you have for EEG (although I did that superficially).

Could you double check that?(I may be wrong)

**Comment by marcelzwiers** [comment]
The warning means that in your bidsmap EEG section, `provenance: Y:\code\sovabids\_data\lemon_bidscoin_input\sub-010004\ses-001\resting\sub-010004.vhdr` there is a bids dictionary field `recording: None`? I can't check that it is in your bidsmap

**Comment by yjmantilla** [comment]
Indeed, you are right, what I have is:

```yaml
    bids:
      task: <<entities.task>>
      acq:
      recording:
      run: <<1>>
      suffix: eeg

```

So as you say, removing that solved the issue.

Now, before closing the issue... Why doesn't this happen with the 'acq' field? I mean nor 'acq'  nor 'recording' are needed by EEG-BIDS but only 'recording' complains? 

When I checked the schema file of eeg you have there isn't even a mention of a 'recording' field (https://github.com/Donders-Institute/bidscoin/blob/master/bidscoin/schema/datatypes/eeg.yaml) 

So my intuition is that for acq he recognizes is optional but when I forcefully added a field on the bids part of the yaml he assumed it was required since it didn't know anything more from it?

Anyhow, this is ready to be close, just curious about this behaviour.

**Comment by marcelzwiers** [comment]
BIDScoin complains about the bidsmap (differently for each datatype):
1. When a required entity value is not present
2. When an expected entity key is missing
3. When a non-bids / illegal entity key is present (which applied to `recording`)

For details see bids.check_run()
