### ISSUE TITLE
A reset button

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#9]
If users mess up, they may want to go back to the start-up state. It would therefore be good to have a 'reload' / 'restore' button on the bottom of the main window, next to the 'save' button

![image](https://user-images.githubusercontent.com/15156015/58463430-20cb7d00-8134-11e9-983a-5687cb543e36.png)

**Comment by rutgervandeelen** [comment]
Reload button has been added. Reload functionality still needs to be implemented.
