### ISSUE TITLE
Physiol log error

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#95]
Having a weird error with some physiol logs. Any idea? :)
Thanks!
![image](https://user-images.githubusercontent.com/31721414/124944468-ada1ce00-e050-11eb-8a3c-d731bf6c7e6d.png)

**Comment by marcelzwiers** [comment]
That's indeed weird, it seems if there is some info missing in the DICOM...? It is hard for me to debug this from a distance, also because I didn't write the algorithm, I only ported that code from Matlab, maybe they can help you:
https://github.com/CMRR-C2P/MB

**Comment by marcelzwiers** [comment]
See issue #103, perhaps you can also continue this issue on the physiopy github page, right @smoia?

**Comment by smoia** [comment]
@marcelzwiers, I don't think this is a problem just on our side - maybe raising an exception in bidscoin to catch these kind of issues (missing variables due to extension and file type not matching) would be more appropriate. I know it's a mess, but it might help.
