### ISSUE TITLE
Output participants.tsv after every new participant? 

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#96]
Last issue for a while I promise ;) 
Just finished coining a lot of data, but due to #95 my participants.tsv did not write correctly for the first 120 participants in the dataset. Bidscoiner continues as usual for the first 120:
![image](https://user-images.githubusercontent.com/31721414/125156042-d340eb80-e1a6-11eb-8c61-20d978c648e2.png)

But my participants.tsv looks like this:
![image](https://user-images.githubusercontent.com/31721414/125156063-f4094100-e1a6-11eb-8965-b219eeb9a6fd.png)

Is it possible to write the participants.tsv out for the whole dataset after the invocation of bidscoiner? Even if the data has already been coined in a previous run? Or potentially check if the entry exists in the participants.tsv before writing it?

**Comment by marcelzwiers** [comment]
Hi Thom,

The more feedback the better, so please keep on going :-)

As to your question, I already implemented that (commit
99c4921154c94a0f8554553d95d6d2f1a10a1fe1), so that feature will be in the
next release.

Cheers,
Marcel

Op za 10 jul. 2021 om 09:49 schreef Thom Shaw ***@***.***>:

**Comment by marcelzwiers** [comment]
There is also an unfinished / poorly tested utility that just writes a participants.tsv file. It may work for you:
bidscoin/bidsparticipants.py

**Comment by thomshaw92** [comment]
Awesome! The bidsparticipants.py worked!
![image](https://user-images.githubusercontent.com/31721414/125156778-9b3ba780-e1aa-11eb-86ea-573573d2983e.png)
