### ISSUE TITLE
Minimal map file requirements

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#97]
I'm trying to write a minimal map file for a single study conversion. However, from the errors it seems that some yaml keys are assumed to exist in the source code. Can anyone point me to some requirements on the structure and keys of the map file?

Here's my map file:
```
Options:   
  bidscoin:
    version: 3.6.2               
  plugins:                       
    dcm2bidsmap: {}

DICOM:
  anat:
    attributes:
      ProtocolName: '*T1*'
    bids:
      suffix: T1w
```

And the output of the mapper command (I removed the irrelevant INFO part):
```
$ singularity exec bidscoin-sandbox/ bidsmapper -b <mymap.yaml> <sourcefolder> <bidsfolder>
2021-07-13 15:47:55 - INFO | 
2021-07-13 15:47:55 - INFO | -------------- START BIDSmapper ------------
...
2021-07-13 15:47:56 - INFO | Executing plugin: dcm2bidsmap.py
Traceback (most recent call last):
  File "/usr/local/bin/bidsmapper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidsmapper.py", line 182, in main
    bidsmapper(rawfolder    = args.sourcefolder,
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidsmapper.py", line 123, in bidsmapper
    module.bidsmapper_plugin(session, bidsmap_new, bidsmap_old, template, store)
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/plugins/dcm2bidsmap.py", line 52, in bidsmapper_plugin
    run, datatype, index = bids.get_matching_run(sourcefile, bidsmap_old, dataformat)
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bids.py", line 1028, in get_matching_run
    match = any([run[matching][attrkey] not in [None,''] for matching in ('filesystem','attributes') for attrkey in run[matching]])     # Normally match==True, but make match==False if all attributes are empty
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bids.py", line 1028, in <listcomp>
    match = any([run[matching][attrkey] not in [None,''] for matching in ('filesystem','attributes') for attrkey in run[matching]])     # Normally match==True, but make match==False if all attributes are empty
TypeError: string indices must be integers
```

**Comment by mateuszpawlik** [comment]
I've made my example to work but the question remains. I also had to use my map file as both map (`-b`) and template (`-t`) to force `bidsmapper` not to use some defaults.

Map file:
```
Options:   
  bidscoin:
    version: 3.6.2               
  plugins:                       
    dcm2bidsmap: {}

DICOM:

  subject: <<SourceFilePath>>
  session: <<SourceFilePath>>

  anat:
  - provenance:
    attributes:
      ProtocolName: '.*T1.*'
    bids:
      suffix: T1w
```

**Comment by marcelzwiers** [comment]
Well, the documentation about writing bidsmaps is here: https://bidscoin.readthedocs.io/en/stable/advanced.html#site-specific-customized-template

Your bidsmap misses quite a few fields. But why do you want to manually write a study bidsmap in the first place? This is only needed if you want to write a (e.g. site-specific) generic template... And you should use the `-t` option to pass a template, the bidsmapper will make the study bidsmap out of it (the `-b` option is if you want to use a specific study bidsmap, e.g. one that you previously saved using a non-standard name).

**Comment by marcelzwiers** [comment]
What exactly is the problem that you are trying to solve?

**Comment by mateuszpawlik** [comment]
Thank you for prompt explanation of the difference. I see I missed that. I'm just starting to use BIDScoin.

In that sense, the goal is to have a concise set of rules - minimal template. Files with general rules tend to grow to satisfy many different cases, e.g., the [dccn template](https://github.com/Donders-Institute/bidscoin/blob/master/bidscoin/heuristics/bidsmap_dccn.yaml). Then, it's rather difficult to track the provenance. I'd like to keep in the template only what's relevant.

**Comment by marcelzwiers** [comment]
I see, you want to create a template that you can re-use multiple times. Good thing to do, my advice is to edit a copy of the bidsmap_dccn.yaml file such that it satisfies your needs. The template doesn't keep track of provenance, that field is only filled in the study bidsmap (it is needed to re-read the attributes when changing the datatype). The template bidsmap contains the generic rules, the study bidsmap contains the minimal set of study specific rules (that the bidscoiner will use)

**Comment by mateuszpawlik** [comment]
Now I understand it better, thank you. I'd like to keep my template short and therefore I wanted to know which elements are necessary. For example, I'd like to avoid all keys without the values unless it's necessary to keep them.

**Comment by mateuszpawlik** [comment]
I believe I have to learn more about the power of the templates :-) I still don't understand the exact purpose of the keys without values. They are only in the first rule in the dccn template and act as set of key-value pairs which can be used in the consecutive rules and even overwritten. However, to me they seem not to be used for matching. But this goes a little bit off topic.

**Comment by marcelzwiers** [comment]
If you have one empty ("extremely wide") {'ProtocolName': ''} rule in your temple and have two different T1 images (i.e. with different ProtocolNames) in your study, then the bidsmapper will replace the empty values with the actual Protocolnames and will create *two* very narrow rules in your study bidsmap, e.g. {'ProtocolName': 'myfirstprot'} and {'ProtocolName': 'mysecondprot'}.

**Comment by mateuszpawlik** [comment]
Thanks a lot, I think I got it now. Let me try. It's still a little bit complicated.

Consider a specific template run-item _R_. First, all images _M_ matching specific rules (e.g. regex on DICOM fields) of R are found. Next, for every different set of values from the images in _M_ of the empty rules in _R_ (DICOM fields, e.g., 'ImageType: ~'), a separate study run-item will be generated with the DICOM values filled in.

Consider this example template run-item which finds all T1w images thanks to `ProtocolName: .*T1.*` pattern:
```
anat:
  - provenance:
    attributes:
      ImageType: ~
      ProtocolName: .*T1.*
    bids:
      suffix: T1w
```
Then, if the T1w images differ in `ImageType` or in `ProtocolName`, specific study run-items will be generated, one for each different set of those values.

I've also seen that the baseline (e.g. with a dummy template rule matching everything) is to generate one study rule for each _seriesfolder_ in the input, when I use _seriesfolder_ organization.

**Comment by mateuszpawlik** [comment]
To come back to the issue topic, certain keys in the template file are required. To find them, I needed to execute `bidsmapper` several times and see what Python complained on. I list some of them. A bidsmap schema with mandatory elements could help.
```
Options:
  bidscoin:
    version:
```
```
DICOM:
  subject:
  session:
```
```
[data type]:
  - provenance:
    attributes:
    bids:
```

**Comment by marcelzwiers** [comment]
> 
> 
> Thanks a lot, I think I got it now. Let me try. It's still a little bit complicated.
> 
True, making a template is considered advanced usage :-)

> Consider a specific template run-item _R_. First, all images _M_ matching specific rules (e.g. regex on DICOM fields) of R are found. Next, for every different set of values from the images in _M_ of the empty rules in _R_ (DICOM fields, e.g., 'ImageType: ~'), a separate study run-item will be generated with the DICOM values filled in.
> 
> [..]
> 
> Then, if the T1w images differ in `ImageType` or in `ProtocolName`, specific study run-items will be generated, one for each different set of those values.
> 
Correct

> I've also seen that the baseline (e.g. with a dummy template rule matching everything) is to generate one study rule for each _seriesfolder_ in the input, when I use _seriesfolder_ organization.
I don't understand what you mean here

**Comment by marcelzwiers** [comment]
> To come back to the issue topic, certain keys in the template file are required. To find them, I needed to execute `bidsmapper` several times and see what Python complained on. I list some of them. A bidsmap schema with mandatory elements could help.

Well, I use the schema file from the bids-specification for this. It is installed with bidscoin in `yourpathtobidscoin/bidscoin/schema`, but you can also find the same files here:
https://github.com/bids-standard/bids-specification/tree/master/src/schema

**Comment by mateuszpawlik** [comment]
> > I've also seen that the baseline (e.g. with a dummy template rule matching everything) is to generate one study rule for each _seriesfolder_ in the input, when I use _seriesfolder_ organization.
> 
> I don't understand what you mean here

Sorry. I'll try to clarify. Lets assume we have only one rule in the template that matches every image. Then, the generated study template will not have only one rule, but a specific rule for every _seriesfolder_ in the input.

**Comment by marcelzwiers** [comment]
Run-items in the bidsmap represent the different datatypes, as defined by the attribute / property key-value pairs. If the key-value pairs change per session (for instance they would if you would use something like `AcquisitionDate`), then the number of rules in your study bidsmap would be the same as the number of sessions. But this is not the idea, you should use keys that represent the acquisition type, such as `EchoTime`. Then, even if you have only one very broad rule in your template, the number of narrowed rules in your study bidsmap will be a shortlist of the nr of datatypes in your data (thus independent of the nr of sessions/subjects).

**Comment by marcelzwiers** [comment]
In other words, the bidsmap tells bidscoin how to convert a datatype, and when it knows that it can do that as many times as needed, i.e. for every subject in your repository.

**Comment by mateuszpawlik** [comment]
Thanks a lot for all the help and clarifications. I think I have much better understanding of the templates now. I propose to close the issue.

**Comment by marcelzwiers** [comment]
> To come back to the issue topic, certain keys in the template file are required. To find them, I needed to execute `bidsmapper` several times and see what Python complained on. I list some of them. A bidsmap schema with mandatory elements could help.

Long time ago that you asked for this but I now added your schema file :-) (which I now use in my pytests, I still use the BIDS schema files for bidscoin runtime tests):

89f7d279f4b8cd29bd4d3c8238153b88b317034d

**Comment by mateuszpawlik** [comment]
I'm sorry for not replying. That is really nice and exactly what I wanted :smiley:
